// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change component structure or accessibility attributes
//
// AIOutputsPanel
// ──────────────
// Right-drawer content shared by SessionWorkspacePage and ProjectWorkspacePage.
// Renders the AI generation outputs as a 2-column thumbnail grid with a small
// "filter / view" toolbar, a dashed empty state when no outputs exist, and a
// footer link to the full results page.
//
// This component is purely presentational. The page owns the outputs data
// (SessionWorkspacePage → generatedResults from the chat turns;
// ProjectWorkspacePage → project outputs/files) and forwards them here as
// `items`. Click selection is emitted so the page can open the relevant
// detail / overlay (chat on session, artboard on project).

<template>
  <aside class="ai-outputs" :aria-label="ariaLabel">
    <!-- Header — title + filter / view toggle -->
    <header class="ai-outputs__header">
      <div class="ai-outputs__title-block">
        <h2 class="ai-outputs__title">{{ title }}</h2>
        <p v-if="subtitle" class="ai-outputs__subtitle">{{ subtitle }}</p>
      </div>
      <div class="ai-outputs__header-actions">
        <button
          type="button"
          class="ai-outputs__icon-btn"
          :class="{ 'ai-outputs__icon-btn-on': layout === 'grid' }"
          aria-label="网格视图"
          @click="emit('layout-change', 'grid')"
        >
          <OiIcon name="grid-2x2" :size="16" />
        </button>
        <button
          type="button"
          class="ai-outputs__icon-btn"
          :class="{ 'ai-outputs__icon-btn-on': layout === 'rows' }"
          aria-label="列表视图"
          @click="emit('layout-change', 'rows')"
        >
          <OiIcon name="rows" :size="16" />
        </button>
        <button
          type="button"
          class="ai-outputs__icon-btn"
          aria-label="筛选结果"
          @click="emit('filter')"
        >
          <OiIcon name="filter" :size="16" />
        </button>
      </div>
    </header>

    <!-- Empty state -->
    <div v-if="items.length === 0" class="ai-outputs__empty">
      <div class="ai-outputs__empty-frame" aria-hidden="true">
        <div class="ai-outputs__empty-corners">
          <span class="ai-outputs__corner ai-outputs__corner--tl" />
          <span class="ai-outputs__corner ai-outputs__corner--tr" />
          <span class="ai-outputs__corner ai-outputs__corner--bl" />
          <span class="ai-outputs__corner ai-outputs__corner--br" />
        </div>
        <div class="ai-outputs__empty-glyph">
          <OiIcon name="spark-fill" :size="22" />
        </div>
      </div>
      <p class="ai-outputs__empty-title">{{ emptyTitle }}</p>
      <p class="ai-outputs__empty-hint">{{ emptyHint }}</p>
    </div>

    <!-- Outputs grid -->
    <div v-else class="ai-outputs__body">
      <ol :class="['ai-outputs__list', `ai-outputs__list--${layout}`]">
        <li
          v-for="item in items"
          :key="item.id"
          class="ai-outputs__item"
        >
          <button
            type="button"
            class="ai-outputs__card"
            :class="{
              'ai-outputs__card-on': item.id === selectedId,
              [`ai-outputs__card-${item.kind}`]: true,
            }"
            :aria-label="`查看 ${item.filename || item.kind || '产出'}`"
            :aria-pressed="item.id === selectedId"
            @click="emit('item-select', item.id)"
          >
            <div class="ai-outputs__frame">
              <img
                v-if="item.kind === 'image' && item.url"
                :src="item.url"
                :alt="item.filename || 'AI 产出'"
                class="ai-outputs__image"
                loading="lazy"
              >
              <div v-else-if="item.kind === 'video'" class="ai-outputs__video">
                <img
                  v-if="item.url"
                  :src="item.url"
                  :alt="''"
                  class="ai-outputs__image"
                >
                <span class="ai-outputs__video-badge" aria-hidden="true">
                  <svg viewBox="0 0 16 16" width="14" height="14" fill="currentColor">
                    <path d="M5 3.5v9l7-4.5-7-4.5Z" />
                  </svg>
                </span>
              </div>
              <div v-else class="ai-outputs__generic" aria-hidden="true">
                <OiIcon name="image-card" :size="22" />
              </div>
              <span class="ai-outputs__kind">{{ kindLabel(item.kind) }}</span>
            </div>
            <div class="ai-outputs__meta">
              <div class="ai-outputs__filename ellipsis">{{ item.filename || '未命名' }}</div>
              <div class="ai-outputs__sub">
                <span class="ai-outputs__time">{{ item.timeLabel }}</span>
                <button
                  type="button"
                  class="ai-outputs__more"
                  :aria-label="`更多 ${item.filename || '产出'}`"
                  @click.stop="emit('item-menu', item.id, $event)"
                >
                  <OiIcon name="more" :size="14" />
                </button>
              </div>
            </div>
          </button>
        </li>
      </ol>

      <button
        v-if="showViewAll"
        type="button"
        class="ai-outputs__view-all"
        @click="emit('view-all')"
      >
        <span>{{ viewAllLabel }}</span>
        <OiIcon name="chevron-down" :size="14" />
      </button>
    </div>
  </aside>
</template>

<script setup lang="ts">
import OiIcon from 'src/components/ui/OiIcon.vue'
import type { AIOutputItem } from 'src/components/session-workspace/types'

// Re-export for downstream consumers (e.g. ProjectWorkspaceRightPanel) that
// import the item shape from this module.
export type { AIOutputItem }

// ── Props ────────────────────────────────────────────────────────────────────

withDefaults(defineProps<{
  title?: string
  subtitle?: string
  emptyTitle?: string
  emptyHint?: string
  items: AIOutputItem[]
  selectedId?: string | null
  layout?: 'grid' | 'rows'
  showViewAll?: boolean
  viewAllLabel?: string
  ariaLabel?: string
}>(), {
  title: 'AI 产出',
  subtitle: '',
  emptyTitle: 'AI 生成的结果将出现在这里',
  emptyHint: '在中央创作面板描述你想要的画面，AI 产出将自动汇总于此',
  selectedId: null,
  layout: 'grid',
  showViewAll: false,
  viewAllLabel: '查看全部',
  ariaLabel: 'AI 产出面板',
})

const emit = defineEmits<{
  (e: 'item-select', id: string): void
  (e: 'item-menu', id: string, event: MouseEvent): void
  (e: 'layout-change', layout: 'grid' | 'rows'): void
  (e: 'filter'): void
  (e: 'view-all'): void
}>()

// ── Helpers ──────────────────────────────────────────────────────────────────

function kindLabel(kind: AIOutputItem['kind']): string {
  if (kind === 'image') return '图像'
  if (kind === 'video') return '视频'
  if (kind === 'audio') return '音频'
  return '文件'
}
</script>

<style lang="scss" scoped>
// ── AI outputs panel ─────────────────────────────────────────────────────────

.ai-outputs {
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
  min-height: 0;
  padding: 18px 16px 16px;
  gap: 14px;
  background: linear-gradient(180deg, var(--imago-bg-deep), var(--imago-bg-void) 30%);
}

// ── Header ───────────────────────────────────────────────────────────────────

.ai-outputs__header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 12px;
  flex-shrink: 0;
}

.ai-outputs__title-block {
  min-width: 0;
}

.ai-outputs__title {
  margin: 0;
  font-size: 14px;
  font-weight: 600;
  color: var(--imago-text-primary);
  letter-spacing: 0.005em;
}

.ai-outputs__subtitle {
  margin: 2px 0 0;
  font-size: 11.5px;
  color: var(--imago-text-dim);
  line-height: 1.4;
}

.ai-outputs__header-actions {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  padding: 3px;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-pill);
  background: var(--imago-bg-surface);
  flex-shrink: 0;
}

.ai-outputs__icon-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 26px;
  height: 26px;
  padding: 0;
  border: 0;
  border-radius: var(--imago-radius-pill);
  background: transparent;
  color: var(--imago-text-muted);
  cursor: pointer;
  transition: color 120ms ease, background 120ms ease;
}

.ai-outputs__icon-btn:hover {
  color: var(--imago-text-primary);
  background: var(--imago-cyan-06);
}

.ai-outputs__icon-btn--active,
.ai-outputs__icon-btn-on {
  color: var(--imago-neon-cyan);
  background: var(--imago-cyan-08);
}

// ── Empty state ──────────────────────────────────────────────────────────────

.ai-outputs__empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  flex: 1 1 auto;
  text-align: center;
  padding: 24px 12px;
  gap: 14px;
}

.ai-outputs__empty-frame {
  position: relative;
  width: 92px;
  height: 92px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: var(--imago-radius-lg);
  background: radial-gradient(circle at center, rgba(0, 240, 255, 0.06), transparent 70%);
  border: 1px solid var(--imago-border-soft);
  flex-shrink: 0;
}

.ai-outputs__empty-corners {
  position: absolute;
  inset: -4px;
  pointer-events: none;
}

.ai-outputs__corner {
  position: absolute;
  width: 12px;
  height: 12px;
  border: 1.5px solid var(--imago-border-cyan);
  border-radius: 2px;
}

.ai-outputs__corner--tl { top: 0; left: 0; border-right: 0; border-bottom: 0; }
.ai-outputs__corner--tr { top: 0; right: 0; border-left: 0; border-bottom: 0; }
.ai-outputs__corner--bl { bottom: 0; left: 0; border-right: 0; border-top: 0; }
.ai-outputs__corner--br { bottom: 0; right: 0; border-left: 0; border-top: 0; }

.ai-outputs__empty-glyph {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 36px;
  height: 36px;
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-raised);
  color: var(--imago-neon-cyan);
  filter: drop-shadow(0 0 8px rgba(0, 240, 255, 0.4));
}

.ai-outputs__empty-title {
  margin: 0;
  font-size: 12.5px;
  color: var(--imago-text-secondary);
  font-weight: 600;
}

.ai-outputs__empty-hint {
  margin: 0;
  font-size: 11.5px;
  color: var(--imago-text-faint);
  max-width: 220px;
  line-height: 1.5;
}

// ── Body / grid ──────────────────────────────────────────────────────────────

.ai-outputs__body {
  flex: 1 1 auto;
  min-height: 0;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.ai-outputs__list {
  list-style: none;
  margin: 0;
  padding: 0 2px 4px 0;
  display: grid;
  gap: 12px;
  overflow-y: auto;
  flex: 1 1 auto;
  min-height: 0;
  scrollbar-width: thin;
}

.ai-outputs__list--grid {
  grid-template-columns: repeat(2, minmax(0, 1fr));
}

.ai-outputs__list--rows {
  grid-template-columns: 1fr;
}

.ai-outputs__item { display: block; }

.ai-outputs__card {
  display: flex;
  flex-direction: column;
  gap: 8px;
  width: 100%;
  padding: 6px;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-lg);
  background: var(--imago-bg-surface);
  text-align: left;
  cursor: pointer;
  transition: border-color 120ms ease, background 120ms ease, box-shadow 120ms ease;
}

.ai-outputs__card:hover {
  border-color: var(--imago-border-cyan);
  background: var(--imago-cyan-04);
}

.ai-outputs__card--active,
.ai-outputs__card-on {
  border-color: var(--imago-border-cyan-active);
  box-shadow:
    inset 0 0 0 1px var(--imago-border-cyan-active),
    0 0 18px rgba(0, 240, 255, 0.08);
}

.ai-outputs__frame {
  position: relative;
  width: 100%;
  aspect-ratio: 1 / 1;
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-raised);
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
}

.ai-outputs__image {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.ai-outputs__video {
  position: relative;
  width: 100%;
  height: 100%;
}

.ai-outputs__video-badge {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(0, 0, 0, 0.32);
  color: #fff;
}

.ai-outputs__generic {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
  color: var(--imago-text-faint);
}

.ai-outputs__kind {
  position: absolute;
  top: 6px;
  left: 6px;
  padding: 1px 6px;
  border-radius: 4px;
  background: rgba(8, 10, 22, 0.78);
  border: 1px solid var(--imago-border-soft);
  color: var(--imago-text-secondary);
  font-size: 10px;
  font-weight: 600;
  letter-spacing: 0.02em;
}

.ai-outputs__meta {
  display: flex;
  flex-direction: column;
  gap: 2px;
  padding: 0 4px 4px;
  min-width: 0;
}

.ai-outputs__filename {
  font-size: 11.5px;
  font-weight: 500;
  color: var(--imago-text-secondary);
}

.ai-outputs__sub {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 6px;
  font-size: 10.5px;
  color: var(--imago-text-faint);
}

.ai-outputs__time {
  font-variant-numeric: tabular-nums;
}

.ai-outputs__more {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 18px;
  height: 18px;
  padding: 0;
  border: 0;
  background: transparent;
  color: var(--imago-text-faint);
  border-radius: 4px;
  cursor: pointer;
  transition: color 120ms ease, background 120ms ease;
}

.ai-outputs__more:hover {
  color: var(--imago-text-primary);
  background: var(--imago-cyan-06);
}

// ── View all ─────────────────────────────────────────────────────────────────

.ai-outputs__view-all {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  padding: 8px 12px;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-md);
  background: transparent;
  color: var(--imago-neon-cyan);
  font-size: 12px;
  font-weight: 500;
  cursor: pointer;
  align-self: center;
  transition: color 120ms ease, border-color 120ms ease, background 120ms ease;
}

.ai-outputs__view-all:hover {
  color: var(--imago-text-primary);
  border-color: var(--imago-border-cyan-active);
  background: var(--imago-cyan-06);
}

// ── Utility ──────────────────────────────────────────────────────────────────

.ellipsis {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

@media (max-width: 1280px) {
  .ai-outputs { padding: 14px 12px 12px; }
}
</style>
