// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change component structure or accessibility attributes
//
// ChatInputDock
// ─────────────
// Center-column input dock shared by both redesigned workspace pages. Visually
// mirrors the composer area in the approved mockups: a single glass card with
// a leading row of "compose" pills (model picker, skill, element) above the
// textarea and a round cyan send button anchored at the right.
//
// Behaviour-wise it is a thin wrapper around the existing PromptInput. The
// leading-slot pills above the textarea are wired through slots so the page
// can decide which ones to surface for the current context. A status line
// ("Enter 发送, Shift + Enter 换行") is shown beneath the textarea.
//
// The dock is intended to be placed at the bottom of the center chat column,
// NOT as a UILayoutFooter — see the redesigned SessionWorkspacePage and
// ProjectWorkspacePage for the layout wiring.

<template>
  <div class="chat-input-dock" role="region" aria-label="创作输入面板">
    <div class="chat-input-dock__container">
      <!-- Optional context strip (e.g. selected scene / artifact preview) -->
      <div v-if="$slots.context" class="chat-input-dock__context">
        <slot name="context" />
      </div>

      <!-- Compose pill row -->
      <div v-if="$slots.compose || showDefaultCompose" class="chat-input-dock__compose">
        <slot name="compose">
          <button
            type="button"
            class="chat-input-dock__pill chat-input-dock__pill--icon"
            aria-label="添加附件"
            @click="handleAttachClick"
          >
            <OiIcon name="plus" :size="14" />
          </button>
          <button
            type="button"
            class="chat-input-dock__pill chat-input-dock__pill--select"
            aria-haspopup="listbox"
          >
            <span class="chat-input-dock__pill-text">{{ modelLabel }}</span>
            <OiIcon name="chevron-down" :size="12" />
          </button>
          <button
            v-if="showSkillPill"
            type="button"
            class="chat-input-dock__pill chat-input-dock__pill--accent"
          >
            <span class="chat-input-dock__pill-icon">
              <OiIcon name="spark-fill" :size="12" />
            </span>
            <span class="chat-input-dock__pill-text">Skill</span>
          </button>
          <button
            v-if="showElementPill"
            type="button"
            class="chat-input-dock__pill chat-input-dock__pill--accent"
          >
            <span class="chat-input-dock__pill-icon">
              <OiIcon name="cube" :size="12" />
            </span>
            <span class="chat-input-dock__pill-text">元素</span>
          </button>
        </slot>
      </div>

      <!-- PromptInput — the existing composer; visually styled to fit the dock -->
      <div class="chat-input-dock__composer">
        <slot
          name="composer"
          :submit="handleSubmit"
          :draft="draft"
          :on-input="handleInput"
        >
          <PromptInput
            ref="inputRef"
            v-model="draft"
            :placeholder="resolvedPlaceholder"
            :loading="loading"
            :connected="connected"
            :disabled="disabled"
            :attachments="attachments"
            @submit="handleSubmit"
            @abort="emit('abort')"
            @remove-attachment="(id) => emit('remove-attachment', id)"
            @attach-files="(files) => emit('attach-files', files)"
          />
        </slot>
      </div>

      <!-- Status hint line -->
      <div v-if="showHint" class="chat-input-dock__hint">
        {{ hintText }}
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import PromptInput from 'src/components/PromptInput.vue'
import OiIcon from 'src/components/ui/OiIcon.vue'

// ── Props ────────────────────────────────────────────────────────────────────

withDefaults(defineProps<{
  placeholder?: string
  loading?: boolean
  connected?: boolean
  disabled?: boolean
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  attachments?: any[]
  modelLabel?: string
  showSkillPill?: boolean
  showElementPill?: boolean
  showDefaultCompose?: boolean
  showHint?: boolean
  hintText?: string
}>(), {
  placeholder: '输入您的指令或需求…',
  loading: false,
  connected: true,
  disabled: false,
  attachments: () => [],
  modelLabel: 'GPT-4o',
  showSkillPill: true,
  showElementPill: true,
  showDefaultCompose: true,
  showHint: true,
  hintText: 'Enter 发送, Shift + Enter 换行',
})

// ── Emits ────────────────────────────────────────────────────────────────────

const emit = defineEmits<{
  (e: 'submit', value: string): void
  (e: 'abort'): void
  (e: 'attach-files', files: File[]): void
  (e: 'remove-attachment', id: string): void
}>()

// ── Local state (only the dock's own draft) ──────────────────────────────────

const draft = ref('')
const inputRef = ref<InstanceType<typeof PromptInput> | null>(null)

const resolvedPlaceholder = '输入您的指令或需求…'

function handleInput(value: string): void {
  draft.value = value
}

function handleSubmit(value: string): void {
  emit('submit', value)
  draft.value = ''
}

function handleAttachClick(): void {
  // TODO: coder wires the PromptInput file picker openFilePicker
  inputRef.value?.openFilePicker?.()
}
</script>

<style lang="scss" scoped>
// ── Chat input dock ──────────────────────────────────────────────────────────

.chat-input-dock {
  flex-shrink: 0;
  padding: 10px 20px 16px;
  background: linear-gradient(180deg, transparent, var(--imago-bg-void) 70%);
}

.chat-input-dock__container {
  max-width: 760px;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  gap: 6px;
}

// ── Context strip slot ───────────────────────────────────────────────────────

.chat-input-dock__context {
  margin-bottom: 4px;
}

// ── Compose pill row ─────────────────────────────────────────────────────────

.chat-input-dock__compose {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 4px 6px;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-lg);
  background: var(--imago-bg-surface);
}

.chat-input-dock__pill {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 4px 10px;
  height: 26px;
  border: 1px solid transparent;
  border-radius: var(--imago-radius-pill);
  background: transparent;
  color: var(--imago-text-secondary);
  font-size: 12px;
  font-weight: 500;
  cursor: pointer;
  white-space: nowrap;
  transition: color 120ms ease, background 120ms ease, border-color 120ms ease;
}

.chat-input-dock__pill:hover {
  color: var(--imago-text-primary);
  background: var(--imago-cyan-06);
}

.chat-input-dock__pill--icon {
  width: 28px;
  padding: 0;
  justify-content: center;
  color: var(--imago-text-muted);
}

.chat-input-dock__pill--select {
  padding-right: 8px;
}

.chat-input-dock__pill--accent {
  border-color: var(--imago-border-cyan);
  color: var(--imago-neon-cyan);
  background: rgba(0, 240, 255, 0.06);
}

.chat-input-dock__pill--accent:hover {
  background: var(--imago-cyan-08);
  color: var(--imago-text-primary);
}

.chat-input-dock__pill-icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
}

// ── Composer card ────────────────────────────────────────────────────────────

.chat-input-dock__composer {
  width: 100%;
}

.chat-input-dock__hint {
  font-size: 11.5px;
  color: var(--imago-text-faint);
  padding: 0 4px;
  letter-spacing: 0.01em;
}

// ── Responsive ───────────────────────────────────────────────────────────────

@media (max-width: 768px) {
  .chat-input-dock { padding: 8px 12px 12px; }
}
</style>
