// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change component structure or accessibility attributes
//
// ProjectContextStrip
// ───────────────────
// Compact preview strip that appears above the center chat surface in the
// redesigned project workspace, mirroring the "场景01_主镜头.png" strip in
// the approved mockup. It surfaces the currently-selected scene (or output)
// as a small glass card with: thumbnail, title, meta, and a download action.
//
// The page passes the current selection in via props; the strip emits the
// intent to switch context (clear / download) so the page can decide what
// "clear" means in its workflow.

<template>
  <div
    v-if="hasContext"
    class="project-context-strip"
    :aria-label="ariaLabel"
  >
    <div class="project-context-strip__thumb" aria-hidden="true">
      <img
        v-if="thumbnailUrl"
        :src="thumbnailUrl"
        :alt="''"
        class="project-context-strip__image"
        loading="lazy"
      >
      <span v-else class="project-context-strip__thumb-fallback">
        <OiIcon :name="kindIcon as OiIconName" :size="18" />
      </span>
    </div>
    <div class="project-context-strip__body">
      <div class="project-context-strip__title-row">
        <span class="project-context-strip__title ellipsis">{{ title }}</span>
        <span v-if="meta" class="project-context-strip__meta">{{ meta }}</span>
      </div>
      <div v-if="subtitle" class="project-context-strip__subtitle ellipsis">
        {{ subtitle }}
      </div>
    </div>
    <div class="project-context-strip__actions">
      <button
        type="button"
        class="project-context-strip__btn"
        :aria-label="'下载当前素材'"
        @click="emit('download')"
      >
        <OiIcon name="download" :size="14" />
      </button>
      <button
        type="button"
        class="project-context-strip__btn"
        :aria-label="'清除上下文'"
        @click="emit('clear')"
      >
        <q-icon name="close" size="14px" />
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import OiIcon from 'src/components/ui/OiIcon.vue'
import type { OiIconName } from 'src/components/ui/OiIcon.vue'

const props = withDefaults(defineProps<{
  title?: string | null
  subtitle?: string | null
  meta?: string | null
  thumbnailUrl?: string | null
  kind?: 'image' | 'video' | 'audio' | 'scene'
}>(), {
  title: null,
  subtitle: null,
  meta: null,
  thumbnailUrl: null,
  kind: 'image',
})

const emit = defineEmits<{
  (e: 'download'): void
  (e: 'clear'): void
}>()

const hasContext = computed(() => Boolean(props.title))

const ariaLabel = computed(() => {
  if (props.kind === 'scene') return '当前场景上下文'
  return '当前素材上下文'
})

const kindIcon = computed(() => {
  switch (props.kind) {
    case 'video': return 'sparkle'
    case 'audio': return 'cube'
    case 'scene': return 'storyboard'
    default: return 'image-card'
  }
})
</script>

<style lang="scss" scoped>
.project-context-strip {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 8px 12px;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-lg);
  background: var(--imago-bg-surface);
  backdrop-filter: var(--imago-blur-panel);
  -webkit-backdrop-filter: var(--imago-blur-panel);
}

.project-context-strip__thumb {
  position: relative;
  flex-shrink: 0;
  width: 48px;
  height: 48px;
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-raised);
  border: 1px solid var(--imago-border-soft);
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--imago-text-faint);
}

.project-context-strip__image {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.project-context-strip__thumb-fallback {
  display: inline-flex;
  align-items: center;
  justify-content: center;
}

.project-context-strip__body {
  flex: 1 1 auto;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.project-context-strip__title-row {
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 0;
}

.project-context-strip__title {
  font-size: 12.5px;
  font-weight: 600;
  color: var(--imago-text-primary);
  min-width: 0;
  flex: 1 1 auto;
}

.project-context-strip__meta {
  flex-shrink: 0;
  font-size: 10.5px;
  color: var(--imago-text-faint);
  font-variant-numeric: tabular-nums;
}

.project-context-strip__subtitle {
  font-size: 11px;
  line-height: 1.4;
  color: var(--imago-text-muted);
}

.project-context-strip__actions {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  flex-shrink: 0;
}

.project-context-strip__btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 26px;
  height: 26px;
  padding: 0;
  border: 1px solid transparent;
  border-radius: var(--imago-radius-md);
  background: transparent;
  color: var(--imago-text-muted);
  cursor: pointer;
  transition: color 120ms ease, background 120ms ease, border-color 120ms ease;
}

.project-context-strip__btn:hover {
  color: var(--imago-text-primary);
  background: var(--imago-cyan-06);
  border-color: var(--imago-border-cyan);
}

.project-context-strip__btn:focus-visible {
  outline: none;
  box-shadow: 0 0 0 2px var(--imago-cyan-08);
}

.ellipsis {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
</style>
