// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change component structure or accessibility attributes
//
// WorkspaceSegmentedTabs
// ──────────────────────
// Pill-shaped segmented switcher used in the top toolbar of both
// SessionWorkspacePage and ProjectWorkspacePage. Tabs are passed in as a
// static array (id + label) so the same control can be reused wherever
// 4-way navigation appears (故事板/时间线/概览/对话 in the approved mockups).
//
// Styling mirrors the approved mockup: a single rounded surface, a single
// "active" pill highlighted with the cyan accent border + soft cyan fill.
// Inactive tabs are text-only, no borders, no shadow.
//
// Responsive: scrollable horizontally on small viewports so all four labels
// remain reachable. Keyboard: arrow-key navigation is not required by the
// design (Quasar's `q-tabs` would do it; this control uses native buttons
// with `aria-selected` and `tabindex` management instead to stay light).

<template>
  <nav
    class="workspace-tabs"
    role="tablist"
    :aria-label="ariaLabel"
  >
    <button
      v-for="tab in tabs"
      :key="tab.id"
      type="button"
      role="tab"
      :id="`ws-tab-${tab.id}`"
      :aria-selected="activeTab === tab.id"
      :aria-controls="tabPanelId(tab.id)"
      :tabindex="activeTab === tab.id ? 0 : -1"
      class="workspace-tabs__tab"
      :class="{ 'workspace-tabs__tab--active': activeTab === tab.id }"
      @click="handleSelect(tab.id)"
      @keydown.left.prevent="focusPrev"
      @keydown.right.prevent="focusNext"
    >
      <span class="workspace-tabs__label">{{ tab.label }}</span>
    </button>
  </nav>
</template>

<script setup lang="ts">
import { nextTick, ref } from 'vue'

// ── Types ────────────────────────────────────────────────────────────────────

export interface WorkspaceTabDescriptor<TId extends string> {
  id: TId
  label: string
}

const props = defineProps<{
  tabs: ReadonlyArray<WorkspaceTabDescriptor<string>>
  activeTab: string
  /** Stable id used to compose `aria-controls` for each tab panel. */
  panelBaseId?: string
  /** Accessible label for the tablist; defaults to "工作区主标签". */
  ariaLabel?: string
}>()

const emit = defineEmits<{
  (e: 'tab-change', id: string): void
}>()

// ── Local refs ───────────────────────────────────────────────────────────────

const tabRefs = ref<HTMLButtonElement[]>([])

function setTabRef(el: Element | null, index: number) {
  if (el instanceof HTMLButtonElement) tabRefs.value[index] = el
}

defineExpose({ setTabRef })

// ── Helpers ──────────────────────────────────────────────────────────────────

function tabPanelId(id: string): string {
  const base = props.panelBaseId ?? 'workspace'
  return `${base}-tabpanel-${id}`
}

function handleSelect(id: string): void {
  if (id === props.activeTab) return
  emit('tab-change', id)
}

function focusIndex(index: number): void {
  const wrapped = (index + props.tabs.length) % props.tabs.length
  const target = tabRefs.value[wrapped]
  if (target) {
    void nextTick(() => target.focus())
  }
}

function focusPrev(): void {
  const idx = props.tabs.findIndex((t) => t.id === props.activeTab)
  focusIndex(idx - 1)
}

function focusNext(): void {
  const idx = props.tabs.findIndex((t) => t.id === props.activeTab)
  focusIndex(idx + 1)
}
</script>

<style lang="scss" scoped>
// ── Segmented pill switcher ──────────────────────────────────────────────────
//
// Single rounded surface, a single highlighted pill. No button borders other
// than the active ring — matches the dark glass UI of the approved mockup.

.workspace-tabs {
  display: inline-flex;
  align-items: center;
  gap: 2px;
  padding: 4px;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-pill);
  background: var(--imago-bg-surface);
  flex: 0 1 auto;
  min-width: 0;
  max-width: 540px;
  overflow-x: auto;
  scrollbar-width: none;
  -webkit-overflow-scrolling: touch;
}

.workspace-tabs::-webkit-scrollbar { display: none; }

.workspace-tabs__tab {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  padding: 6px 18px;
  min-height: 30px;
  border: 0;
  border-radius: var(--imago-radius-pill);
  background: transparent;
  color: var(--imago-text-muted);
  font-size: 13px;
  font-weight: 500;
  white-space: nowrap;
  cursor: pointer;
  transition: color 120ms ease, background 120ms ease, box-shadow 120ms ease;
}

.workspace-tabs__tab:hover {
  color: var(--imago-text-primary);
}

.workspace-tabs__tab:focus-visible {
  outline: none;
  box-shadow: 0 0 0 2px var(--imago-cyan-08);
}

.workspace-tabs__tab--active {
  color: var(--imago-text-primary);
  background: var(--imago-cyan-08);
  box-shadow:
    inset 0 0 0 1px var(--imago-border-cyan-active),
    0 0 18px rgba(0, 240, 255, 0.12);
}

.workspace-tabs__label {
  letter-spacing: 0.01em;
}

// ── Responsive ───────────────────────────────────────────────────────────────

@media (max-width: 720px) {
  .workspace-tabs__tab { padding: 6px 12px; font-size: 12.5px; }
}
</style>
