<!--
  DESIGN SPEC — generated by Designer agent
  Coder: implement TODO items, do not change component structure or accessibility attributes
-->
<template>
  <PageShell>
    <PageHeader
      title="技能"
      subtitle="你的 AI 技能库，会在进入项目时自动生效"
      v-model:search="searchQuery"
      search-placeholder="按名称或描述搜索技能..."
      create-label="新建技能"
      @create="openCreate"
    />

    <PageLoading v-if="loading" message="正在加载技能..." />

    <PageEmpty
      v-else-if="skills.length === 0"
      icon="auto_awesome"
      title="还没有技能"
      description="创建你的第一个技能，进入项目时它会自动加载"
      action-label="新建技能"
      @action="openCreate"
    />

    <PageEmpty
      v-else-if="filteredSkills.length === 0"
      icon="search_off"
      title="没有匹配的技能"
      description="换个关键词试试，或调整搜索条件"
    />

    <ul v-else class="skills-grid" role="list">
      <li v-for="skill in filteredSkills" :key="skill.id" class="skills-grid__item">
        <article class="skill-card" :aria-labelledby="`skill-name-${skill.id}`">
          <!-- Card head: the skill IS a command/file, so we surface its slug as an
               invokable token rather than a decorative thumbnail. -->
          <header class="skill-card__head">
            <span class="skill-card__slug">
              <OiIcon name="command-slash" size="14px" class="skill-card__slug-icon" />
              <code>/{{ skill.name }}</code>
            </span>
            <q-space />
            <span
              class="skill-card__status"
              :class="`skill-card__status--${skill.status}`"
            >
              {{ statusLabel(skill.status) }}
            </span>
          </header>

          <h2 :id="`skill-name-${skill.id}`" class="skill-card__name">
            {{ skill.name }}
          </h2>
          <p class="skill-card__desc">{{ skill.description || '暂无描述' }}</p>

          <pre class="skill-card__snippet"><code>{{ contentSnippet(skill.content) }}</code></pre>

          <footer class="skill-card__footer">
            <span class="skill-card__meta">
              <OiIcon name="clock-outline" size="13px" class="skill-card__meta-icon" />
              <span>{{ formatUpdatedAt(skill.updatedAt) }}</span>
            </span>
            <q-space />
            <q-btn
              flat
              dense
              no-caps
              class="skill-card__action"
              :aria-label="`编辑技能 ${skill.name}`"
              @click="openEdit(skill)"
            >
              <OiIcon name="document" size="15px" class="skill-card__action-icon" />
              <span>编辑</span>
            </q-btn>
            <q-btn
              flat
              dense
              round
              class="skill-card__delete"
              :aria-label="`删除技能 ${skill.name}`"
              @click="openDelete(skill)"
            >
              <OiIcon name="trash" size="16px" />
            </q-btn>
          </footer>
        </article>
      </li>
    </ul>

    <!-- ── Create / Edit dialog (mode-driven, single form) ───────────────── -->
    <q-dialog v-model="showEditor" @hide="resetForm">
      <q-card class="skill-dialog" role="dialog" aria-labelledby="skill-dialog-title">
        <q-card-section>
          <h2 id="skill-dialog-title" class="skill-dialog__title">
            {{ editorMode === 'create' ? '新建技能' : '编辑技能' }}
          </h2>
          <p class="skill-dialog__hint">
            技能以 SKILL.md 的形式保存，名称即调用它的命令。
          </p>
        </q-card-section>

        <q-card-section class="skill-dialog__body">
          <!-- Slug -->
          <div class="skill-field">
            <label for="skill-name-input" class="skill-field__label">
              名称（命令标识）
            </label>
            <q-input
              id="skill-name-input"
              v-model="form.name"
              outlined
              dark
              dense
              maxlength="64"
              placeholder="例如：code-review"
              prefix="/"
              :error="!!nameError"
              :error-message="nameError"
              :aria-describedby="'skill-name-help'"
              @blur="touched.name = true"
            />
            <p id="skill-name-help" class="skill-field__help">
              小写字母、数字、连字符，1–64 个字符。
              <span class="skill-field__count">{{ form.name.length }}/64</span>
            </p>
          </div>

          <!-- Description -->
          <div class="skill-field">
            <label for="skill-desc-input" class="skill-field__label">描述</label>
            <q-input
              id="skill-desc-input"
              v-model="form.description"
              outlined
              dark
              dense
              type="textarea"
              rows="2"
              maxlength="1024"
              placeholder="一句话说明这个技能做什么、何时使用"
              :error="!!descriptionError"
              :error-message="descriptionError"
              @blur="touched.description = true"
            />
            <p class="skill-field__help">
              <q-space />
              <span class="skill-field__count">{{ form.description.length }}/1024</span>
            </p>
          </div>

          <!-- Content -->
          <div class="skill-field">
            <label for="skill-content-input" class="skill-field__label">
              内容（SKILL.md 正文）
            </label>
            <q-input
              id="skill-content-input"
              v-model="form.content"
              outlined
              dark
              dense
              type="textarea"
              rows="9"
              class="skill-field__content"
              placeholder="# 标题&#10;&#10;在这里编写技能指令..."
              :error="!!contentError"
              :error-message="contentError"
              @blur="touched.content = true"
            />
          </div>
        </q-card-section>

        <q-card-actions align="right" class="skill-dialog__actions">
          <q-btn flat no-caps label="取消" v-close-popup />
          <q-btn
            unelevated
            no-caps
            class="skill-dialog__submit"
            :disable="!isFormValid"
            :loading="saving"
            @click="handleSubmit"
          >
            <OiIcon
              :name="editorMode === 'create' ? 'plus' : 'check'"
              size="16px"
              class="skill-dialog__submit-icon"
            />
            <span>{{ editorMode === 'create' ? '创建' : '保存' }}</span>
          </q-btn>
        </q-card-actions>
      </q-card>
    </q-dialog>

    <!-- ── Delete confirmation ───────────────────────────────────────────── -->
    <q-dialog v-model="showDelete">
      <q-card class="skill-dialog skill-dialog--confirm" role="alertdialog" aria-labelledby="skill-delete-title">
        <q-card-section>
          <h2 id="skill-delete-title" class="skill-dialog__title">删除技能</h2>
          <p class="skill-dialog__hint">
            确定要删除
            <strong class="skill-dialog__emphasis">{{ pendingDelete?.name }}</strong>
            吗？此操作无法撤销。
          </p>
        </q-card-section>
        <q-card-actions align="right" class="skill-dialog__actions">
          <q-btn flat no-caps label="取消" v-close-popup />
          <q-btn
            unelevated
            no-caps
            label="删除"
            class="skill-dialog__danger"
            :loading="deleting"
            @click="handleDelete"
          />
        </q-card-actions>
      </q-card>
    </q-dialog>
  </PageShell>
</template>

<script setup lang="ts">
import { computed, reactive, ref, onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import OiIcon from 'src/components/ui/OiIcon.vue'
import PageShell from 'src/components/page/PageShell.vue'
import PageHeader from 'src/components/page/PageHeader.vue'
import PageEmpty from 'src/components/page/PageEmpty.vue'
import PageLoading from 'src/components/page/PageLoading.vue'
import { useSkillsStore } from 'src/stores/skills'
import type { Skill } from 'src/api/client'

type EditorMode = 'create' | 'edit'

// ── Validation rules (mirror backend limits) ───────────────────────────
const NAME_PATTERN = /^[a-z0-9-]+$/
const NAME_MAX = 64
const DESC_MAX = 1024

// ── Store-backed data ──────────────────────────────────────────────────
const store = useSkillsStore()
const { skills, loading } = storeToRefs(store)

onMounted(() => store.fetchAll())

const searchQuery = ref('')

const filteredSkills = computed<Skill[]>(() => {
  const q = searchQuery.value.trim().toLowerCase()
  if (!q) return skills.value
  return skills.value.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.description.toLowerCase().includes(q),
  )
})

// ── Editor (create + edit share one dialog) ────────────────────────────
const showEditor = ref(false)
const editorMode = ref<EditorMode>('create')
// Skills are keyed by name (backend unique (userId, name)) — track the name
// of the skill being edited so update() can address it.
const editingName = ref<string | null>(null)
const saving = ref(false)

const form = reactive({ name: '', description: '', content: '' })
const touched = reactive({ name: false, description: false, content: false })

const nameError = computed<string>(() => {
  if (!touched.name) return ''
  const v = form.name.trim()
  if (!v) return '请输入名称'
  if (v.length > NAME_MAX) return `名称不能超过 ${NAME_MAX} 个字符`
  if (!NAME_PATTERN.test(v)) return '只能使用小写字母、数字和连字符'
  return ''
})

const descriptionError = computed<string>(() => {
  if (!touched.description) return ''
  if (form.description.length > DESC_MAX) return `描述不能超过 ${DESC_MAX} 个字符`
  return ''
})

const contentError = computed<string>(() => {
  if (!touched.content) return ''
  if (!form.content.trim()) return '请输入技能内容'
  return ''
})

const isFormValid = computed<boolean>(() => {
  const name = form.name.trim()
  return (
    !!name &&
    name.length <= NAME_MAX &&
    NAME_PATTERN.test(name) &&
    form.description.length <= DESC_MAX &&
    !!form.content.trim()
  )
})

function resetForm(): void {
  form.name = ''
  form.description = ''
  form.content = ''
  touched.name = false
  touched.description = false
  touched.content = false
  editingName.value = null
}

function openCreate(): void {
  resetForm()
  editorMode.value = 'create'
  showEditor.value = true
}

function openEdit(skill: Skill): void {
  editorMode.value = 'edit'
  editingName.value = skill.name
  form.name = skill.name
  form.description = skill.description
  form.content = skill.content
  touched.name = false
  touched.description = false
  touched.content = false
  showEditor.value = true
}

async function handleSubmit(): Promise<void> {
  touched.name = true
  touched.description = true
  touched.content = true
  if (!isFormValid.value) return
  saving.value = true
  try {
    const name = form.name.trim()
    const description = form.description.trim()
    const content = form.content
    if (editorMode.value === 'create') {
      await store.create({ name, description, content })
    } else if (editingName.value) {
      await store.update(editingName.value, { description, content })
    }
    showEditor.value = false
  } finally {
    saving.value = false
  }
}

// ── Delete ─────────────────────────────────────────────────────────────
const showDelete = ref(false)
const deleting = ref(false)
const pendingDelete = ref<Skill | null>(null)

function openDelete(skill: Skill): void {
  pendingDelete.value = skill
  showDelete.value = true
}

async function handleDelete(): Promise<void> {
  if (!pendingDelete.value) return
  deleting.value = true
  try {
    await store.remove(pendingDelete.value.name)
    showDelete.value = false
    pendingDelete.value = null
  } finally {
    deleting.value = false
  }
}

// ── Presentation helpers ───────────────────────────────────────────────
function statusLabel(status: Skill['status']): string {
  return status === 'active' ? '已启用' : '草稿'
}

function contentSnippet(content: string): string {
  const oneLine = content.replace(/\s+/g, ' ').trim()
  if (!oneLine) return '空内容'
  return oneLine.length > 150 ? `${oneLine.slice(0, 150)}…` : oneLine
}

function formatUpdatedAt(iso: string): string {
  // TODO: replace with project date-format util once available.
  const d = new Date(iso)
  return Number.isNaN(d.getTime()) ? '—' : d.toLocaleDateString()
}
</script>

<style lang="scss" scoped>
// ── Grid (mirrors PromptsPage breakpoints) ─────────────────────────────
.skills-grid {
  position: relative;
  z-index: 1;
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 18px 24px;
  margin: 0;
  padding: 0;
  list-style: none;
}

.skills-grid__item {
  min-width: 0;
}

// ── Card ───────────────────────────────────────────────────────────────
.skill-card {
  display: flex;
  flex-direction: column;
  min-height: 230px;
  height: 100%;
  padding: 18px;
  border-radius: 16px;
  background: linear-gradient(180deg, rgb(16 21 35 / 96%), rgb(10 14 24 / 96%));
  border: 1px solid var(--imago-border-dim);
  box-shadow: 0 14px 36px rgb(0 0 0 / 28%);
  transition: border-color var(--imago-ease-fast), box-shadow var(--imago-ease-fast);
}

.skill-card:hover {
  border-color: var(--imago-border-cyan);
  box-shadow: 0 14px 40px rgb(0 0 0 / 36%), 0 0 24px rgb(0 240 255 / 8%);
}

.skill-card__head {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-bottom: 12px;
}

.skill-card__slug {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  height: 26px;
  padding: 0 10px;
  border-radius: 8px;
  background: var(--imago-bg-code);
  border: 1px solid var(--imago-border-dim);
  color: var(--imago-neon-cyan);
  font: 12px/1 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
}

.skill-card__slug-icon {
  color: var(--imago-neon-cyan);
}

.skill-card__status {
  flex-shrink: 0;
  height: 22px;
  padding: 0 10px;
  display: inline-flex;
  align-items: center;
  border-radius: 999px;
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.02em;
}

.skill-card__status--active {
  color: #5af0c8;
  background: rgb(40 220 170 / 12%);
  border: 1px solid rgb(40 220 170 / 36%);
}

.skill-card__status--draft {
  color: var(--imago-text-muted);
  background: rgb(255 255 255 / 5%);
  border: 1px solid var(--imago-border-dim);
}

.skill-card__name {
  margin: 0;
  color: var(--imago-text-primary);
  font-size: 20px;
  font-weight: 700;
  line-height: 1.25;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.skill-card__desc {
  margin: 6px 0 12px;
  color: var(--imago-text-muted);
  font-size: 14px;
  line-height: 1.45;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.skill-card__snippet {
  flex: 1;
  min-height: 76px;
  margin: 0;
  padding: 12px 14px;
  border-radius: 8px;
  color: var(--imago-text-secondary);
  background: var(--imago-bg-code);
  border: 1px solid var(--imago-border-dim);
  white-space: pre-wrap;
  overflow: hidden;
  font: 12px/1.46 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
}

.skill-card__footer {
  display: flex;
  align-items: center;
  gap: 6px;
  margin-top: 12px;
  color: var(--imago-text-muted);
  font-size: 13px;
}

.skill-card__meta {
  display: inline-flex;
  align-items: center;
  gap: 6px;
}

.skill-card__meta-icon {
  color: var(--imago-text-muted);
}

.skill-card__action {
  height: 32px;
  border-radius: 8px;
  color: var(--imago-text-secondary);

  :deep(.q-btn__content) {
    gap: 6px;
  }
}

.skill-card__action-icon {
  color: currentColor;
}

.skill-card__delete {
  width: 28px;
  height: 28px;
  color: var(--imago-text-dim);
  transition: color var(--imago-ease-fast);
}

.skill-card__delete:hover {
  color: var(--imago-neon-pink, #ff2d95);
}

// ── Dialog ─────────────────────────────────────────────────────────────
.skill-dialog {
  width: 560px;
  max-width: 92vw;
  color: var(--imago-text-primary);
  background: var(--imago-bg-panel);
  border: 1px solid var(--imago-border-dim);
  border-radius: 14px;
}

.skill-dialog--confirm {
  width: 420px;
}

.skill-dialog__title {
  margin: 0;
  font-size: 18px;
  font-weight: 700;
}

.skill-dialog__hint {
  margin: 6px 0 0;
  color: var(--imago-text-muted);
  font-size: 13px;
  line-height: 1.5;
}

.skill-dialog__emphasis {
  color: var(--imago-text-primary);
  font-weight: 700;
}

.skill-dialog__body {
  display: flex;
  flex-direction: column;
  gap: 18px;
}

.skill-field {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.skill-field__label {
  font-size: 13px;
  font-weight: 600;
  color: var(--imago-text-secondary);
}

.skill-field__help {
  display: flex;
  align-items: center;
  gap: 8px;
  margin: 0;
  font-size: 12px;
  line-height: 1.4;
  color: var(--imago-text-muted);
}

.skill-field__count {
  margin-left: auto;
  font-variant-numeric: tabular-nums;
  color: var(--imago-text-dim);
}

.skill-field__content :deep(textarea) {
  font: 13px/1.5 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
}

.skill-dialog__actions {
  padding: 8px 16px 16px;
}

.skill-dialog__submit {
  height: 38px;
  padding: 0 18px;
  border-radius: 10px;
  font-weight: 600;
  color: #030713;
  background: linear-gradient(90deg, #00f0ff 0%, #5cc6ff 100%);
  box-shadow: 0 0 18px rgb(0 240 255 / 30%);

  :deep(.q-btn__content) {
    gap: 6px;
  }
}

.skill-dialog__submit:disabled {
  filter: grayscale(0.6);
  opacity: 0.5;
}

.skill-dialog__submit-icon {
  color: #030713;
}

.skill-dialog__danger {
  height: 38px;
  padding: 0 18px;
  border-radius: 10px;
  font-weight: 600;
  color: #fff;
  background: linear-gradient(90deg, #ff2d95 0%, #ff5b6b 100%);
  box-shadow: 0 0 18px rgb(255 45 149 / 28%);
}

// ── Responsive (mirror PromptsPage) ────────────────────────────────────
@media (max-width: 1240px) {
  .skills-grid { grid-template-columns: 1fr; }
}

@media (max-width: 780px) {
  .skill-dialog { width: 100%; }
  .skill-card__footer { flex-wrap: wrap; }
}

@media (prefers-reduced-motion: reduce) {
  .skill-card { transition: none; }
}
</style>
