// DESIGN SPEC — generated by Designer agent
// Coder: wire behavior without changing component structure or accessibility attributes
//
// UnverifiedEmailDialog
// ---------------------
// Compact Quasar/Vue dialog shown after a returning user logs in with valid
// email/password but their account's email has not yet been verified.
//
// State machine (driven by parent via `phase` prop, plus internal `phase`
// transitions triggered by emit results):
//
//   notice   → sending  → input  → verifying → success  → (emit 'verified' → close)
//                            │            │
//                            └── resend ──┘  (re-send another NEW code)
//
// This component is the dialog host AND the visual state machine. It does
// NOT call any backend — it only emits semantic events. The parent
// (e.g. App.vue) is responsible for wiring `api.sendEmailVerification`,
// `api.verifyEmail`, sign-out, route transitions, etc.
//
// Visual contract (matches existing AuthPanel/AuthDialog tokens):
// - 400px wide, dark glass card with thin cyan/violet neon border
// - Header + close X (de-emphasized; this is a required security step)
// - Single small icon block per phase (shield+mail / envelope+check / spinner / check)
// - 6 separated square OTP inputs with cyan glow on focus
// - Primary submit: cyan/violet gradient (reuses `.imago-submit--cyan`)
// - Secondary action: ghost text button
// - No new design system; all values come from --imago-* tokens

<template>
  <q-dialog
    :model-value="modelValue"
    :persistent="persistent"
    transition-show="jump-up"
    transition-hide="jump-down"
    class="unverified-email-dialog-host"
    @update:model-value="onDialogModelUpdate"
  >
    <div
      class="unverified-email-dialog"
      role="dialog"
      aria-modal="true"
      :aria-labelledby="headerId"
      :aria-describedby="bodyId"
    >
      <!-- Header: title + (de-emphasized) close button -->
      <header class="unverified-email-dialog__header">
        <div class="unverified-email-dialog__title-row">
          <h2 :id="headerId" class="unverified-email-dialog__title">
            {{ headerTitle }}
          </h2>
          <span
            v-if="isInputPhase"
            class="unverified-email-dialog__required-badge"
            aria-label="必需步骤"
          >
            必需
          </span>
        </div>
        <button
          v-if="showCloseButton"
          type="button"
          class="unverified-email-dialog__close"
          :aria-label="closeAriaLabel"
          :disabled="!dismissible"
          @click="onCloseClick"
        >
          <q-icon name="close" />
        </button>
      </header>

      <!-- Icon block (one per phase) -->
      <div class="unverified-email-dialog__icon" aria-hidden="true">
        <template v-if="phase === 'notice'">
          <q-icon name="shield" class="unverified-email-dialog__icon-glyph" />
          <q-icon name="mail_outline" class="unverified-email-dialog__icon-bubble" />
        </template>
        <template v-else-if="phase === 'sending'">
          <q-spinner
            color="cyan-4"
            size="34px"
            class="unverified-email-dialog__spinner"
          />
        </template>
        <template v-else-if="phase === 'input'">
          <q-icon name="mail_outline" class="unverified-email-dialog__icon-glyph" />
          <q-icon name="check_circle" class="unverified-email-dialog__icon-bubble" />
        </template>
        <template v-else-if="phase === 'verifying'">
          <q-spinner
            color="cyan-4"
            size="34px"
            class="unverified-email-dialog__spinner"
          />
        </template>
        <template v-else-if="phase === 'success'">
          <q-icon name="check_circle" class="unverified-email-dialog__icon-glyph unverified-email-dialog__icon-glyph--success" />
        </template>
      </div>

      <!-- Body: phase-specific copy + controls -->
      <div :id="bodyId" class="unverified-email-dialog__body">
        <!-- ── Phase: notice (initial required state) ─────────────── -->
        <template v-if="phase === 'notice'">
          <p class="unverified-email-dialog__lede">
            你的账号已创建，但邮箱尚未验证
          </p>
          <p class="unverified-email-dialog__copy">
            为了保护账号安全，需要重新发送验证码并完成邮箱验证后才能继续使用 OpenImago。
          </p>

          <div class="unverified-email-dialog__info-row">
            <div class="unverified-email-dialog__info-meta">
              <span class="unverified-email-dialog__info-label">账号邮箱</span>
              <span class="unverified-email-dialog__info-value">{{ email }}</span>
            </div>
            <span
              class="unverified-email-dialog__badge unverified-email-dialog__badge--unverified"
              role="status"
            >
              未验证
            </span>
          </div>

          <p class="unverified-email-dialog__note">
            之前的验证码可能已过期。点击发送验证码后，我们会向该邮箱发送新的 6 位验证码。
          </p>
        </template>

        <!-- ── Phase: sending (request in flight) ─────────────────── -->
        <template v-else-if="phase === 'sending'">
          <p class="unverified-email-dialog__lede">正在发送新的验证码...</p>
          <p class="unverified-email-dialog__copy">
            我们正在为这个未验证账号生成新的验证码。
          </p>

          <div class="unverified-email-dialog__info-row">
            <div class="unverified-email-dialog__info-meta">
              <span class="unverified-email-dialog__info-label">账号邮箱</span>
              <span class="unverified-email-dialog__info-value">{{ email }}</span>
            </div>
            <span
              class="unverified-email-dialog__badge unverified-email-dialog__badge--unverified"
              role="status"
            >
              未验证
            </span>
          </div>

          <ul class="unverified-email-dialog__status-list" aria-live="polite">
            <li class="unverified-email-dialog__status-item is-done">
              <q-icon name="check" class="unverified-email-dialog__status-icon" aria-hidden="true" />
              <span>确认账号未验证</span>
            </li>
            <li
              class="unverified-email-dialog__status-item"
              :class="{ 'is-active': true, 'is-done': false }"
            >
              <q-spinner color="cyan-4" size="16px" class="unverified-email-dialog__status-icon" />
              <span>生成新的 6 位验证码</span>
            </li>
            <li class="unverified-email-dialog__status-item is-pending">
              <span class="unverified-email-dialog__status-dot" aria-hidden="true" />
              <span>发送验证邮件</span>
            </li>
          </ul>
        </template>

        <!-- ── Phase: input (OTP entry + resend) ──────────────────── -->
        <template v-else-if="phase === 'input'">
          <p class="unverified-email-dialog__lede">请输入新的验证码</p>
          <p class="unverified-email-dialog__copy">
            我们已向该邮箱重新发送 6 位验证码，请查收。
          </p>

          <div class="unverified-email-dialog__email-pill">
            <q-icon name="mail_outline" class="unverified-email-dialog__email-pill-icon" aria-hidden="true" />
            <span class="unverified-email-dialog__email-pill-value">{{ email }}</span>
            <span
              class="unverified-email-dialog__badge unverified-email-dialog__badge--pending"
              role="status"
            >
              待验证
            </span>
            <button
              v-if="allowChangeEmail"
              type="button"
              class="unverified-email-dialog__email-pill-action"
              @click="onChangeEmailClick"
            >
              更换
            </button>
          </div>

          <!-- 6 separate OTP inputs (composition: no existing OTP component in repo) -->
          <div
            class="unverified-email-dialog__otp"
            role="group"
            aria-label="6 位验证码输入"
            @paste="onOtpPaste"
          >
            <input
              v-for="(digit, index) in otpDigits"
              :key="index"
              :ref="(el) => setOtpRef(el, index)"
              v-model="otpDigits[index]"
              type="text"
              inputmode="numeric"
              pattern="[0-9]*"
              maxlength="1"
              class="unverified-email-dialog__otp-cell"
              :class="{
                'is-focused': otpFocusedIndex === index,
                'is-filled': !!digit,
                'is-error': !!errorMessage,
              }"
              :aria-label="`验证码第 ${index + 1} 位`"
              :aria-invalid="!!errorMessage"
              autocomplete="one-time-code"
              @input="onOtpDigitInput(index, $event)"
              @keydown="onOtpKeydown(index, $event)"
              @focus="otpFocusedIndex = index"
              @blur="otpFocusedIndex = -1"
            />
          </div>

          <p class="unverified-email-dialog__helper">新验证码 10 分钟内有效</p>

          <p
            v-if="errorMessage"
            class="unverified-email-dialog__inline-error"
            role="alert"
          >
            {{ errorMessage }}
          </p>

          <div class="unverified-email-dialog__resend-row">
            <span class="unverified-email-dialog__resend-hint">
              <q-icon name="info" size="14px" class="unverified-email-dialog__resend-hint-icon" aria-hidden="true" />
              未收到邮件？请检查垃圾邮件
            </span>
            <button
              v-if="resendCooldownRemaining > 0"
              type="button"
              class="unverified-email-dialog__resend-action is-disabled"
              disabled
              aria-live="polite"
            >
              {{ resendCooldownRemaining }}s 后可重新发送
            </button>
            <button
              v-else
              type="button"
              class="unverified-email-dialog__resend-action"
              @click="onResendClick"
            >
              重新发送验证码
            </button>
          </div>
        </template>

        <!-- ── Phase: verifying (in-flight verification call) ─────── -->
        <template v-else-if="phase === 'verifying'">
          <p class="unverified-email-dialog__lede">正在验证...</p>
          <p class="unverified-email-dialog__copy">
            正在检查该邮箱的验证码
          </p>

          <ul class="unverified-email-dialog__status-list" aria-live="polite">
            <li class="unverified-email-dialog__status-item is-done">
              <q-icon name="check" class="unverified-email-dialog__status-icon" aria-hidden="true" />
              <span>邮箱格式有效</span>
            </li>
            <li class="unverified-email-dialog__status-item is-done">
              <q-icon name="check" class="unverified-email-dialog__status-icon" aria-hidden="true" />
              <span>验证码已提交</span>
            </li>
            <li class="unverified-email-dialog__status-item is-active">
              <q-spinner color="cyan-4" size="16px" class="unverified-email-dialog__status-icon" />
              <span>与服务器核对</span>
            </li>
          </ul>
        </template>

        <!-- ── Phase: success (verified) ──────────────────────────── -->
        <template v-else-if="phase === 'success'">
          <p class="unverified-email-dialog__lede">邮箱已验证</p>
          <p class="unverified-email-dialog__copy">
            {{ email }} 已完成验证，现在可以继续使用 OpenImago。
          </p>

          <ul class="unverified-email-dialog__checklist" aria-label="验证完成清单">
            <li class="unverified-email-dialog__checklist-item">
              <q-icon name="check_circle" class="unverified-email-dialog__checklist-icon" aria-hidden="true" />
              <span>账号邮箱已确认</span>
            </li>
            <li class="unverified-email-dialog__checklist-item">
              <q-icon name="check_circle" class="unverified-email-dialog__checklist-icon" aria-hidden="true" />
              <span>登录状态已恢复</span>
            </li>
            <li class="unverified-email-dialog__checklist-item">
              <q-icon name="check_circle" class="unverified-email-dialog__checklist-icon" aria-hidden="true" />
              <span>即将进入工作区</span>
            </li>
          </ul>
        </template>
      </div>

      <!-- Footer: phase-specific actions -->
      <footer class="unverified-email-dialog__footer">
        <!-- notice: send-code + sign-out -->
        <template v-if="phase === 'notice'">
          <q-btn
            type="button"
            label="发送验证码"
            class="imago-submit imago-submit--cyan unverified-email-dialog__submit"
            :loading="false"
            :disable="false"
            unelevated
            no-caps
            @click="onSendCodeClick"
          />
          <button
            type="button"
            class="unverified-email-dialog__ghost-action"
            @click="onSignOutClick"
          >
            退出登录
          </button>
        </template>

        <!-- sending: disabled submit + sign-out -->
        <template v-else-if="phase === 'sending'">
          <q-btn
            type="button"
            label="发送中..."
            class="imago-submit imago-submit--cyan unverified-email-dialog__submit"
            :loading="true"
            :disable="true"
            unelevated
            no-caps
          />
          <button
            type="button"
            class="unverified-email-dialog__ghost-action"
            @click="onSignOutClick"
          >
            退出登录
          </button>
        </template>

        <!-- input: verify + sign-out -->
        <template v-else-if="phase === 'input'">
          <q-btn
            type="button"
            label="验证并进入"
            class="imago-submit imago-submit--cyan unverified-email-dialog__submit"
            :loading="false"
            :disable="!isOtpComplete"
            unelevated
            no-caps
            @click="onVerifyClick"
          />
          <button
            type="button"
            class="unverified-email-dialog__ghost-action"
            @click="onSignOutClick"
          >
            退出登录
          </button>
        </template>

        <!-- verifying: disabled submit -->
        <template v-else-if="phase === 'verifying'">
          <q-btn
            type="button"
            label="验证中..."
            class="imago-submit imago-submit--cyan unverified-email-dialog__submit"
            :loading="true"
            :disable="true"
            unelevated
            no-caps
          />
        </template>

        <!-- success: enter app -->
        <template v-else-if="phase === 'success'">
          <q-btn
            type="button"
            label="进入 OpenImago"
            class="imago-submit imago-submit--cyan unverified-email-dialog__submit"
            :loading="false"
            :disable="false"
            unelevated
            no-caps
            @click="onEnterAppClick"
          />
        </template>
      </footer>
    </div>
  </q-dialog>
</template>

<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, watch } from 'vue'

/**
 * Phase of the unverified-account verification flow.
 * - 'notice'    : account is unverified, no code has been requested yet.
 * - 'sending'   : a new code is being sent.
 * - 'input'     : code has been sent; user must enter 6 digits.
 * - 'verifying' : code has been submitted; awaiting server response.
 * - 'success'   : verification succeeded; ready to enter app.
 */
export type UnverifiedPhase = 'notice' | 'sending' | 'input' | 'verifying' | 'success'

/** Payload emitted when the user finishes entering the 6-digit code. */
export interface VerifyEmailPayload {
  email: string
  code: string
}

interface Props {
  /** v-model:open — whether the dialog is visible. */
  modelValue: boolean
  /** Current phase of the flow. Parent controls this in response to emits. */
  phase: UnverifiedPhase
  /** Email of the unverified account (already known from login). */
  email: string
  /** Whether the dialog can be dismissed (close X + outside click + escape). */
  dismissible?: boolean
  /** Cooldown in seconds before resend is allowed. 0 means resend is enabled. */
  resendCooldownSeconds?: number
  /** Whether to show the "更换" link next to the email pill (input phase only). */
  allowChangeEmail?: boolean
  /** Inline error message rendered under OTP cells (input phase). */
  errorMessage?: string
}

interface Emits {
  (e: 'update:modelValue', open: boolean): void
  (e: 'update:phase', phase: UnverifiedPhase): void
  /** Fired when the user clicks "发送验证码" in the notice phase. */
  (e: 'send-code', email: string): void
  /** Fired when the user clicks "重新发送验证码" after cooldown. */
  (e: 'resend-code', email: string): void
  /** Fired when the user finishes entering a 6-digit code and clicks verify. */
  (e: 'verify', payload: VerifyEmailPayload): void
  /** Fired when the user clicks "退出登录" at any phase that shows it. */
  (e: 'sign-out'): void
  /** Fired when the user clicks "更换" (change email) — only input phase. */
  (e: 'change-email'): void
  /** Fired when the user clicks "进入 OpenImago" on the success phase. */
  (e: 'enter-app'): void
}

const props = withDefaults(defineProps<Props>(), {
  dismissible: false,
  resendCooldownSeconds: 0,
  allowChangeEmail: false,
  errorMessage: '',
})

const emit = defineEmits<Emits>()

// ── Header text per phase ───────────────────────────────────────────
const headerTitle = computed<string>(() => {
  switch (props.phase) {
    case 'notice':    return '需要验证邮箱'
    case 'sending':   return '发送验证码'
    case 'input':     return '验证账号邮箱'
    case 'verifying': return '验证邮箱'
    case 'success':   return '邮箱验证完成'
    default:          return '需要验证邮箱'
  }
})

const closeAriaLabel = computed<string>(() => {
  if (!props.dismissible) return '关闭（必需步骤）'
  return '关闭对话框'
})

const showCloseButton = computed<boolean>(() => props.phase !== 'sending' && props.phase !== 'verifying')

// Accessibility IDs (stable per component instance)
const headerId = 'unverified-email-dialog-header'
const bodyId = 'unverified-email-dialog-body'

// ── OTP state (input phase) ─────────────────────────────────────────
const OTP_LENGTH = 6
const otpDigits = ref<string[]>(Array.from({ length: OTP_LENGTH }, () => ''))
const otpRefs = ref<Array<HTMLInputElement | null>>([])
const otpFocusedIndex = ref<number>(-1)
let cooldownTimer: ReturnType<typeof setInterval> | null = null
const resendCooldownRemaining = ref<number>(props.resendCooldownSeconds)

const isOtpComplete = computed<boolean>(() =>
  otpDigits.value.every((d) => d !== '' && /^\d$/.test(d)),
)

const isInputPhase = computed<boolean>(() => props.phase === 'input')

// ── Persistent in this flow: do not allow outside dismiss during security checkpoint
const persistent = computed<boolean>(() => !props.dismissible)

// ── Lifecycle: reset OTP + cooldown when entering input phase ───────
watch(
  () => props.phase,
  (next, prev) => {
    if (next === 'input' && prev !== 'input') {
      otpDigits.value = Array.from({ length: OTP_LENGTH }, () => '')
      otpFocusedIndex.value = -1
      // Focus the first cell on next tick so the dialog is mounted
      void nextTick(() => focusOtpCell(0))
    }
    if (next === 'input' && prev === 'notice') {
      // Phase transitioned to input because a code was just sent; start cooldown
      startCooldown(props.resendCooldownSeconds)
    }
  },
  { immediate: true },
)

// ── Cooldown timer (resend) ─────────────────────────────────────────
function startCooldown(durationSec: number) {
  resendCooldownRemaining.value = Math.max(0, Math.floor(durationSec))
  if (cooldownTimer) clearInterval(cooldownTimer)
  if (resendCooldownRemaining.value <= 0) return
  cooldownTimer = setInterval(() => {
    resendCooldownRemaining.value--
    if (resendCooldownRemaining.value <= 0) {
      if (cooldownTimer) clearInterval(cooldownTimer)
      cooldownTimer = null
    }
  }, 1000)
}

watch(
  () => props.resendCooldownSeconds,
  (next) => {
    if (props.phase === 'input') startCooldown(next)
  },
)

onBeforeUnmount(() => {
  if (cooldownTimer) {
    clearInterval(cooldownTimer)
    cooldownTimer = null
  }
})

// ── OTP input handlers ──────────────────────────────────────────────
function setOtpRef(el: unknown, index: number) {
  // Vue template-ref callback yields Element | ComponentPublicInstance | null.
  // We always render raw <input> elements here, so coerce to HTMLInputElement.
  const input = el instanceof HTMLInputElement ? el : null
  otpRefs.value[index] = input
}

function focusOtpCell(index: number) {
  const cell = otpRefs.value[index]
  if (cell) cell.focus()
}

/** Coerce a single character to a digit; if not a digit, return null. */
function coerceDigit(raw: string): string | null {
  if (!raw) return ''
  const ch = raw.replace(/\D/g, '')
  return ch.length > 0 ? ch[0]! : null
}

function onOtpDigitInput(index: number, event: Event) {
  const input = event.target as HTMLInputElement
  const coerced = coerceDigit(input.value)
  if (coerced === null) {
    // Non-digit input → reject, restore prior value
    input.value = otpDigits.value[index] ?? ''
    return
  }
  otpDigits.value[index] = coerced
  input.value = coerced
  // Auto-advance to next cell if we just filled this one
  if (coerced && index < OTP_LENGTH - 1) {
    void nextTick(() => focusOtpCell(index + 1))
  }
}

function onOtpKeydown(index: number, event: KeyboardEvent) {
  if (event.key === 'Backspace') {
    if (otpDigits.value[index]) {
      // Clear current cell
      otpDigits.value[index] = ''
    } else if (index > 0) {
      // Move to previous cell and clear it
      event.preventDefault()
      otpDigits.value[index - 1] = ''
      void nextTick(() => focusOtpCell(index - 1))
    }
  } else if (event.key === 'ArrowLeft' && index > 0) {
    event.preventDefault()
    focusOtpCell(index - 1)
  } else if (event.key === 'ArrowRight' && index < OTP_LENGTH - 1) {
    event.preventDefault()
    focusOtpCell(index + 1)
  } else if (event.key === 'Enter') {
    // Submit when complete
    if (isOtpComplete.value) {
      event.preventDefault()
      onVerifyClick()
    }
  }
}

function onOtpPaste(event: ClipboardEvent) {
  const data = event.clipboardData?.getData('text') ?? ''
  if (!data) return
  const digits = data.replace(/\D/g, '').slice(0, OTP_LENGTH).split('')
  if (digits.length === 0) return
  event.preventDefault()
  for (let i = 0; i < OTP_LENGTH; i++) {
    otpDigits.value[i] = digits[i] ?? ''
  }
  // Focus the cell after the last filled digit
  const lastFilled = Math.min(digits.length, OTP_LENGTH) - 1
  void nextTick(() => focusOtpCell(Math.min(lastFilled + 1, OTP_LENGTH - 1)))
}

// ── Action handlers — emit only, never call backend directly ───────
function onDialogModelUpdate(open: boolean) {
  emit('update:modelValue', open)
}

function onCloseClick() {
  if (props.dismissible) emit('update:modelValue', false)
}

function onSendCodeClick() {
  emit('send-code', props.email)
}

function onResendClick() {
  if (resendCooldownRemaining.value > 0) return
  emit('resend-code', props.email)
}

function onVerifyClick() {
  if (!isOtpComplete.value) return
  emit('verify', {
    email: props.email,
    code: otpDigits.value.join(''),
  })
}

function onSignOutClick() {
  emit('sign-out')
}

function onChangeEmailClick() {
  emit('change-email')
}

function onEnterAppClick() {
  emit('enter-app')
}
</script>

<style scoped>
/* ── Root: 400px-wide dark glass card, neon ring, no full-page redesign ─ */
.unverified-email-dialog {
  position: relative;
  width: min(400px, 92vw);
  max-height: 92vh;
  overflow-y: auto;
  padding: 22px 24px 20px;
  background: linear-gradient(
      160deg,
      rgb(18 22 38 / 92%) 0%,
      rgb(12 14 26 / 94%) 60%,
      rgb(20 10 32 / 92%) 100%
    );
  border: 1px solid rgb(34 247 255 / 22%);
  border-radius: 20px;
  color: var(--imago-text-primary, #eaf6ff);
  box-shadow:
    0 0 0 1px rgb(34 247 255 / 18%),
    0 0 22px rgb(34 247 255 / 22%),
    0 0 60px rgb(196 38 255 / 18%),
    inset 0 1px 0 rgb(255 255 255 / 6%);
  backdrop-filter: blur(18px) saturate(120%);
  -webkit-backdrop-filter: blur(18px) saturate(120%);
}

/* ── Header ───────────────────────────────────────────────────────── */
.unverified-email-dialog__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding-bottom: 14px;
  border-bottom: 1px solid rgb(255 255 255 / 6%);
}

.unverified-email-dialog__title-row {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  min-width: 0;
}

.unverified-email-dialog__title {
  margin: 0;
  font-size: 17px;
  font-weight: 700;
  letter-spacing: 0.04em;
  color: #f1fbff;
  text-shadow: 0 0 12px rgb(34 247 255 / 28%);
}

.unverified-email-dialog__required-badge {
  display: inline-flex;
  align-items: center;
  height: 18px;
  padding: 0 8px;
  font-size: 10px;
  font-weight: 600;
  letter-spacing: 0.12em;
  color: #f1fbff;
  background: linear-gradient(135deg, rgb(196 38 255 / 36%), rgb(34 247 255 / 30%));
  border: 1px solid rgb(196 38 255 / 45%);
  border-radius: 999px;
  text-shadow: 0 0 8px rgb(196 38 255 / 35%);
}

.unverified-email-dialog__close {
  flex-shrink: 0;
  width: 28px;
  height: 28px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 0;
  background: transparent;
  border: 1px solid rgb(255 255 255 / 8%);
  border-radius: 50%;
  color: rgb(220 235 250 / 60%);
  cursor: pointer;
  transition:
    color var(--imago-ease-fast),
    background var(--imago-ease-fast),
    border-color var(--imago-ease-fast);
}

.unverified-email-dialog__close:hover:not(:disabled),
.unverified-email-dialog__close:focus-visible:not(:disabled) {
  background: rgb(255 255 255 / 5%);
  border-color: rgb(34 247 255 / 45%);
  color: #fff;
  outline: none;
}

.unverified-email-dialog__close:disabled {
  opacity: 0.4;
  cursor: not-allowed;
}

.unverified-email-dialog__close .q-icon {
  font-size: 15px;
}

/* ── Icon block (single small glyph per phase) ───────────────────── */
.unverified-email-dialog__icon {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  height: 56px;
  margin: 18px auto 6px;
}

.unverified-email-dialog__icon-glyph {
  font-size: 32px;
  color: var(--imago-cyan-bright, #2ff7ff);
  filter:
    drop-shadow(0 0 6px rgb(34 247 255 / 80%))
    drop-shadow(0 0 18px rgb(34 247 255 / 45%));
}

.unverified-email-dialog__icon-glyph--success {
  color: var(--imago-neon-green, #39ff14);
  filter:
    drop-shadow(0 0 6px rgb(57 255 20 / 80%))
    drop-shadow(0 0 18px rgb(34 247 255 / 40%));
}

.unverified-email-dialog__icon-bubble {
  position: absolute;
  right: -2px;
  bottom: -2px;
  font-size: 16px;
  color: var(--imago-neon-purple, #a855f7);
  background: var(--imago-bg-void, #08080f);
  border-radius: 50%;
  filter: drop-shadow(0 0 6px rgb(196 38 255 / 70%));
}

.unverified-email-dialog__spinner {
  filter: drop-shadow(0 0 8px rgb(34 247 255 / 60%));
}

/* ── Body copy ───────────────────────────────────────────────────── */
.unverified-email-dialog__body {
  display: flex;
  flex-direction: column;
  gap: 10px;
  padding: 8px 0 4px;
}

.unverified-email-dialog__lede {
  margin: 4px 0 0;
  font-size: 15px;
  font-weight: 600;
  text-align: center;
  color: #f1fbff;
  text-shadow: 0 0 12px rgb(34 247 255 / 24%);
}

.unverified-email-dialog__copy {
  margin: 0;
  font-size: 12.5px;
  line-height: 1.6;
  text-align: center;
  color: rgb(196 215 235 / 78%);
  letter-spacing: 0.02em;
}

.unverified-email-dialog__note {
  margin: 4px 0 0;
  font-size: 11.5px;
  line-height: 1.6;
  text-align: center;
  color: rgb(180 205 230 / 60%);
  letter-spacing: 0.02em;
}

.unverified-email-dialog__helper {
  margin: 6px 0 0;
  font-size: 11.5px;
  text-align: center;
  color: rgb(180 205 230 / 60%);
  letter-spacing: 0.04em;
}

/* ── Info row: label + email + status badge ──────────────────────── */
.unverified-email-dialog__info-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 12px 14px;
  margin: 6px 0 2px;
  background: rgb(255 255 255 / 3%);
  border: 1px solid rgb(255 255 255 / 8%);
  border-radius: 12px;
}

.unverified-email-dialog__info-meta {
  display: flex;
  flex-direction: column;
  gap: 4px;
  min-width: 0;
}

.unverified-email-dialog__info-label {
  font-size: 11px;
  letter-spacing: 0.08em;
  color: rgb(170 195 220 / 60%);
  text-transform: none;
}

.unverified-email-dialog__info-value {
  font-size: 13.5px;
  font-weight: 500;
  color: #eaf6ff;
  word-break: break-all;
}

.unverified-email-dialog__badge {
  flex-shrink: 0;
  display: inline-flex;
  align-items: center;
  height: 22px;
  padding: 0 9px;
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.06em;
  border-radius: 6px;
}

.unverified-email-dialog__badge--unverified {
  color: #ffd591;
  background: rgb(245 158 11 / 12%);
  border: 1px solid rgb(245 158 11 / 36%);
  text-shadow: 0 0 6px rgb(245 158 11 / 35%);
}

.unverified-email-dialog__badge--pending {
  color: #c8b6ff;
  background: rgb(196 38 255 / 12%);
  border: 1px solid rgb(196 38 255 / 36%);
  text-shadow: 0 0 6px rgb(196 38 255 / 35%);
}

/* ── Email pill (input phase) ────────────────────────────────────── */
.unverified-email-dialog__email-pill {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 10px 12px;
  margin: 4px 0 2px;
  background: linear-gradient(135deg, rgb(34 247 255 / 6%), rgb(196 38 255 / 6%));
  border: 1px solid rgb(34 247 255 / 22%);
  border-radius: 12px;
  font-size: 13px;
}

.unverified-email-dialog__email-pill-icon {
  font-size: 18px;
  color: var(--imago-cyan-bright, #2ff7ff);
  filter: drop-shadow(0 0 4px rgb(34 247 255 / 50%));
  flex-shrink: 0;
}

.unverified-email-dialog__email-pill-value {
  flex: 1;
  min-width: 0;
  color: #eaf6ff;
  word-break: break-all;
}

.unverified-email-dialog__email-pill-action {
  flex-shrink: 0;
  padding: 4px 8px;
  background: transparent;
  border: 0;
  font-size: 12px;
  color: var(--imago-cyan-bright, #2ff7ff);
  text-shadow: 0 0 8px rgb(34 247 255 / 35%);
  cursor: pointer;
  border-radius: 6px;
  transition: background var(--imago-ease-fast);
}

.unverified-email-dialog__email-pill-action:hover,
.unverified-email-dialog__email-pill-action:focus-visible {
  background: rgb(34 247 255 / 8%);
  outline: none;
}

/* ── OTP cells (6 separated inputs) ───────────────────────────────── */
.unverified-email-dialog__otp {
  display: grid;
  grid-template-columns: repeat(6, 1fr);
  gap: 8px;
  margin: 8px 0 2px;
}

.unverified-email-dialog__otp-cell {
  width: 100%;
  height: 52px;
  font-size: 22px;
  font-weight: 600;
  text-align: center;
  color: #f1fbff;
  background: rgb(255 255 255 / 3%);
  border: 1px solid rgb(255 255 255 / 10%);
  border-radius: 10px;
  caret-color: var(--imago-cyan-bright, #2ff7ff);
  outline: none;
  transition:
    border-color var(--imago-ease-fast),
    background var(--imago-ease-fast),
    box-shadow var(--imago-ease-fast);
  font-variant-numeric: tabular-nums;
}

.unverified-email-dialog__otp-cell::placeholder {
  color: rgb(255 255 255 / 18%);
}

.unverified-email-dialog__otp-cell:hover {
  border-color: rgb(34 247 255 / 30%);
  background: rgb(34 247 255 / 4%);
}

.unverified-email-dialog__otp-cell.is-focused {
  border-color: var(--imago-cyan-bright, #2ff7ff);
  background: rgb(34 247 255 / 6%);
  box-shadow:
    0 0 0 1px var(--imago-cyan-bright, #2ff7ff),
    0 0 14px rgb(34 247 255 / 45%);
}

.unverified-email-dialog__otp-cell.is-filled {
  border-color: rgb(34 247 255 / 50%);
}

.unverified-email-dialog__otp-cell.is-error {
  border-color: rgb(255 82 82 / 55%);
  box-shadow: 0 0 0 1px rgb(255 82 82 / 35%);
}

/* Hide native number-input spinners (we use text + inputmode) */
.unverified-email-dialog__otp-cell::-webkit-outer-spin-button,
.unverified-email-dialog__otp-cell::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

/* ── Inline error (under OTP cells) ───────────────────────────────── */
.unverified-email-dialog__inline-error {
  margin: 2px 0 0;
  font-size: 12px;
  text-align: center;
  color: #ff8c8c;
  text-shadow: 0 0 6px rgb(255 82 82 / 35%);
}

/* ── Resend row ───────────────────────────────────────────────────── */
.unverified-email-dialog__resend-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  margin-top: 6px;
  padding-top: 10px;
  border-top: 1px solid rgb(255 255 255 / 6%);
  font-size: 12px;
}

.unverified-email-dialog__resend-hint {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  color: rgb(170 195 220 / 70%);
  letter-spacing: 0.02em;
}

.unverified-email-dialog__resend-hint-icon {
  color: var(--imago-cyan-bright, #2ff7ff);
  filter: drop-shadow(0 0 4px rgb(34 247 255 / 45%));
}

.unverified-email-dialog__resend-action {
  background: transparent;
  border: 0;
  padding: 4px 6px;
  font-size: 12px;
  color: var(--imago-cyan-bright, #2ff7ff);
  text-shadow: 0 0 8px rgb(34 247 255 / 35%);
  cursor: pointer;
  border-radius: 6px;
  transition: background var(--imago-ease-fast);
}

.unverified-email-dialog__resend-action:hover:not(.is-disabled),
.unverified-email-dialog__resend-action:focus-visible:not(.is-disabled) {
  background: rgb(34 247 255 / 8%);
  outline: none;
}

.unverified-email-dialog__resend-action.is-disabled {
  color: rgb(170 195 220 / 50%);
  text-shadow: none;
  cursor: not-allowed;
}

/* ── Status list (sending / verifying phases) ────────────────────── */
.unverified-email-dialog__status-list {
  list-style: none;
  margin: 8px 0 4px;
  padding: 12px 14px;
  background: rgb(255 255 255 / 3%);
  border: 1px solid rgb(255 255 255 / 8%);
  border-radius: 12px;
}

.unverified-email-dialog__status-item {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 4px 0;
  font-size: 12.5px;
  color: rgb(196 215 235 / 70%);
  letter-spacing: 0.02em;
}

.unverified-email-dialog__status-item + .unverified-email-dialog__status-item {
  border-top: 1px dashed rgb(255 255 255 / 5%);
}

.unverified-email-dialog__status-item.is-done {
  color: rgb(196 215 235 / 95%);
}

.unverified-email-dialog__status-item.is-active {
  color: #f1fbff;
  text-shadow: 0 0 8px rgb(34 247 255 / 35%);
}

.unverified-email-dialog__status-item.is-pending {
  color: rgb(170 195 220 / 45%);
}

.unverified-email-dialog__status-icon {
  flex-shrink: 0;
  font-size: 16px;
  color: var(--imago-cyan-bright, #2ff7ff);
  filter: drop-shadow(0 0 4px rgb(34 247 255 / 55%));
}

.unverified-email-dialog__status-item.is-done .unverified-email-dialog__status-icon {
  color: var(--imago-neon-green, #39ff14);
  filter: drop-shadow(0 0 4px rgb(57 255 20 / 55%));
}

.unverified-email-dialog__status-item.is-pending .unverified-email-dialog__status-icon {
  color: rgb(170 195 220 / 30%);
}

.unverified-email-dialog__status-dot {
  flex-shrink: 0;
  display: inline-block;
  width: 8px;
  height: 8px;
  margin: 0 4px;
  background: rgb(170 195 220 / 30%);
  border-radius: 50%;
}

/* ── Checklist (success phase) ───────────────────────────────────── */
.unverified-email-dialog__checklist {
  list-style: none;
  margin: 6px 0 0;
  padding: 12px 14px;
  background: linear-gradient(135deg, rgb(34 247 255 / 5%), rgb(196 38 255 / 5%));
  border: 1px solid rgb(34 247 255 / 22%);
  border-radius: 12px;
}

.unverified-email-dialog__checklist-item {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 5px 0;
  font-size: 13px;
  color: #eaf6ff;
}

.unverified-email-dialog__checklist-item + .unverified-email-dialog__checklist-item {
  border-top: 1px dashed rgb(255 255 255 / 6%);
}

.unverified-email-dialog__checklist-icon {
  flex-shrink: 0;
  font-size: 18px;
  color: var(--imago-neon-green, #39ff14);
  filter:
    drop-shadow(0 0 4px rgb(57 255 20 / 65%))
    drop-shadow(0 0 12px rgb(34 247 255 / 35%));
}

/* ── Footer ───────────────────────────────────────────────────────── */
.unverified-email-dialog__footer {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 10px;
  margin-top: 16px;
  padding-top: 14px;
  border-top: 1px solid rgb(255 255 255 / 6%);
}

.unverified-email-dialog__submit {
  width: 100%;
  height: 44px;
  font-size: 14px !important;
  letter-spacing: 0.08em;
}

.unverified-email-dialog__ghost-action {
  background: transparent;
  border: 0;
  padding: 4px 8px;
  font-size: 13px;
  color: var(--imago-cyan-bright, #2ff7ff);
  text-shadow: 0 0 8px rgb(34 247 255 / 32%);
  cursor: pointer;
  border-radius: 6px;
  transition:
    color var(--imago-ease-fast),
    background var(--imago-ease-fast);
}

.unverified-email-dialog__ghost-action:hover,
.unverified-email-dialog__ghost-action:focus-visible {
  color: #9cfcff;
  background: rgb(34 247 255 / 6%);
  outline: none;
  text-shadow:
    0 0 10px rgb(34 247 255 / 55%),
    0 0 20px rgb(34 247 255 / 28%);
}

/* ── Mobile ───────────────────────────────────────────────────────── */
@media (max-width: 600px) {
  .unverified-email-dialog {
    width: min(360px, 94vw);
    padding: 18px 18px 16px;
    border-radius: 16px;
  }

  .unverified-email-dialog__title {
    font-size: 16px;
  }

  .unverified-email-dialog__lede {
    font-size: 14px;
  }

  .unverified-email-dialog__copy {
    font-size: 12px;
  }

  .unverified-email-dialog__otp-cell {
    height: 46px;
    font-size: 20px;
  }
}

@media (prefers-reduced-motion: reduce) {
  .unverified-email-dialog__close,
  .unverified-email-dialog__close:hover,
  .unverified-email-dialog__close:focus-visible,
  .unverified-email-dialog__email-pill-action,
  .unverified-email-dialog__resend-action,
  .unverified-email-dialog__otp-cell,
  .unverified-email-dialog__ghost-action,
  .unverified-email-dialog__ghost-action:hover,
  .unverified-email-dialog__ghost-action:focus-visible {
    transition: none;
    text-shadow: none;
  }
}
</style>

<style>
/* ── Dialog backdrop: dark blur (unscoped — Quasar teleports the dialog) ── */
.unverified-email-dialog-host + .q-dialog__backdrop,
.q-dialog__backdrop:has(+ .unverified-email-dialog-host) {
  background: rgb(2 6 15 / 78%) !important;
  backdrop-filter: blur(8px) saturate(120%);
  -webkit-backdrop-filter: blur(8px) saturate(120%);
}
</style>
