// DESIGN SPEC — generated by Designer agent // Coder: implement TODO items, do not change component structure or accessibility attributes
<template>
  <q-menu
    class="image-picker-popup"
    anchor="top middle"
    self="bottom middle"
    :offset="[0, -8]"
    transition-show="jump-up"
    transition-hide="jump-down"
  >
    <div class="image-picker-popup__container">
      <!-- Header -->
      <header class="image-picker-popup__header">
        <h3 class="image-picker-popup__title">
          {{ t('gallery.selectImage', 'Select Image') }}
        </h3>
        <q-btn
          flat
          round
          dense
          icon="close"
          size="sm"
          v-close-popup
          :aria-label="t('gallery.close', 'Close')"
          class="image-picker-popup__close"
        />
      </header>

      <!-- Source Selection Actions -->
      <div class="image-picker-popup__sources">
        <button
          type="button"
          class="image-picker-popup__source-btn"
          @click="handleUploadClick"
        >
          <q-icon name="cloud_upload" size="20px" aria-hidden="true" />
          <span class="image-picker-popup__source-label">{{ t('gallery.uploadLocal', 'Upload file') }}</span>
        </button>
        <button
          type="button"
          class="image-picker-popup__source-btn"
          @click="handleUrlClick"
        >
          <q-icon name="link" size="20px" aria-hidden="true" />
          <span class="image-picker-popup__source-label">{{ t('gallery.pasteUrl', 'Paste URL') }}</span>
        </button>
      </div>

      <q-separator dark class="image-picker-popup__divider" />

      <!-- Image Grid Section -->
      <section class="image-picker-popup__gallery">
        <h4 class="image-picker-popup__gallery-title">
          {{ t('gallery.recentUploads', 'Recent Uploads') }}
        </h4>
        
        <div class="image-picker-popup__grid" role="listbox" :aria-label="t('gallery.recentImagesList', 'Recent images')">
          <!-- TODO: Replace with actual v-for over fetched user images -->
          <button
            v-for="i in 6"
            :key="i"
            type="button"
            class="image-picker-popup__grid-item"
            role="option"
            :aria-selected="false"
            @click="handleImageSelect(`placeholder-${i}`)"
          >
            <!-- TODO: Replace placeholder with actual image thumbnail -->
            <div class="image-picker-popup__thumbnail-placeholder" aria-hidden="true">
              <q-icon name="image" size="24px" />
            </div>
          </button>
        </div>
      </section>
    </div>
  </q-menu>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

// TODO: Define props/emits for selected images (e.g. emit('select', imageId))

// ── Handlers ───────────────────────────────────────────────────────────────

function handleUploadClick() {
  // TODO: Trigger actual file input picker
  console.debug('Upload clicked')
}

function handleUrlClick() {
  // TODO: Open URL input dialog or expand input field
  console.debug('Paste URL clicked')
}

function handleImageSelect(id: string) {
  // TODO: Handle selection of a recent image
  console.debug('Image selected:', id)
}
</script>

<style lang="scss" scoped>
.image-picker-popup {
  /* Quasar applies classes to the q-menu root portal, so styling is scoped inside the container.
     Wait, Quasar's q-menu contents are rendered in a body portal. 
     To style the wrapper itself, we use global classes or QMenu properties. 
     But .image-picker-popup is passed to the portal content wrapper! */
  background: rgba(12, 12, 18, 0.95);
  border: 1px solid rgba(168, 85, 247, 0.2);
  border-radius: 16px;
  backdrop-filter: var(--imago-blur-panel, blur(24px));
  -webkit-backdrop-filter: var(--imago-blur-panel, blur(24px));
  box-shadow:
    0 12px 40px rgba(0, 0, 0, 0.5),
    0 0 0 1px rgba(255, 255, 255, 0.05) inset;
  color: var(--imago-text-primary, #fff);
  overflow: hidden;
}

.image-picker-popup__container {
  display: flex;
  flex-direction: column;
  width: 320px;
  max-width: 100vw;
}

.image-picker-popup__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px 16px 12px;
}

.image-picker-popup__title {
  margin: 0;
  font-size: 14px;
  font-weight: 600;
  color: var(--imago-text-primary, #fff);
  letter-spacing: 0.3px;
}

.image-picker-popup__close {
  color: var(--imago-text-muted, rgba(255, 255, 255, 0.5));
  transition: color var(--imago-ease-fast, 0.2s ease);

  &:hover {
    color: var(--imago-text-primary, #fff);
    background: rgba(255, 255, 255, 0.08);
  }
}

.image-picker-popup__sources {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 8px;
  padding: 0 16px 16px;
}

.image-picker-popup__source-btn {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 16px 8px;
  border: 1px solid rgba(255, 255, 255, 0.06);
  border-radius: 12px;
  background: rgba(255, 255, 255, 0.02);
  color: var(--imago-text-secondary, rgba(255, 255, 255, 0.8));
  cursor: pointer;
  transition: all var(--imago-ease-fast, 0.2s ease);

  &:hover,
  &:focus-visible {
    outline: none;
    background: rgba(168, 85, 247, 0.08);
    border-color: rgba(168, 85, 247, 0.3);
    color: var(--imago-cyan-bright, #00f0ff);
  }
  
  /* Visible focus replacement */
  &:focus-visible {
    box-shadow: 0 0 0 2px rgba(0, 240, 255, 0.4);
  }
}

.image-picker-popup__source-label {
  font-size: 12px;
  font-weight: 500;
}

.image-picker-popup__divider {
  background: rgba(255, 255, 255, 0.06);
  margin: 0;
}

.image-picker-popup__gallery {
  padding: 16px;
}

.image-picker-popup__gallery-title {
  margin: 0 0 12px;
  font-size: 12px;
  font-weight: 500;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  color: var(--imago-text-dim, rgba(255, 255, 255, 0.4));
}

.image-picker-popup__grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 8px;
}

.image-picker-popup__grid-item {
  position: relative;
  aspect-ratio: 1;
  border: 1px solid rgba(255, 255, 255, 0.04);
  border-radius: 8px;
  background: rgba(0, 0, 0, 0.2);
  cursor: pointer;
  overflow: hidden;
  padding: 0;
  transition: all var(--imago-ease-fast, 0.2s ease);

  &:hover,
  &:focus-visible {
    outline: none;
    border-color: rgba(168, 85, 247, 0.5);
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(168, 85, 247, 0.15);
  }

  /* Visible focus replacement */
  &:focus-visible {
    box-shadow: 0 0 0 2px rgba(0, 240, 255, 0.4), 0 4px 12px rgba(168, 85, 247, 0.15);
  }
}

.image-picker-popup__thumbnail-placeholder {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
  color: var(--imago-text-dim, rgba(255, 255, 255, 0.2));
  background: linear-gradient(135deg, rgba(255,255,255,0.02), rgba(255,255,255,0));
}

// ── Responsive ───────────────────────────────────────────────────────────
@media (max-width: 640px) {
  .image-picker-popup__container {
    width: 280px;
  }
}
</style>
