// DESIGN SPEC — generated by Designer agent // Coder: implement TODO items, do not change component structure or accessibility attributes
<template>
  <q-menu
    class="upload-menu-popup"
    anchor="top middle"
    self="bottom middle"
    :offset="[0, 16]"
    transition-show="jump-up"
    transition-hide="jump-down"
  >
    <div class="upload-menu-popup__container">
      <button type="button" class="upload-menu-popup__item" @click="handleSelect('image')">
        <q-icon name="image" size="22px" class="upload-menu-popup__icon" />
        <span class="upload-menu-popup__label">{{ t('gallery.typeImage', '图片') }}</span>
      </button>
      
      <button type="button" class="upload-menu-popup__item" @click="handleSelect('audio')">
        <q-icon name="graphic_eq" size="22px" class="upload-menu-popup__icon" />
        <span class="upload-menu-popup__label">{{ t('gallery.typeAudio', '音频') }}</span>
      </button>

      <button type="button" class="upload-menu-popup__item" @click="handleSelect('video')">
        <q-icon name="videocam" size="22px" class="upload-menu-popup__icon" />
        <span class="upload-menu-popup__label">{{ t('gallery.typeVideo', '视频') }}</span>
      </button>

      <button type="button" class="upload-menu-popup__item" @click="handleSelect('text')">
        <q-icon name="description" size="22px" class="upload-menu-popup__icon" />
        <span class="upload-menu-popup__label">{{ t('gallery.typeText', '文本') }}</span>
      </button>
    </div>
  </q-menu>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

const emit = defineEmits<{
  (e: 'select', type: 'image' | 'audio' | 'video' | 'text'): void
}>()

function handleSelect(type: 'image' | 'audio' | 'video' | 'text') {
  // Emit intent to open picker; parent should handle actual file selection
  emit('select', type)
}
</script>

<style lang="scss">
/* Target the QMenu portal wrapper to allow the caret to overflow and prevent double backgrounds */
.upload-menu-popup {
  background: transparent !important;
  box-shadow: none !important;
  border: none !important;
  overflow: visible !important;
}
</style>

<style lang="scss" scoped>
.upload-menu-popup__container {
  position: relative;
  display: flex;
  flex-direction: column;
  gap: 8px;
  width: 140px;
  padding: 8px;
  border-radius: 16px;
  background:
    radial-gradient(ellipse 60% 80% at 50% 0%, rgba(168, 85, 247, 0.08), transparent 70%),
    radial-gradient(ellipse 80% 60% at 100% 100%, rgba(217, 70, 239, 0.06), transparent 70%),
    rgba(6, 6, 12, 0.95);
  border: 1px solid rgba(168, 85, 247, 0.2);
  backdrop-filter: var(--imago-blur-panel, blur(24px));
  -webkit-backdrop-filter: var(--imago-blur-panel, blur(24px));
  box-shadow: 
    0 16px 40px rgba(0, 0, 0, 0.6),
    inset 0 0 20px rgba(168, 85, 247, 0.05);
  
  /* The downward pointing caret/arrow */
  &::after {
    content: '';
    position: absolute;
    bottom: -6px;
    left: 50%;
    transform: translateX(-50%) rotate(45deg);
    width: 12px;
    height: 12px;
    background: rgba(6, 6, 12, 0.95);
    border-right: 1px solid rgba(168, 85, 247, 0.2);
    border-bottom: 1px solid rgba(168, 85, 247, 0.2);
    box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.3);
    z-index: -1;
  }
}

.upload-menu-popup__item {
  display: flex;
  align-items: center;
  gap: 14px;
  padding: 12px 16px;
  background: var(--imago-bg-raised);
  border: 1px solid var(--imago-border-light);
  border-radius: 10px;
  color: var(--imago-text-primary);
  cursor: pointer;
  transition: all var(--imago-ease-fast);
  outline: none;

  &:hover,
  &:focus-visible {
    background: var(--imago-cyan-06);
    border-color: var(--imago-border-cyan-active);
    box-shadow: 
      var(--imago-glow-cyan-soft),
      inset 0 0 12px var(--imago-cyan-08);

    .upload-menu-popup__icon {
      color: var(--imago-neon-cyan);
      filter: drop-shadow(0 0 6px rgba(0, 240, 255, 0.5));
    }
  }
}

.upload-menu-popup__icon {
  color: var(--imago-text-muted);
  transition: all var(--imago-ease-fast);
}

.upload-menu-popup__label {
  font-size: 15px;
  font-weight: 500;
  letter-spacing: 0.5px;
}
</style>
