<!--
  DESIGN SPEC — generated by Designer agent
  Coder: implement TODO items, do not change component structure or accessibility attributes.

  AudioCard — 旁白与音乐 (Narration & Music)
  Title, description, an italic timing note, an audio thumbnail row (waveform
  glyph), and a footer with a "最终音频 ▾" selector, a "+" add-media button, and a
  "评论生成" button. Purely presentational.
-->

<template>
  <article
    class="card"
    :class="{ 'card--active': active }"
  >
    <!-- ── Head: drag handle · title · collapse ─────────────────── -->
    <div class="card__head">
      <span class="card__drag" aria-hidden="true">⠿</span>

      <button
        type="button"
        class="card__title-btn"
        :aria-pressed="active"
        :aria-label="`选择 ${track.title}`"
        @click="emit('select', track.id)"
      >
        <span class="card__title">{{ track.title }}</span>
        <span v-if="active" class="card__check" aria-hidden="true">
          <OiIcon name="check" :size="14" />
        </span>
      </button>

      <button
        type="button"
        class="card__collapse"
        :aria-expanded="!collapsed"
        :aria-label="collapsed ? `展开 ${track.title}` : `收起 ${track.title}`"
        @click="emit('toggle', track.id)"
      >
        <OiIcon
          name="chevron-down"
          :size="14"
          class="card__collapse-icon"
          :class="{ 'card__collapse-icon--collapsed': collapsed }"
        />
      </button>
    </div>

    <!-- ── Body (hidden when collapsed) ─────────────────────────── -->
    <template v-if="!collapsed">
      <p v-if="track.description" class="card__description card__description--clamp">
        {{ track.description }}
      </p>

      <p v-if="track.timingNote" class="card__timing">{{ track.timingNote }}</p>

      <!-- Audio thumbnail row (waveform glyph) -->
      <div class="card__thumbs" :aria-label="`${track.title} 音频`">
        <div
          v-for="(thumb, index) in track.thumbnails"
          :key="index"
          class="card__thumb"
          aria-hidden="true"
        >
          <img
            v-if="thumb"
            :src="thumb"
            alt=""
            class="card__thumb-image"
            loading="lazy"
          >
          <span v-else class="card__thumb-wave">
            <OiIcon name="enhance-wave" :size="16" />
          </span>
        </div>
        <button
          v-if="!readOnly"
          type="button"
          class="card__thumb card__thumb--add"
          :aria-label="`为 ${track.title} 添加音频`"
          @click="emit('add-media', track.id)"
        >
          <OiIcon name="plus" :size="14" />
        </button>
      </div>

      <!-- Footer -->
      <div class="card__footer">
        <button
          v-if="!readOnly"
          type="button"
          class="card__select"
          aria-haspopup="true"
          :aria-label="`${track.title} 最终音频`"
          @click="emit('select-type', track.id)"
        >
          <span>最终音频</span>
          <OiIcon name="chevron-down" :size="12" />
        </button>
        <button
          v-if="!readOnly"
          type="button"
          class="card__add"
          :aria-label="`为 ${track.title} 添加`"
          @click="emit('add-media', track.id)"
        >
          <OiIcon name="plus" :size="12" />
        </button>
        <button
          type="button"
          class="card__generate"
          :aria-label="`为 ${track.title} 评论生成`"
          @click="emit('generate', track.id)"
        >
          <OiIcon name="enhance-wave" :size="12" />
          <span>评论生成</span>
        </button>
      </div>
    </template>
  </article>
</template>

<script setup lang="ts">
import OiIcon from 'src/components/ui/OiIcon.vue'
import type { AudioCardVM } from './types'

defineProps<{
  track: AudioCardVM
  active?: boolean
  readOnly?: boolean
  collapsed?: boolean
}>()

const emit = defineEmits<{
  (e: 'select', id: string): void
  (e: 'toggle', id: string): void
  (e: 'add-media', id: string): void
  (e: 'select-type', id: string): void
  (e: 'generate', id: string): void
}>()
</script>

<style lang="scss" scoped>
@use './card-chrome.scss';
</style>
