<!--
  DESIGN SPEC — generated by Designer agent
  Coder: implement TODO items, do not change component structure or accessibility attributes.

  ShotCard — 分镜 (Shots)
  Title + subtitle line, an inline chip row ("场景:" chip + character chips with
  small avatars), a clamped description with an inline 展开/收起 link, a mixed
  media row (video thumb with ▶ play badge + audio thumbs with waveform glyph),
  and a footer with "最终镜头 ▾" + "最终音频 ▾" selectors, a "+" add-media button,
  and a "评论生成" button.

  `descExpanded` is local presentational UI state (expand/collapse of the long
  description) — distinct from the card-level `collapsed` prop owned by the parent.
-->

<template>
  <article
    class="card"
    :class="{ 'card--active': active }"
  >
    <!-- ── Head: drag handle · title · collapse ─────────────────── -->
    <div class="card__head">
      <span class="card__drag" aria-hidden="true">⠿</span>

      <button
        type="button"
        class="card__title-btn"
        :aria-pressed="active"
        :aria-label="`选择 ${shot.title}`"
        @click="emit('select', shot.id)"
      >
        <span class="card__title">{{ shot.title }}</span>
        <span v-if="active" class="card__check" aria-hidden="true">
          <OiIcon name="check" :size="14" />
        </span>
      </button>

      <button
        type="button"
        class="card__collapse"
        :aria-expanded="!collapsed"
        :aria-label="collapsed ? `展开 ${shot.title}` : `收起 ${shot.title}`"
        @click="emit('toggle', shot.id)"
      >
        <OiIcon
          name="chevron-down"
          :size="14"
          class="card__collapse-icon"
          :class="{ 'card__collapse-icon--collapsed': collapsed }"
        />
      </button>
    </div>

    <!-- ── Body (hidden when card collapsed) ────────────────────── -->
    <template v-if="!collapsed">
      <p v-if="shot.subtitle" class="card__subtitle">{{ shot.subtitle }}</p>

      <!-- Scene chip + inline character chips -->
      <div
        v-if="shot.sceneLabel || shot.characters.length > 0"
        class="card__chips"
        :aria-label="`${shot.title} 场景与角色`"
      >
        <span v-if="shot.sceneLabel" class="card__chip card__chip--scene">
          场景: {{ shot.sceneLabel }}
        </span>
        <span
          v-for="character in shot.characters"
          :key="character.id"
          class="card__chip"
        >
          <img
            v-if="character.avatarUrl"
            :src="character.avatarUrl"
            alt=""
            class="card__chip-avatar"
            loading="lazy"
          >
          <span
            v-else
            class="card__chip-avatar card__chip-avatar--fallback"
            aria-hidden="true"
          >{{ initial(character.name) }}</span>
          <span class="card__chip-name">{{ character.name }}</span>
        </span>
      </div>

      <!-- Description with expand/collapse -->
      <p
        class="card__description"
        :class="{ 'card__description--clamp': !descExpanded }"
      >
        {{ shot.description }}
      </p>
      <button
        type="button"
        class="card__expand"
        :aria-expanded="descExpanded"
        @click="toggleDescription"
      >
        {{ descExpanded ? '收起' : '展开' }}
      </button>

      <!-- Mixed media row: video (play badge) + audio (waveform) + images -->
      <div class="card__thumbs" :aria-label="`${shot.title} 媒体`">
        <div
          v-for="(thumb, index) in shot.media"
          :key="index"
          class="card__thumb"
          aria-hidden="true"
        >
          <img
            v-if="thumb.url"
            :src="thumb.url"
            alt=""
            class="card__thumb-image"
            loading="lazy"
          >
          <OiIcon v-else-if="thumb.kind === 'image'" name="image-card" :size="14" />

          <!-- Overlays -->
          <span v-if="thumb.kind === 'video'" class="card__thumb-play" />
          <span v-else-if="thumb.kind === 'audio'" class="card__thumb-wave">
            <OiIcon name="enhance-wave" :size="16" />
          </span>
        </div>
        <button
          v-if="!readOnly"
          type="button"
          class="card__thumb card__thumb--add"
          :aria-label="`为 ${shot.title} 添加媒体`"
          @click="emit('add-media', shot.id)"
        >
          <OiIcon name="plus" :size="14" />
        </button>
      </div>

      <!-- Footer -->
      <div class="card__footer">
        <button
          v-if="!readOnly"
          type="button"
          class="card__select"
          aria-haspopup="true"
          :aria-label="`${shot.title} 最终镜头`"
          @click="emit('select-type', shot.id)"
        >
          <span>最终镜头</span>
          <OiIcon name="chevron-down" :size="12" />
        </button>
        <button
          v-if="!readOnly"
          type="button"
          class="card__select"
          aria-haspopup="true"
          :aria-label="`${shot.title} 最终音频`"
          @click="emit('select-type', shot.id)"
        >
          <span>最终音频</span>
          <OiIcon name="chevron-down" :size="12" />
        </button>
        <button
          type="button"
          class="card__generate"
          :aria-label="`为 ${shot.title} 评论生成`"
          @click="emit('generate', shot.id)"
        >
          <OiIcon name="enhance-wave" :size="12" />
          <span>评论生成</span>
        </button>
      </div>
    </template>
  </article>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import OiIcon from 'src/components/ui/OiIcon.vue'
import type { ShotCardVM } from './types'

defineProps<{
  shot: ShotCardVM
  active?: boolean
  readOnly?: boolean
  collapsed?: boolean
}>()

const emit = defineEmits<{
  (e: 'select', id: string): void
  (e: 'toggle', id: string): void
  (e: 'add-media', id: string): void
  (e: 'select-type', id: string): void
  (e: 'generate', id: string): void
}>()

// Local UI: expand/collapse the long description (not the card-level collapse).
const descExpanded = ref(false)

function toggleDescription(): void {
  descExpanded.value = !descExpanded.value
}

/** First grapheme of a name for the avatar fallback. */
function initial(name: string): string {
  return Array.from(name.trim())[0] ?? '?'
}
</script>

<style lang="scss" scoped>
@use './card-chrome.scss';
</style>
