// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change these interface shapes or names.
//
// View-model contracts for the redesigned 故事板 left panel accordion. The parent
// page (bd-C) maps domain data into these shapes; the panel and its card
// sub-components are purely presentational over them.

/** The three accordion sections, top → bottom. */
export type LeftPanelSection = 'elements' | 'shots' | 'audio'

/** A single media thumbnail inside a card's horizontal thumbnail row. */
export interface ShotMediaThumb {
  /** Resolved media URL, or null for an empty/placeholder slot. */
  url: string | null
  /** Drives the overlay glyph: ▶ play badge for video, waveform for audio. */
  kind: 'video' | 'audio' | 'image'
}

/** 关键元素 — a character or scene element card. */
export interface ElementCardVM {
  id: string
  kind: 'character' | 'scene'
  title: string
  description: string
  thumbnails: ReadonlyArray<string | null>
  /** Footer type-selector label, e.g. "图片". Defaults to "图片" when omitted. */
  selectorLabel?: string
}

/** An inline character chip (small avatar + name) embedded in a shot description. */
export interface CharacterChipVM {
  id: string
  name: string
  avatarUrl: string | null
}

/** 分镜 — a shot card mixing video + audio media. */
export interface ShotCardVM {
  id: string
  title: string
  /** Secondary line, e.g. "带有内部剪辑的长镜头 (约 15s)". */
  subtitle?: string
  /** Scene chip label rendered before the character chips, e.g. "林北的公寓". */
  sceneLabel?: string
  /** Inline character chips embedded in the description block. */
  characters: ReadonlyArray<CharacterChipVM>
  description: string
  /** Optional status pill text, e.g. "草稿" / "已生成". */
  status?: string
  /** Optional duration label, e.g. "约 15s". */
  durationLabel?: string
  /** Mixed media row (video + audio thumbs). */
  media: ReadonlyArray<ShotMediaThumb>
}

/** 旁白与音乐 — an audio (narration / music) card. */
export interface AudioCardVM {
  id: string
  title: string
  description: string
  /** Italic timing note, e.g. "从全局 0s 开始，作为贯穿全片的背景音乐。". */
  timingNote?: string
  thumbnails: ReadonlyArray<string | null>
}
