import { Context, Effect, Layer } from "effect"
import {
  type MediaProvider,
  type GenerateImageParams,
  type GenerateVideoParams,
  type GenerateResult,
  GenerateError,
  MediaProviderTag,
} from "../provider.js"
import { MediaConfig, type MediaConfigData } from "../config.js"

// ── Google Provider Implementation ─────────────────────────────────────

/**
 * Creates a Google media provider backed by the `@google/genai` SDK.
 *
 * Supports:
 *   - Image generation: `gemini-2.5-flash-image`, `gemini-3-pro-image-preview`
 *   - Video generation: skeleton only (Veo API not yet integrated)
 *
 * Returns a clear error when `GOOGLE_API_KEY` is missing.
 */
export function createGoogleProvider(config: MediaConfigData): MediaProvider {
  const apiKey = config.providers["google"]?.apiKey

  const models: string[] = [
    "gemini-2.5-flash-image",
    "gemini-3-pro-image-preview",
    // Video models registered for capability discovery; live calls deferred
    "veo-3.1-generate-preview",
    "veo-3.1-fast-generate-preview",
  ]

  const imageModels = [
    "gemini-2.5-flash-image",
    "gemini-3-pro-image-preview",
  ]

  function requireApiKey(): string {
    if (!apiKey) {
      throw new GenerateError(
        "google",
        "GOOGLE_API_KEY is not set. " +
          "Configure it via the GOOGLE_API_KEY environment variable or " +
          "MediaConfig.providers.google.apiKey.",
      )
    }
    return apiKey
  }

  return {
    id: "google",
    label: "Google (Gemini / Veo)",
    kind: "image",
    models,

    generateImage(params: GenerateImageParams) {
      return Effect.tryPromise({
        try: async () => {
          const key = requireApiKey()
          // Dynamic import for testability — Bun's mock.module can intercept this
          const { GoogleGenAI } = await import("@google/genai")
          const ai = new GoogleGenAI({ apiKey: key })

          const response = await ai.models.generateContent({
            model: params.model,
            contents: params.prompt,
            config: {
              imageConfig: {
                aspectRatio: "1:1",
              },
            },
          })

          // Extract inline image data from the response
          const parts = response.candidates?.[0]?.content?.parts ?? []
          for (const part of parts) {
            if (part.inlineData && part.inlineData.data) {
              const mimeType = part.inlineData.mimeType ?? "image/png"
              return {
                url: `data:${mimeType};base64,${part.inlineData.data}`,
                metadata: {
                  provider: "google",
                  model: params.model,
                  mimeType,
                },
              } satisfies GenerateResult
            }
          }

          // No image found in response — return text as error info
          const text = response.text ?? "(no output)"
          throw new GenerateError(
            "google",
            `No image generated by ${params.model}. Model response: ${text.slice(0, 200)}`,
          )
        },
        catch: (error) =>
          error instanceof GenerateError
            ? error
            : new GenerateError(
                "google",
                `Google API error: ${(error as Error).message}`,
                error,
              ),
      })
    },

    generateVideo(_params: GenerateVideoParams) {
      return Effect.fail(
        new GenerateError(
          "google",
          "Veo video generation is not yet implemented. " +
            "Image generation is available via gemini-2.5-flash-image and gemini-3-pro-image-preview.",
        ),
      )
    },
  }
}

// ── Layer ──────────────────────────────────────────────────────────────

/**
 * Google provider layer.
 *
 * Requires `MediaConfig`.  If `GOOGLE_API_KEY` is configured the provider
 * is registered; generation fails with a clear error at execute time
 * if the key is missing.
 */
export const GoogleProviderLayer: Layer.Layer<
  MediaProviderTag,
  GenerateError,
  MediaConfig
> = Layer.effect(
  MediaProviderTag,
  Effect.gen(function* () {
    const config = yield* MediaConfig
    return createGoogleProvider(config)
  }),
)
