<!--
  DESIGN SPEC — generated by Designer agent
  Coder: implement TODO items, do not change component structure or accessibility attributes.

  PreviewPane — center detail view of the 故事板 tab
  ─────────────────────────────────────────────────
  Selection-driven big preview of the item picked in the left storyboard panel
  (element / shot / audio). Layout:
    - Header: "预览" label + item title; right-aligned action icons
      (评论 / 下载 / 调色 / 删除) + an "HD" toggle pill.
    - Meta sub-row: model badge + resolution/aspect badge.
    - Media stage: <img> for elements, <video controls> for shots,
      <audio controls> for audio; a left-edge vertical "元素" nav with up/down
      chevrons to step prev/next within the current section.
    - Bottom action bar: comment input + 手动编辑 + primary 重新生成.
    - Empty state when nothing is selected.

  Purely presentational over `preview`. All data/IO is bd-E's job (TODO sites).
  NOTE: HTML comment banner on purpose — `//` before <template> crashes Vite HMR.
-->

<template>
  <section class="preview" aria-label="预览详情">
    <!-- ── Empty state ───────────────────────────────────────────── -->
    <div v-if="preview.kind === 'empty'" class="preview__empty">
      <OiIcon name="image-card" :size="28" />
      <p class="preview__empty-title">从左侧故事板选择一个条目查看详情</p>
    </div>

    <!-- ── Detail ────────────────────────────────────────────────── -->
    <template v-else>
      <!-- Header -->
      <header class="preview__header">
        <div class="preview__title-block">
          <span class="preview__eyebrow">预览</span>
          <h2 class="preview__title">{{ preview.title }}</h2>
        </div>

        <div class="preview__actions">
          <button
            type="button"
            class="preview__icon-btn"
            aria-label="评论"
            @click="onCommentFocus"
          >
            <OiIcon name="chat-bubble" :size="16" />
          </button>
          <button
            type="button"
            class="preview__icon-btn"
            aria-label="下载"
            @click="emit('download')"
          >
            <OiIcon name="download" :size="16" />
          </button>
          <button
            type="button"
            class="preview__icon-btn"
            aria-label="调色"
            @click="emit('manual-edit')"
          >
            <OiIcon name="palette" :size="16" />
          </button>
          <button
            type="button"
            class="preview__icon-btn preview__icon-btn--danger"
            aria-label="删除"
            @click="emit('delete')"
          >
            <OiIcon name="trash" :size="16" />
          </button>
          <button
            type="button"
            class="preview__hd"
            :class="{ 'preview__hd--active': hdActive }"
            :aria-pressed="hdActive"
            aria-label="切换高清"
            @click="onToggleHd"
          >
            HD
          </button>
        </div>
      </header>

      <!-- Meta sub-row -->
      <div class="preview__meta">
        <span v-if="preview.modelLabel" class="preview__badge">
          <OiIcon name="sparkle" :size="12" />
          <span>{{ preview.modelLabel }}</span>
        </span>
        <span v-if="preview.resolutionLabel" class="preview__badge preview__badge--muted">
          {{ preview.resolutionLabel }}
        </span>
      </div>

      <!-- Media stage with left-edge prev/next nav -->
      <div class="preview__stage">
        <nav class="preview__nav" aria-label="元素切换">
          <button
            type="button"
            class="preview__nav-btn"
            :disabled="!preview.hasPrev"
            aria-label="上一个元素"
            @click="emit('prev')"
          >
            <OiIcon name="chevron-down" :size="16" class="preview__nav-up" />
          </button>
          <span class="preview__nav-label" aria-hidden="true">元素</span>
          <button
            type="button"
            class="preview__nav-btn"
            :disabled="!preview.hasNext"
            aria-label="下一个元素"
            @click="emit('next')"
          >
            <OiIcon name="chevron-down" :size="16" />
          </button>
        </nav>

        <div class="preview__media">
          <img
            v-if="preview.kind === 'image' && preview.mediaUrl"
            :src="preview.mediaUrl"
            :alt="preview.title"
            class="preview__image"
          >
          <!-- eslint-disable-next-line vuejs-accessibility/media-has-caption -->
          <video
            v-else-if="preview.kind === 'video' && preview.mediaUrl"
            :src="preview.mediaUrl"
            class="preview__video"
            controls
            playsinline
          />
          <!-- eslint-disable-next-line vuejs-accessibility/media-has-caption -->
          <audio
            v-else-if="preview.kind === 'audio' && preview.mediaUrl"
            :src="preview.mediaUrl"
            class="preview__audio"
            controls
          />
          <div v-else class="preview__media-fallback">
            <OiIcon :name="preview.kind === 'audio' ? 'enhance-wave' : 'image-card'" :size="28" />
            <span>暂无媒体</span>
          </div>
        </div>
      </div>

      <!-- Bottom action bar -->
      <footer class="preview__bar">
        <label class="preview__comment">
          <span class="sr-only">评论</span>
          <input
            v-model="commentDraft"
            type="text"
            class="preview__comment-input"
            placeholder="输入评论，编辑当前镜头并生成新画面…"
            @keydown.enter.prevent="submitComment"
          >
        </label>
        <button
          type="button"
          class="preview__bar-btn"
          @click="emit('manual-edit')"
        >
          手动编辑
        </button>
        <button
          type="button"
          class="preview__bar-btn preview__bar-btn--primary"
          @click="emit('regenerate')"
        >
          <OiIcon name="enhance-wave" :size="14" />
          <span>重新生成</span>
        </button>
      </footer>
    </template>
  </section>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import OiIcon from 'src/components/ui/OiIcon.vue'

// ── Public shape ────────────────────────────────────────────────────────────

export type PreviewKind = 'image' | 'video' | 'audio' | 'empty'

export interface PreviewVM {
  id: string
  section: 'element' | 'shot' | 'audio'
  kind: PreviewKind
  title: string
  mediaUrl: string | null
  modelLabel?: string
  resolutionLabel?: string
  /** Whether a previous item exists in the current section (disables up nav). */
  hasPrev: boolean
  /** Whether a next item exists in the current section (disables down nav). */
  hasNext: boolean
}

// ── Props ────────────────────────────────────────────────────────────────────

defineProps<{
  preview: PreviewVM
}>()

const emit = defineEmits<{
  (e: 'prev'): void
  (e: 'next'): void
  (e: 'regenerate'): void
  (e: 'manual-edit'): void
  (e: 'comment-submit', text: string): void
  (e: 'download'): void
  (e: 'delete'): void
  (e: 'toggle-hd'): void
}>()

// ── Comment input (local draft only; submission is relayed up) ────────────────

const commentDraft = ref('')

function submitComment(): void {
  const text = commentDraft.value.trim()
  if (!text) return
  emit('comment-submit', text)
  commentDraft.value = ''
}

function onCommentFocus(): void {
  // TODO (bd-E): focus the comment input / open a comment affordance.
  emit('comment-submit', '')
}

// ── HD pill (local visual toggle; canonical state owned by parent) ────────────

const hdActive = ref(false)

function onToggleHd(): void {
  hdActive.value = !hdActive.value
  emit('toggle-hd')
}
</script>

<style lang="scss" scoped>
.preview {
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
  min-height: 0;
  background: linear-gradient(180deg, var(--imago-bg-deep), var(--imago-bg-void) 40%);
}

// ── Empty state ───────────────────────────────────────────────────────────────

.preview__empty {
  flex: 1 1 auto;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 10px;
  color: var(--imago-text-faint);
  text-align: center;
  padding: 32px;
}

.preview__empty-title {
  margin: 0;
  font-size: 13px;
  color: var(--imago-text-secondary);
}

// ── Header ────────────────────────────────────────────────────────────────────

.preview__header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 16px;
  padding: 18px 22px 10px;
  flex-shrink: 0;
}

.preview__title-block {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 3px;
}

.preview__eyebrow {
  font-size: 10.5px;
  font-weight: 600;
  letter-spacing: 0.16em;
  text-transform: uppercase;
  color: var(--imago-text-dim);
}

.preview__title {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
  color: var(--imago-text-primary);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.preview__actions {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  flex-shrink: 0;
}

.preview__icon-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 30px;
  height: 30px;
  padding: 0;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-md);
  background: transparent;
  color: var(--imago-text-muted);
  cursor: pointer;
  transition: color 120ms ease, border-color 120ms ease, background 120ms ease;
}

.preview__icon-btn:hover {
  color: var(--imago-text-primary);
  border-color: var(--imago-border-cyan);
  background: var(--imago-cyan-06);
}

.preview__icon-btn--danger:hover {
  color: var(--imago-neon-pink);
  border-color: rgba(255, 45, 149, 0.4);
  background: rgba(255, 45, 149, 0.08);
}

.preview__hd {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  height: 30px;
  padding: 0 12px;
  margin-left: 4px;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-pill);
  background: transparent;
  color: var(--imago-text-secondary);
  font-size: 11px;
  font-weight: 700;
  letter-spacing: 0.08em;
  cursor: pointer;
  transition: color 120ms ease, border-color 120ms ease, background 120ms ease;
}

.preview__hd:hover {
  color: var(--imago-text-primary);
  border-color: var(--imago-border-cyan);
}

.preview__hd--active {
  color: var(--imago-neon-cyan);
  border-color: var(--imago-border-cyan-active);
  background: var(--imago-cyan-08);
}

// ── Meta sub-row ───────────────────────────────────────────────────────────────

.preview__meta {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 0 22px 12px;
  flex-shrink: 0;
}

.preview__badge {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  padding: 4px 10px;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-pill);
  background: var(--imago-bg-surface);
  color: var(--imago-text-secondary);
  font-size: 11px;
}

.preview__badge--muted {
  color: var(--imago-text-muted);
  font-variant-numeric: tabular-nums;
}

// ── Media stage ────────────────────────────────────────────────────────────────

.preview__stage {
  flex: 1 1 auto;
  min-height: 0;
  display: flex;
  align-items: stretch;
  gap: 12px;
  padding: 0 22px;
}

.preview__nav {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 8px;
  flex-shrink: 0;
}

.preview__nav-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 30px;
  height: 30px;
  padding: 0;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-surface);
  color: var(--imago-text-secondary);
  cursor: pointer;
  transition: color 120ms ease, border-color 120ms ease, background 120ms ease;
}

.preview__nav-btn:hover:not(:disabled) {
  color: var(--imago-neon-cyan);
  border-color: var(--imago-border-cyan);
  background: var(--imago-cyan-06);
}

.preview__nav-btn:disabled {
  opacity: 0.35;
  cursor: not-allowed;
}

.preview__nav-up {
  transform: rotate(180deg);
}

.preview__nav-label {
  font-size: 10px;
  letter-spacing: 0.12em;
  color: var(--imago-text-faint);
  writing-mode: vertical-rl;
}

.preview__media {
  flex: 1 1 auto;
  min-width: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-xl);
  background: var(--imago-bg-void);
  overflow: hidden;
}

.preview__image,
.preview__video {
  max-width: 100%;
  max-height: 100%;
  object-fit: contain;
  display: block;
}

.preview__audio {
  width: 80%;
  max-width: 420px;
}

.preview__media-fallback {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  color: var(--imago-text-faint);
  font-size: 12px;
}

// ── Bottom action bar ───────────────────────────────────────────────────────────

.preview__bar {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 14px 22px 18px;
  flex-shrink: 0;
}

.preview__comment {
  flex: 1 1 auto;
  min-width: 0;
}

.preview__comment-input {
  width: 100%;
  height: 38px;
  padding: 0 14px;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-surface);
  color: var(--imago-text-primary);
  font: inherit;
  font-size: 12.5px;
}

.preview__comment-input::placeholder {
  color: var(--imago-text-faint);
}

.preview__comment-input:focus-visible {
  outline: none;
  border-color: var(--imago-border-cyan-active);
}

.preview__bar-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 5px;
  height: 38px;
  padding: 0 16px;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-md);
  background: transparent;
  color: var(--imago-text-secondary);
  font-size: 12.5px;
  font-weight: 500;
  cursor: pointer;
  flex-shrink: 0;
  transition: color 120ms ease, border-color 120ms ease, background 120ms ease;
}

.preview__bar-btn:hover {
  color: var(--imago-text-primary);
  border-color: var(--imago-border-cyan);
  background: var(--imago-cyan-06);
}

.preview__bar-btn--primary {
  border-color: var(--imago-border-cyan-active);
  color: var(--imago-neon-cyan);
  background: var(--imago-cyan-08);
}

.preview__bar-btn--primary:hover {
  color: var(--imago-neon-cyan);
  background: var(--imago-cyan-06);
}

// ── Utility ───────────────────────────────────────────────────────────────────

.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}
</style>
