// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change component structure or accessibility attributes
// ─────────────────────────────────────────────────────────────────────────────
// ProjectWorkspaceGrid — center column wrapper for the redesigned project page
// ─────────────────────────────────────────────────────────────────────────────
// After the redesign, the top command bar (back, status, tabs, action buttons)
// lives in the shared `WorkspaceTopBar` rendered by ProjectWorkspacePage. This
// component now ONLY owns the center column:
//   • On the "storyboard" tab it injects the shared SessionChatView via a
//     `center-session` slot, with an optional compact "context strip" rendered
//     above the chat when a scene/output is selected.
//   • On the other tabs it renders simple placeholder content (overview /
//     timeline / etc.) so the page can drop in richer views later without
//     re-plumbing layout.
//
// Left and right columns are NOT owned by this component — they live in
// dedicated panels (ProjectWorkspaceLeftPanel, ProjectWorkspaceRightPanel)
// that the page composes into the surrounding UILayout. This component only
// provides the center column so it can be slotted into the
// UILayoutPageContainer inside ProjectWorkspacePage.
//
// Active tab state is owned here (and exposed for parent code that needs to
// force-jump to a specific tab, e.g. when picking a session in the left
// drawer). The page forwards the shared top bar's tab-change event here.

<template>
  <div class="project-workspace-grid" role="region" :aria-label="centerAriaLabel">
    <!-- Ambient backdrop — matches PageShell orbs but dimmer to not fight the columns -->
    <div class="grid-ambient" aria-hidden="true">
      <div class="grid-ambient__orb grid-ambient__orb--cyan" />
      <div class="grid-ambient__orb grid-ambient__orb--violet" />
      <div class="grid-ambient__ambient-grid" />
    </div>

    <!-- ── Center column ────────────────────────────────────────────── -->
    <section class="grid-center" role="main" :aria-label="centerAriaLabel">
      <!--
        storyboard tab — context strip + (injected) SessionChatView.
        The chat is the main creative surface; the strip above shows
        the currently-selected scene/output as a compact preview.
      -->
      <template v-if="activeWorkspaceTab === 'storyboard'">
        <div class="center-stack">
          <div v-if="$slots['context-strip']" class="center-stack__context">
            <slot name="context-strip" />
          </div>
          <div class="center-stack__chat">
            <slot name="center-session">
              <div class="center-session-empty" :aria-busy="isAssistantBusy">
                <div class="center-session-empty__art" aria-hidden="true">
                  <div class="center-session-empty__ring" />
                  <q-icon name="forum" size="28px" color="grey-6" />
                </div>
                <div class="center-session-empty__title">选择左侧场景或会话</div>
                <div class="center-session-empty__hint">
                  在左侧选择一个场景，或创建新会话开始对话。
                </div>
              </div>
            </slot>
          </div>
        </div>
      </template>

      <!--
        Other tabs — render simple placeholder panes so the layout stays
        stable. Coder may replace these with richer content per tab.
      -->
      <div v-else-if="activeWorkspaceTab === 'overview'" class="tab-pane tab-pane--overview">
        <header class="tab-pane__header">
          <h2 class="tab-pane__title">项目概览</h2>
          <p class="tab-pane__subtitle">{{ projectName }} 的整体状态与最近活动</p>
        </header>
        <div class="overview-metrics">
          <div class="overview-metric">
            <div class="overview-metric__value">{{ sessionCount ?? 0 }}</div>
            <div class="overview-metric__label">会话</div>
          </div>
          <div class="overview-metric">
            <div class="overview-metric__value">{{ outputs.length }}</div>
            <div class="overview-metric__label">产出</div>
          </div>
          <div class="overview-metric">
            <div class="overview-metric__value">{{ elementCount }}</div>
            <div class="overview-metric__label">故事元素</div>
          </div>
          <div class="overview-metric">
            <div class="overview-metric__value">{{ fileCount }}</div>
            <div class="overview-metric__label">文件</div>
          </div>
        </div>
      </div>

      <div v-else-if="activeWorkspaceTab === 'timeline'" class="tab-pane tab-pane--placeholder">
        <q-icon name="schedule" size="28px" color="grey-6" />
        <div class="tab-pane__title">时间线</div>
        <div class="tab-pane__hint">该模块正在开发中，敬请期待</div>
      </div>

      <div v-else-if="activeWorkspaceTab === 'exports'" class="tab-pane tab-pane--placeholder">
        <q-icon name="ios_share" size="28px" color="grey-6" />
        <div class="tab-pane__title">导出记录</div>
        <div class="tab-pane__hint">该模块正在开发中，敬请期待</div>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'

import type { ShotOutputItem, StoryElement, WorkspaceTabId } from './types'

// ── Props ────────────────────────────────────────────────────────────────────

const props = withDefaults(
  defineProps<{
    projectName: string
    projectStatus?: 'active' | 'archived'
    outputs?: ShotOutputItem[]
    storyElements?: StoryElement[]
    sessionCount?: number | null
    fileCount?: number
    isAssistantBusy?: boolean
  }>(),
  {
    projectStatus: 'active',
    outputs: () => [],
    storyElements: () => [],
    sessionCount: null,
    fileCount: 0,
    isAssistantBusy: false,
  },
)

const emit = defineEmits<{
  (e: 'workspace-tab-change', tab: WorkspaceTabId): void
}>()

// ── Local state ──────────────────────────────────────────────────────────────

const activeWorkspaceTab = ref<WorkspaceTabId>('storyboard')

// Map the active tab to an a11y-friendly label for the center region.
const centerAriaLabel = computed<string>(() => {
  switch (activeWorkspaceTab.value) {
    case 'overview':  return '项目概览'
    case 'storyboard': return '故事板工作区'
    case 'timeline':  return '项目时间线'
    case 'edit':      return '剪辑工作区'
    case 'audio':     return '音频工作区'
    case 'exports':   return '导出记录'
    default:          return '项目工作区'
  }
})

// ── Derived ──────────────────────────────────────────────────────────────────

const elementCount = computed(() => props.storyElements.length)

// ── Expose for parent integration ───────────────────────────────────────────

// Used to switch tabs from page-level events (e.g. picking a session jumps
// to the storyboard tab so the chat is visible in the center column).
defineExpose({
  setActiveWorkspaceTab: (tab: WorkspaceTabId) => {
    activeWorkspaceTab.value = tab
    emit('workspace-tab-change', tab)
  },
  getActiveWorkspaceTab: () => activeWorkspaceTab.value,
})
</script>

<style lang="scss" scoped>
.project-workspace-grid {
  position: relative;
  display: flex;
  flex-direction: column;
  width: 100%;
  min-height: 0;
  flex: 1 1 auto;
  background: var(--imago-bg-void);
  color: var(--imago-text-primary);
  isolation: isolate; // keep the ambient orbs behind the content
}

// ── Ambient backdrop ─────────────────────────────────────────────────────
.grid-ambient {
  position: absolute;
  inset: 0;
  pointer-events: none;
  z-index: 0;
  overflow: hidden;
}

.grid-ambient__orb {
  position: absolute;
  border-radius: 50%;
  filter: blur(90px);
  opacity: 0.3;
  animation: orb-drift 20s ease-in-out infinite;
}

.grid-ambient__orb--cyan {
  top: -80px;
  left: 18%;
  width: 380px;
  height: 380px;
  background: radial-gradient(circle, rgba(0, 240, 255, 0.10), transparent 65%);
}

.grid-ambient__orb--violet {
  bottom: -120px;
  right: 12%;
  width: 460px;
  height: 460px;
  background: radial-gradient(circle, rgba(168, 85, 247, 0.10), transparent 65%);
  animation-delay: -8s;
}

.grid-ambient__ambient-grid {
  position: absolute;
  inset: 0;
  background-image:
    linear-gradient(rgba(255, 255, 255, 0.018) 1px, transparent 1px),
    linear-gradient(90deg, rgba(255, 255, 255, 0.018) 1px, transparent 1px);
  background-size: 56px 56px;
  mask-image: radial-gradient(ellipse at center, black 30%, transparent 75%);
}

@keyframes orb-drift {
  0%, 100% { transform: translate(0, 0); }
  50% { transform: translate(20px, -10px); }
}

// ── Center column ────────────────────────────────────────────────────────
.grid-center {
  position: relative;
  z-index: 1;
  flex: 1 1 auto;
  min-height: 0;
  display: flex;
  flex-direction: column;
  background: var(--imago-bg-void);
  overflow: hidden;
}

.center-stack {
  flex: 1 1 auto;
  min-height: 0;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.center-stack__context {
  flex-shrink: 0;
  padding: 12px 24px 0;
}

.center-stack__chat {
  flex: 1 1 auto;
  min-height: 0;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

// ── Overview pane ────────────────────────────────────────────────────────
.tab-pane {
  flex: 1 1 auto;
  min-height: 0;
  overflow-y: auto;
  padding: 24px 28px 32px;
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.tab-pane--placeholder {
  align-items: center;
  justify-content: center;
  text-align: center;
  color: var(--imago-text-faint);
  font-size: 13px;
  gap: 8px;
  padding: 60px 24px;
}

.tab-pane--placeholder .tab-pane__title {
  font-size: 16px;
  font-weight: 600;
  color: var(--imago-text-secondary);
}

.tab-pane--placeholder .tab-pane__hint {
  font-size: 12.5px;
  color: var(--imago-text-faint);
}

.tab-pane__header {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.tab-pane__title {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
  color: var(--imago-text-primary);
  letter-spacing: 0.005em;
}

.tab-pane__subtitle {
  margin: 0;
  font-size: 12.5px;
  color: var(--imago-text-dim);
}

.overview-metrics {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 10px;
}

.overview-metric {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 14px 16px;
  border: 1px solid var(--imago-border-soft);
  border-radius: 12px;
  background: var(--imago-bg-surface);
}

.overview-metric__value {
  font-size: 24px;
  font-weight: 600;
  color: var(--imago-text-primary);
  font-variant-numeric: tabular-nums;
  line-height: 1.1;
}

.overview-metric__label {
  font-size: 11px;
  color: var(--imago-text-faint);
  letter-spacing: 0.04em;
  text-transform: uppercase;
}

// ── Empty / placeholder ─────────────────────────────────────────────────

.center-session-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  flex: 1 1 auto;
  text-align: center;
  padding: 24px;
  gap: 16px;
  color: var(--imago-text-dim);
}

.center-session-empty__art {
  position: relative;
  width: 96px;
  height: 96px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.center-session-empty__ring {
  position: absolute;
  inset: 0;
  border-radius: 50%;
  border: 1.5px solid var(--imago-border-cyan);
  animation: logo-spin 8s linear infinite;
}

.center-session-empty__title {
  font-size: 16px;
  font-weight: 600;
  color: var(--imago-text-primary);
}

.center-session-empty__hint {
  font-size: 12.5px;
  color: var(--imago-text-faint);
  max-width: 360px;
  line-height: 1.5;
}

@keyframes logo-spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

@media (max-width: 1024px) {
  .overview-metrics {
    grid-template-columns: repeat(2, 1fr);
  }
}
</style>
