<!--
  DESIGN SPEC — generated by Designer agent
  Coder: implement TODO items, do not change component structure or accessibility attributes.

  ProjectWorkspaceLeftPanel
  ─────────────────────────
  Left drawer content for the redesigned project workspace ("故事板"). Replaces the
  former flat scene-card list with a THREE-SECTION COLLAPSIBLE ACCORDION:

    1. 关键元素 (Key Elements)     — character + scene element cards
    2. 分镜 (Shots)                — shot cards (video + audio media)
    3. 旁白与音乐 (Narration & Music) — audio cards

  Each section has a centered "·· 关键元素 ··" style label that doubles as the
  collapse toggle (a <button> with aria-expanded + a chevron on the right). Collapse
  state lives IN MEMORY only (sectionOpen ref) and is NOT persisted; all three start
  expanded.

  This component is purely presentational + emits. Data mapping, fetching, and all
  business logic are bd-C's job — every such site is a TODO comment, not an impl.

  NOTE: banner is an HTML comment (NOT `//` lines) on purpose — `//` before <template>
  crashes Vite HMR.
-->

<template>
  <aside class="left-panel" aria-label="项目故事板">
    <!-- ── Header ────────────────────────────────────────────────── -->
    <header class="left-panel__header">
      <div class="left-panel__title-block">
        <h2 class="left-panel__title">故事板</h2>
        <p class="left-panel__subtitle">{{ summaryLabel }}</p>
      </div>
      <div class="left-panel__header-actions">
        <button
          type="button"
          class="left-panel__icon-btn"
          :class="{ 'left-panel__icon-btn--active': viewDensity === 'grid' }"
          aria-label="网格视图"
          @click="emit('view-change', 'grid')"
        >
          <OiIcon name="grid-2x2" :size="14" />
        </button>
        <button
          type="button"
          class="left-panel__icon-btn"
          :class="{ 'left-panel__icon-btn--active': viewDensity === 'list' }"
          aria-label="列表视图"
          @click="emit('view-change', 'list')"
        >
          <OiIcon name="list-bullet" :size="14" />
        </button>
      </div>
    </header>

    <!-- ── Accordion ─────────────────────────────────────────────── -->
    <div class="left-panel__scroll">
      <!-- ── Section 1: 关键元素 ─────────────────────────────────── -->
      <section class="accordion" aria-labelledby="accordion-elements-label">
        <h3 id="accordion-elements-label" class="accordion__heading">
          <button
            type="button"
            class="accordion__toggle"
            :aria-expanded="sectionOpen.elements"
            aria-controls="accordion-elements-body"
            @click="toggleSection('elements')"
          >
            <span class="accordion__label">·· 关键元素 ··</span>
            <OiIcon
              name="chevron-down"
              :size="14"
              class="accordion__chevron"
              :class="{ 'accordion__chevron--collapsed': !sectionOpen.elements }"
            />
          </button>
        </h3>

        <div
          v-show="sectionOpen.elements"
          id="accordion-elements-body"
          class="accordion__body"
        >
          <ul v-if="elements.length > 0" class="card-list">
            <li v-for="element in elements" :key="element.id">
              <ElementCard
                :element="element"
                :active="element.id === selectedId"
                :read-only="readOnly"
                :collapsed="isCardCollapsed(element.id)"
                @select="onItemSelect"
                @toggle="toggleCard"
                @add-media="onAddMedia('elements', $event)"
                @select-type="onSelectType('elements', $event)"
                @generate="onCommentGenerate('elements', $event)"
              />
            </li>
          </ul>
          <p v-else class="accordion__empty">暂无关键元素</p>
        </div>
      </section>

      <!-- ── Section 2: 分镜 ─────────────────────────────────────── -->
      <section class="accordion" aria-labelledby="accordion-shots-label">
        <h3 id="accordion-shots-label" class="accordion__heading">
          <button
            type="button"
            class="accordion__toggle"
            :aria-expanded="sectionOpen.shots"
            aria-controls="accordion-shots-body"
            @click="toggleSection('shots')"
          >
            <span class="accordion__label">·· 分镜 ··</span>
            <OiIcon
              name="chevron-down"
              :size="14"
              class="accordion__chevron"
              :class="{ 'accordion__chevron--collapsed': !sectionOpen.shots }"
            />
          </button>
        </h3>

        <div
          v-show="sectionOpen.shots"
          id="accordion-shots-body"
          class="accordion__body"
        >
          <ul v-if="shots.length > 0" class="card-list">
            <li v-for="shot in shots" :key="shot.id">
              <ShotCard
                :shot="shot"
                :active="shot.id === selectedId"
                :read-only="readOnly"
                :collapsed="isCardCollapsed(shot.id)"
                @select="onItemSelect"
                @toggle="toggleCard"
                @select-type="onSelectType('shots', $event)"
                @generate="onCommentGenerate('shots', $event)"
              />
            </li>
          </ul>
          <p v-else class="accordion__empty">暂无分镜</p>
        </div>
      </section>

      <!-- ── Section 3: 旁白与音乐 ───────────────────────────────── -->
      <section class="accordion" aria-labelledby="accordion-audio-label">
        <h3 id="accordion-audio-label" class="accordion__heading">
          <button
            type="button"
            class="accordion__toggle"
            :aria-expanded="sectionOpen.audio"
            aria-controls="accordion-audio-body"
            @click="toggleSection('audio')"
          >
            <span class="accordion__label">·· 旁白与音乐 ··</span>
            <OiIcon
              name="chevron-down"
              :size="14"
              class="accordion__chevron"
              :class="{ 'accordion__chevron--collapsed': !sectionOpen.audio }"
            />
          </button>
        </h3>

        <div
          v-show="sectionOpen.audio"
          id="accordion-audio-body"
          class="accordion__body"
        >
          <ul v-if="audio.length > 0" class="card-list">
            <li v-for="track in audio" :key="track.id">
              <AudioCard
                :track="track"
                :active="track.id === selectedId"
                :read-only="readOnly"
                :collapsed="isCardCollapsed(track.id)"
                @select="onItemSelect"
                @toggle="toggleCard"
                @add-media="onAddMedia('audio', $event)"
                @select-type="onSelectType('audio', $event)"
                @generate="onCommentGenerate('audio', $event)"
              />
            </li>
          </ul>
          <p v-else class="accordion__empty">暂无旁白与音乐</p>
        </div>
      </section>
    </div>

    <!-- ── Footer: add element button ────────────────────────────── -->
    <footer v-if="!readOnly || editable" class="left-panel__footer">
      <button
        type="button"
        class="left-panel__add-scene"
        @click="emit('add')"
      >
        <OiIcon name="plus" :size="14" />
        <span>添加场景</span>
      </button>
    </footer>
  </aside>
</template>

<script setup lang="ts">
import { computed, reactive } from 'vue'
import OiIcon from 'src/components/ui/OiIcon.vue'
import ElementCard from './left-panel/ElementCard.vue'
import ShotCard from './left-panel/ShotCard.vue'
import AudioCard from './left-panel/AudioCard.vue'
import type {
  ElementCardVM,
  ShotCardVM,
  AudioCardVM,
  LeftPanelSection,
} from './left-panel/types'

// ── Props ────────────────────────────────────────────────────────────────────

const props = withDefaults(defineProps<{
  elements: ElementCardVM[]
  shots: ShotCardVM[]
  audio: AudioCardVM[]
  /** Currently selected item id across all three sections. */
  selectedId?: string | null
  viewDensity?: 'grid' | 'list'
  /** When true, hides all write affordances (add, add-media, type selector). */
  readOnly?: boolean
  /** Opt-in: show write affordances even while readOnly (ADR 0005 first write). */
  editable?: boolean
}>(), {
  elements: () => [],
  shots: () => [],
  audio: () => [],
  selectedId: null,
  viewDensity: 'grid',
  readOnly: false,
  editable: false,
})

const emit = defineEmits<{
  /** A card was clicked/selected (replaces the former scene-select). */
  (e: 'item-select', id: string): void
  /** Footer "添加场景" pressed (replaces the former add-scene). */
  (e: 'add'): void
  /** View density toggle. */
  (e: 'view-change', density: 'grid' | 'list'): void
  /** A section header was toggled (collapse state is in-memory; emit for analytics/sync). */
  (e: 'section-toggle', section: LeftPanelSection): void
  /** "+" add-media button on a card footer. */
  (e: 'item-add-media', section: LeftPanelSection, id: string): void
  /** "评论生成" button on a card footer. */
  (e: 'comment-generate', section: LeftPanelSection, id: string): void
  /** Type-selector button ("图片 ▾" / "最终镜头 ▾" / "最终音频 ▾"). */
  (e: 'item-select-type', section: LeftPanelSection, id: string): void
}>()

// ── Header summary ───────────────────────────────────────────────────────────

const summaryLabel = computed(
  () => `${props.elements.length} 元素 · ${props.shots.length} 分镜 · ${props.audio.length} 音轨`,
)

// ── Section collapse (in-memory only, NOT persisted; all start expanded) ───────

const sectionOpen = reactive<Record<LeftPanelSection, boolean>>({
  elements: true,
  shots: true,
  audio: true,
})

function toggleSection(section: LeftPanelSection): void {
  sectionOpen[section] = !sectionOpen[section]
  emit('section-toggle', section)
}

// ── Per-card collapse (in-memory only; cards start expanded) ──────────────────

const collapsedCards = reactive<Record<string, boolean>>({})

function isCardCollapsed(id: string): boolean {
  return collapsedCards[id] === true
}

function toggleCard(id: string): void {
  collapsedCards[id] = !collapsedCards[id]
}

// ── Card event relays ────────────────────────────────────────────────────────

function onItemSelect(id: string): void {
  emit('item-select', id)
}

function onAddMedia(section: LeftPanelSection, id: string): void {
  emit('item-add-media', section, id)
}

function onSelectType(section: LeftPanelSection, id: string): void {
  emit('item-select-type', section, id)
}

function onCommentGenerate(section: LeftPanelSection, id: string): void {
  emit('comment-generate', section, id)
}
</script>

<style lang="scss" scoped>
.left-panel {
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
  min-height: 0;
  background: linear-gradient(180deg, var(--imago-bg-deep), var(--imago-bg-void) 40%);
}

// ── Header ──────────────────────────────────────────────────────────────────

.left-panel__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 18px 18px 12px;
  flex-shrink: 0;
}

.left-panel__title-block {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.left-panel__title {
  margin: 0;
  font-size: 14px;
  font-weight: 600;
  color: var(--imago-text-primary);
  letter-spacing: 0.005em;
}

.left-panel__subtitle {
  margin: 0;
  font-size: 11.5px;
  color: var(--imago-text-dim);
}

.left-panel__header-actions {
  display: inline-flex;
  align-items: center;
  gap: 2px;
  padding: 3px;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-pill);
  background: var(--imago-bg-surface);
  flex-shrink: 0;
}

.left-panel__icon-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 24px;
  padding: 0;
  border: 0;
  border-radius: var(--imago-radius-pill);
  background: transparent;
  color: var(--imago-text-muted);
  cursor: pointer;
  transition: color 120ms ease, background 120ms ease;
}

.left-panel__icon-btn:hover {
  color: var(--imago-text-primary);
  background: var(--imago-cyan-06);
}

.left-panel__icon-btn--active {
  color: var(--imago-neon-cyan);
  background: var(--imago-cyan-08);
}

// ── Scroll area ─────────────────────────────────────────────────────────────

.left-panel__scroll {
  flex: 1 1 auto;
  min-height: 0;
  overflow-y: auto;
  padding: 0 14px 12px;
  display: flex;
  flex-direction: column;
  gap: 6px;
}

// ── Accordion section ─────────────────────────────────────────────────────────

.accordion {
  display: flex;
  flex-direction: column;
}

.accordion__heading {
  margin: 0;
  position: sticky;
  top: 0;
  z-index: 1;
  background: var(--imago-bg-void);
}

.accordion__toggle {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  width: 100%;
  padding: 10px 6px;
  border: 0;
  background: transparent;
  cursor: pointer;
  color: var(--imago-text-secondary);
  transition: color 120ms ease;
}

.accordion__toggle:hover {
  color: var(--imago-text-primary);
}

.accordion__toggle:focus-visible {
  outline: 2px solid var(--imago-border-cyan-active);
  outline-offset: 2px;
  border-radius: var(--imago-radius-sm);
}

.accordion__label {
  font-size: 12px;
  font-weight: 600;
  letter-spacing: 0.14em;
}

.accordion__chevron {
  color: var(--imago-text-muted);
  transition: transform 160ms var(--imago-ease-default, ease);
}

.accordion__chevron--collapsed {
  transform: rotate(-90deg);
}

@media (prefers-reduced-motion: reduce) {
  .accordion__chevron { transition: none; }
}

.accordion__body {
  padding-bottom: 8px;
}

.accordion__empty {
  margin: 0;
  padding: 18px 12px;
  text-align: center;
  font-size: 11.5px;
  color: var(--imago-text-faint);
  border: 1px dashed var(--imago-border-soft);
  border-radius: var(--imago-radius-lg);
}

.card-list {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

// ── Footer ──────────────────────────────────────────────────────────────────

.left-panel__footer {
  flex-shrink: 0;
  padding: 10px 14px 14px;
  border-top: 1px solid var(--imago-border-light);
}

.left-panel__add-scene {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  width: 100%;
  padding: 10px 12px;
  border: 1px dashed var(--imago-border-cyan);
  border-radius: var(--imago-radius-md);
  background: transparent;
  color: var(--imago-text-secondary);
  font-size: 12.5px;
  font-weight: 500;
  cursor: pointer;
  transition: color 120ms ease, border-color 120ms ease, background 120ms ease;
}

.left-panel__add-scene:hover {
  color: var(--imago-neon-cyan);
  border-color: var(--imago-border-cyan-active);
  background: var(--imago-cyan-06);
}
</style>
