// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change component structure or accessibility attributes
//
// ProjectWorkspaceRightPanel
// ──────────────────────────
// Right drawer content for the redesigned project workspace. After the
// redesign the panel is structurally identical to the session workspace's
// right side — it surfaces project-level AI generation outputs in a 2-column
// grid. This component is now a thin pass-through to the shared
// AIOutputsPanel, with project-specific copy + a "view all" link.
//
// Renders into a UILayoutDrawer side="right" slot on ProjectWorkspacePage.
// All state is owned by the parent (page) — this component is purely
// presentational + emits.

<template>
  <AIOutputsPanel
    :title="'AI 产出'"
    :subtitle="`项目 ${projectName || ''} 的全部生成结果`"
    :empty-title="'AI 生成的结果将出现在这里'"
    :empty-hint="'在中央创作面板描述你想要的画面，AI 产出将自动汇总于此'"
    :items="items"
    :selected-id="selectedId"
    :layout="layout"
    :show-view-all="showViewAll"
    :view-all-label="'查看全部'"
    :aria-label="'项目 AI 产出面板'"
    @item-select="(id) => emit('item-select', id)"
    @item-menu="(id, ev) => emit('item-menu', id, ev)"
    @layout-change="(l) => emit('layout-change', l)"
    @filter="emit('filter')"
    @view-all="emit('view-all')"
  />
</template>

<script setup lang="ts">
import AIOutputsPanel from 'src/components/workspace/AIOutputsPanel.vue'
import type { AIOutputItem } from 'src/components/session-workspace/types'

withDefaults(defineProps<{
  items: AIOutputItem[]
  selectedId?: string | null
  layout?: 'grid' | 'rows'
  showViewAll?: boolean
  projectName?: string
}>(), {
  selectedId: null,
  layout: 'grid',
  showViewAll: false,
  projectName: '',
})

const emit = defineEmits<{
  (e: 'item-select', id: string): void
  (e: 'item-menu', id: string, event: MouseEvent): void
  (e: 'layout-change', layout: 'grid' | 'rows'): void
  (e: 'filter'): void
  (e: 'view-all'): void
}>()
</script>
