// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change component structure or accessibility attributes
//
// ProjectWorkspaceLeftPanel
// ─────────────────────────
// Left drawer content for the redesigned project workspace. Hosts the
// storyboard scene cards exactly as shown in the approved mockup
// (docs/images/project_worksapce.png): a header with "故事板" + a
// view-density toggle, followed by vertical scene cards, and a "+ 添加场景"
// button at the bottom.
//
// Each scene card surfaces the scene index, title, one-line description, a
// row of reference thumbnails, and an "图片 ▾" / "+ 添加" footer.
//
// All state is owned by the parent (page) — this component is purely
// presentational + emits. Rendering targets a UILayoutDrawer side="left"
// slot, matching the same pattern as SessionWorkspaceSidebar.

<template>
  <aside class="left-panel" :aria-label="'项目故事板'">
    <!-- ── Header ────────────────────────────────────────────────── -->
    <header class="left-panel__header">
      <div class="left-panel__title-block">
        <h2 class="left-panel__title">故事板</h2>
        <p class="left-panel__subtitle">{{ scenes.length }} 个场景</p>
      </div>
      <div class="left-panel__header-actions">
        <button
          type="button"
          class="left-panel__icon-btn"
          :class="{ 'left-panel__icon-btn--active': viewDensity === 'grid' }"
          aria-label="网格视图"
          @click="emit('view-change', 'grid')"
        >
          <OiIcon name="grid-2x2" :size="14" />
        </button>
        <button
          type="button"
          class="left-panel__icon-btn"
          :class="{ 'left-panel__icon-btn--active': viewDensity === 'list' }"
          aria-label="列表视图"
          @click="emit('view-change', 'list')"
        >
          <OiIcon name="list-bullet" :size="14" />
        </button>
      </div>
    </header>

    <!-- ── Scene cards ────────────────────────────────────────────── -->
    <div class="left-panel__scroll">
      <ol v-if="scenes.length > 0" class="left-panel__list">
        <li
          v-for="(scene, index) in scenes"
          :key="scene.id"
          class="scene-card"
          :class="{
            'scene-card--active': scene.id === selectedId,
          }"
        >
          <button
            type="button"
            class="scene-card__head"
            :aria-pressed="scene.id === selectedId"
            :aria-label="`选择 ${scene.title}`"
            @click="emit('scene-select', scene.id)"
          >
            <span class="scene-card__index" aria-hidden="true">
              {{ String(index + 1).padStart(2, '0') }}
            </span>
            <span class="scene-card__title ellipsis">{{ scene.title }}</span>
            <span v-if="scene.id === selectedId" class="scene-card__check" aria-hidden="true">
              <OiIcon name="check" :size="14" />
            </span>
          </button>
          <p v-if="scene.description" class="scene-card__description ellipsis-2">
            {{ scene.description }}
          </p>
          <div class="scene-card__thumbs" :aria-label="`${scene.title} 缩略图`">
            <div
              v-for="(thumb, thumbIndex) in scene.thumbnails"
              :key="thumbIndex"
              class="scene-card__thumb"
              :aria-hidden="true"
            >
              <img
                v-if="thumb"
                :src="thumb"
                :alt="''"
                class="scene-card__thumb-image"
                loading="lazy"
              >
              <span v-else class="scene-card__thumb-fallback">
                <OiIcon name="image-card" :size="14" />
              </span>
            </div>
            <button
              v-if="!readOnly"
              type="button"
              class="scene-card__thumb scene-card__thumb--add"
              :aria-label="`为 ${scene.title} 添加图片`"
              @click.stop="emit('scene-add-image', scene.id)"
            >
              <OiIcon name="plus" :size="14" />
            </button>
          </div>
          <div v-if="!readOnly" class="scene-card__footer">
            <button
              type="button"
              class="scene-card__select"
              :aria-haspopup="true"
              @click.stop="emit('scene-image-type', scene.id)"
            >
              <span>{{ scene.imageTypeLabel ?? '图片' }}</span>
              <OiIcon name="chevron-down" :size="12" />
            </button>
            <button
              type="button"
              class="scene-card__add"
              @click.stop="emit('scene-add', scene.id)"
            >
              <OiIcon name="plus" :size="12" />
              <span>添加</span>
            </button>
          </div>

          <!-- Generate action (ADR 0005). Available in read-only mode only when
               shot generation is explicitly enabled; per-card loading state. -->
          <div v-if="canGenerate" class="scene-card__generate">
            <button
              type="button"
              class="scene-card__generate-btn"
              :disabled="generatingIds.includes(scene.id)"
              :aria-busy="generatingIds.includes(scene.id)"
              :aria-label="`为 ${scene.title} 生成关键帧`"
              @click.stop="emit('scene-generate', scene.id)"
            >
              <OiIcon
                name="enhance-wave"
                :size="12"
                :class="{ 'scene-card__spin': generatingIds.includes(scene.id) }"
              />
              <span>{{ generatingIds.includes(scene.id) ? '生成中…' : '生成' }}</span>
            </button>
          </div>
        </li>
      </ol>

      <div v-else class="left-panel__empty">
        <q-icon name="movie_filter" size="22px" color="grey-6" />
        <p class="left-panel__empty-title">暂无场景</p>
        <p class="left-panel__empty-hint">点击下方按钮创建第一个故事场景</p>
      </div>
    </div>

    <!-- ── Footer: add scene button ──────────────────────────────── -->
    <!-- Shown when fully editable, OR when read-only but shot-adding is
         explicitly enabled (ADR 0005 first write). Other write buttons
         stay hidden under readOnly. -->
    <footer v-if="!readOnly || canAddShot" class="left-panel__footer">
      <button
        type="button"
        class="left-panel__add-scene"
        @click="emit('add-scene')"
      >
        <OiIcon name="plus" :size="14" />
        <span>添加场景</span>
      </button>
    </footer>
  </aside>
</template>

<script setup lang="ts">
import OiIcon from 'src/components/ui/OiIcon.vue'

// ── Public shape ────────────────────────────────────────────────────────────

export interface StoryboardScene {
  id: string
  title: string
  description?: string
  thumbnails: ReadonlyArray<string | null>
  imageTypeLabel?: string
}

// ── Props ────────────────────────────────────────────────────────────────────

withDefaults(defineProps<{
  scenes: StoryboardScene[]
  selectedId?: string | null
  viewDensity?: 'grid' | 'list'
  /** When true, hides all write affordances (add scene/image, image-type). */
  readOnly?: boolean
  /**
   * Opt-in: show the footer "添加场景" button even while readOnly, enabling the
   * single supported write (append a shot, ADR 0005). Other write buttons stay
   * hidden under readOnly.
   */
  canAddShot?: boolean
  /**
   * Opt-in: show the per-card "生成" action (mock keyframe generation, ADR
   * 0005), independent of the other write affordances.
   */
  canGenerate?: boolean
  /** Shot ids currently generating — drives per-card loading state. */
  generatingIds?: ReadonlyArray<string>
}>(), {
  selectedId: null,
  viewDensity: 'grid',
  readOnly: false,
  canAddShot: false,
  canGenerate: false,
  generatingIds: () => [],
})

const emit = defineEmits<{
  (e: 'scene-select', id: string): void
  (e: 'scene-add-image', id: string): void
  (e: 'scene-add', id: string): void
  (e: 'scene-image-type', id: string): void
  (e: 'scene-generate', id: string): void
  (e: 'add-scene'): void
  (e: 'view-change', density: 'grid' | 'list'): void
}>()
</script>

<style lang="scss" scoped>
.left-panel {
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
  min-height: 0;
  background: linear-gradient(180deg, var(--imago-bg-deep), var(--imago-bg-void) 40%);
}

// ── Header ──────────────────────────────────────────────────────────────────

.left-panel__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 18px 18px 12px;
  flex-shrink: 0;
}

.left-panel__title-block {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.left-panel__title {
  margin: 0;
  font-size: 14px;
  font-weight: 600;
  color: var(--imago-text-primary);
  letter-spacing: 0.005em;
}

.left-panel__subtitle {
  margin: 0;
  font-size: 11.5px;
  color: var(--imago-text-dim);
}

.left-panel__header-actions {
  display: inline-flex;
  align-items: center;
  gap: 2px;
  padding: 3px;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-pill);
  background: var(--imago-bg-surface);
  flex-shrink: 0;
}

.left-panel__icon-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 24px;
  padding: 0;
  border: 0;
  border-radius: var(--imago-radius-pill);
  background: transparent;
  color: var(--imago-text-muted);
  cursor: pointer;
  transition: color 120ms ease, background 120ms ease;
}

.left-panel__icon-btn:hover {
  color: var(--imago-text-primary);
  background: var(--imago-cyan-06);
}

.left-panel__icon-btn--active {
  color: var(--imago-neon-cyan);
  background: var(--imago-cyan-08);
}

// ── Scroll area ─────────────────────────────────────────────────────────────

.left-panel__scroll {
  flex: 1 1 auto;
  min-height: 0;
  overflow-y: auto;
  padding: 0 14px 12px;
}

.left-panel__list {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

// ── Scene card ──────────────────────────────────────────────────────────────

.scene-card {
  display: flex;
  flex-direction: column;
  gap: 8px;
  padding: 12px;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-lg);
  background: var(--imago-bg-surface);
  transition: border-color 120ms ease, background 120ms ease, box-shadow 120ms ease;
}

.scene-card:hover {
  border-color: var(--imago-border-cyan);
}

.scene-card--active {
  border-color: var(--imago-border-cyan-active);
  background: var(--imago-cyan-04);
  box-shadow:
    inset 0 0 0 1px var(--imago-border-cyan-active),
    0 0 22px rgba(0, 240, 255, 0.08);
}

.scene-card__head {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 0;
  border: 0;
  background: transparent;
  text-align: left;
  cursor: pointer;
  min-width: 0;
  width: 100%;
}

.scene-card__index {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 22px;
  height: 22px;
  padding: 0 6px;
  border-radius: var(--imago-radius-sm);
  background: var(--imago-bg-raised);
  color: var(--imago-text-secondary);
  font-size: 10.5px;
  font-weight: 600;
  font-variant-numeric: tabular-nums;
  flex-shrink: 0;
  letter-spacing: 0.04em;
}

.scene-card--active .scene-card__index {
  background: var(--imago-cyan-08);
  color: var(--imago-neon-cyan);
}

.scene-card__title {
  flex: 1 1 auto;
  font-size: 13px;
  font-weight: 600;
  color: var(--imago-text-primary);
  min-width: 0;
}

.scene-card__check {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  color: var(--imago-neon-cyan);
  flex-shrink: 0;
}

.scene-card__description {
  margin: 0;
  font-size: 11.5px;
  line-height: 1.45;
  color: var(--imago-text-muted);
}

.scene-card__thumbs {
  display: grid;
  grid-template-columns: repeat(5, minmax(0, 1fr));
  gap: 6px;
  margin-top: 2px;
}

.scene-card__thumb {
  position: relative;
  aspect-ratio: 1 / 1;
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-raised);
  border: 1px solid var(--imago-border-soft);
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--imago-text-faint);
  flex-shrink: 0;
}

.scene-card__thumb-image {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.scene-card__thumb-fallback {
  display: inline-flex;
  align-items: center;
  justify-content: center;
}

.scene-card__thumb--add {
  border-style: dashed;
  background: transparent;
  color: var(--imago-text-muted);
  cursor: pointer;
  transition: color 120ms ease, border-color 120ms ease, background 120ms ease;
}

.scene-card__thumb--add:hover {
  color: var(--imago-neon-cyan);
  border-color: var(--imago-border-cyan);
  background: var(--imago-cyan-06);
}

.scene-card__footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  margin-top: 2px;
}

.scene-card__select {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  padding: 4px 10px;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-md);
  background: transparent;
  color: var(--imago-text-secondary);
  font-size: 11.5px;
  cursor: pointer;
  transition: color 120ms ease, border-color 120ms ease, background 120ms ease;
}

.scene-card__select:hover {
  color: var(--imago-text-primary);
  border-color: var(--imago-border-cyan);
  background: var(--imago-cyan-06);
}

.scene-card__add {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  padding: 4px 10px;
  border: 0;
  background: transparent;
  color: var(--imago-text-muted);
  font-size: 11.5px;
  cursor: pointer;
  border-radius: var(--imago-radius-md);
  transition: color 120ms ease, background 120ms ease;
}

.scene-card__add:hover {
  color: var(--imago-neon-cyan);
  background: var(--imago-cyan-06);
}

// ── Generate action ───────────────────────────────────────────────────────────

.scene-card__generate {
  display: flex;
}

.scene-card__generate-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 5px;
  width: 100%;
  padding: 6px 10px;
  border: 1px solid var(--imago-border-cyan);
  border-radius: var(--imago-radius-md);
  background: transparent;
  color: var(--imago-text-secondary);
  font-size: 11.5px;
  font-weight: 500;
  cursor: pointer;
  transition: color 120ms ease, border-color 120ms ease, background 120ms ease;
}

.scene-card__generate-btn:hover:not(:disabled) {
  color: var(--imago-neon-cyan);
  border-color: var(--imago-border-cyan-active);
  background: var(--imago-cyan-06);
}

.scene-card__generate-btn:disabled {
  opacity: 0.6;
  cursor: progress;
}

.scene-card__spin {
  animation: scene-card-spin 1s linear infinite;
}

@keyframes scene-card-spin {
  to { transform: rotate(360deg); }
}

@media (prefers-reduced-motion: reduce) {
  .scene-card__spin { animation: none; }
}

// ── Empty state ─────────────────────────────────────────────────────────────

.left-panel__empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 6px;
  padding: 30px 16px;
  border: 1px dashed var(--imago-border-soft);
  border-radius: var(--imago-radius-lg);
  text-align: center;
  color: var(--imago-text-faint);
}

.left-panel__empty-title {
  margin: 4px 0 0;
  font-size: 13px;
  color: var(--imago-text-secondary);
  font-weight: 600;
}

.left-panel__empty-hint {
  margin: 0;
  font-size: 11.5px;
  color: var(--imago-text-faint);
}

// ── Footer ──────────────────────────────────────────────────────────────────

.left-panel__footer {
  flex-shrink: 0;
  padding: 10px 14px 14px;
  border-top: 1px solid var(--imago-border-light);
}

.left-panel__add-scene {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  width: 100%;
  padding: 10px 12px;
  border: 1px dashed var(--imago-border-cyan);
  border-radius: var(--imago-radius-md);
  background: transparent;
  color: var(--imago-text-secondary);
  font-size: 12.5px;
  font-weight: 500;
  cursor: pointer;
  transition: color 120ms ease, border-color 120ms ease, background 120ms ease;
}

.left-panel__add-scene:hover {
  color: var(--imago-neon-cyan);
  border-color: var(--imago-border-cyan-active);
  background: var(--imago-cyan-06);
}

// ── Utility ──────────────────────────────────────────────────────────────────

.ellipsis {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.ellipsis-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>
