// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change component structure or accessibility attributes
<template>
  <div class="project-workspace-grid" role="region" :aria-label="`${projectName} 工作区`">
    <!-- Ambient backdrop — matches PageShell orbs but dimmer to not fight the three columns -->
    <div class="grid-ambient" aria-hidden="true">
      <div class="grid-ambient__orb grid-ambient__orb--cyan" />
      <div class="grid-ambient__orb grid-ambient__orb--violet" />
      <div class="grid-ambient__ambient-grid" />
    </div>

    <!-- ── Top command bar ──────────────────────────────────────────── -->
    <header class="command-bar" role="banner">
      <div class="command-bar__left">
        <button
          type="button"
          class="command-bar__back"
          aria-label="返回项目列表"
          @click="handleBack"
        >
          <q-icon name="arrow_back" size="18px" />
        </button>
        <div class="command-bar__title-block">
          <h1 class="command-bar__title">{{ projectName }}</h1>
          <div class="command-bar__meta">
            <span
              class="command-bar__status"
              :class="{ 'command-bar__status--archived': projectStatus === 'archived' }"
            >
              <span class="command-bar__status-dot" aria-hidden="true" />
              {{ projectStatus === 'archived' ? '已归档' : '进行中' }}
            </span>
            <span v-if="sessionCount != null" class="command-bar__meta-divider" aria-hidden="true">|</span>
            <span v-if="sessionCount != null" class="command-bar__meta-text">
              {{ sessionCount }} 个会话
            </span>
            <span v-if="outputCount != null" class="command-bar__meta-divider" aria-hidden="true">|</span>
            <span v-if="outputCount != null" class="command-bar__meta-text">
              {{ outputCount }} 个产出
            </span>
          </div>
        </div>
      </div>

      <!-- Workspace tab switcher — segmented control, full-width on mobile, auto-width on desktop -->
      <nav
        class="command-bar__tabs"
        role="tablist"
        aria-label="工作区主标签"
      >
        <button
          v-for="tab in WORKSPACE_TABS"
          :key="tab.id"
          type="button"
          role="tab"
          :id="`workspace-tab-${tab.id}`"
          :aria-selected="activeWorkspaceTab === tab.id"
          :aria-controls="`workspace-tabpanel-${tab.id}`"
          :tabindex="activeWorkspaceTab === tab.id ? 0 : -1"
          class="command-bar__tab"
          :class="{ 'command-bar__tab--active': activeWorkspaceTab === tab.id }"
          @click="handleWorkspaceTabSelect(tab.id)"
        >
          <q-icon v-if="tab.icon" :name="tab.icon" size="14px" class="command-bar__tab-icon" />
          <span>{{ tab.label }}</span>
        </button>
      </nav>

      <div class="command-bar__right">
        <button
          type="button"
          class="command-bar__action"
          aria-label="打开项目素材库"
          @click="handleOpenAssets"
        >
          <q-icon name="perm_media" size="16px" />
          <span class="command-bar__action-label">素材</span>
        </button>
        <button
          type="button"
          class="command-bar__action"
          aria-label="导出当前产出"
          @click="handleOpenExport"
        >
          <q-icon name="ios_share" size="16px" />
          <span class="command-bar__action-label">导出</span>
        </button>
        <div class="command-bar__credits" :aria-label="`项目余额 ${creditsLabel}`">
          <q-icon name="toll" size="14px" class="command-bar__credits-icon" />
          <span class="command-bar__credits-value">{{ creditsLabel }}</span>
        </div>
      </div>
    </header>

    <!-- ── Three-column grid body ───────────────────────────────────── -->
    <div class="grid-body" :class="`grid-body--tab-${activeWorkspaceTab}`">
      <!-- LEFT: 项目会话 (primary) + 故事元素 (secondary) ──────────── -->
      <aside
        class="grid-column grid-column--left"
        :aria-label="'项目会话与故事元素'"
        role="complementary"
      >
        <!-- ── Sessions: primary navigation ────────────────────────── -->
        <div class="grid-column__header">
          <div class="grid-column__title-block">
            <h2 class="grid-column__title">会话</h2>
            <p class="grid-column__subtitle">
              当前项目的对话与会话流
            </p>
          </div>
          <button
            type="button"
            class="grid-column__add session-create-btn"
            aria-label="新建会话"
            :disabled="isSessionSwitching"
            @click="handleSessionCreate"
          >
            <q-icon name="add" size="16px" />
          </button>
        </div>

        <!-- Session list -->
        <div class="session-list-panel">
          <div class="session-group">
            <div class="session-group__title">
              <span>会话流</span>
              <span class="session-group__count">{{ sessions.length }}</span>
            </div>

            <div v-if="sessions.length > 0" class="session-list">
              <button
                v-for="session in sessions"
                :key="session.id"
                type="button"
                class="session-card"
                :class="{ 'session-card--active': session.active }"
                :aria-pressed="session.active"
                :aria-label="`切换到会话 ${session.title}`"
                @click="handleSessionSelect(session.id)"
              >
                <div class="session-card__body">
                  <div class="session-card__row">
                    <div class="session-card__title ellipsis">{{ session.title }}</div>
                    <span class="session-card__time">{{ session.clockLabel }}</span>
                  </div>
                  <div v-if="session.preview" class="session-card__preview ellipsis-2">
                    {{ session.preview }}
                  </div>
                  <div class="session-card__meta">
                    <span class="session-card__meta-label">{{ session.meta }}</span>
                    <span class="session-card__meta-time">{{ session.timeLabel }}</span>
                  </div>
                </div>
              </button>
            </div>

            <div v-else class="session-list-empty">
              <q-icon name="forum" size="16px" color="grey-7" />
              <span>暂无会话 — 点击上方按钮创建一个</span>
            </div>
          </div>
        </div>

        <!-- ── Story elements: secondary section ────────────────────── -->
        <div class="elements-section">
          <div class="elements-section__header">
            <button
              type="button"
              class="elements-section__toggle"
              :aria-expanded="storyElementsExpanded"
              :aria-label="storyElementsExpanded ? '收起故事元素' : '展开故事元素'"
              @click="storyElementsExpanded = !storyElementsExpanded"
            >
              <div class="grid-column__title-block">
                <h3 class="grid-column__title">故事元素</h3>
                <p class="grid-column__subtitle">
                  {{ elementCount }} 个元素
                </p>
              </div>
              <q-icon
                :name="storyElementsExpanded ? 'expand_less' : 'expand_more'"
                size="16px"
                class="elements-section__toggle-icon"
              />
            </button>
            <button
              v-if="storyElementsExpanded"
              type="button"
              class="grid-column__add"
              aria-label="添加故事元素"
              @click="handleAddElement"
            >
              <q-icon name="add" size="16px" />
            </button>
          </div>

          <div v-if="storyElementsExpanded" class="elements-list">
            <section
              v-for="group in storyElementGroups"
              :key="group.id"
              class="element-group"
              :aria-label="group.label"
            >
              <header class="element-group__header">
                <div class="element-group__label-block">
                  <span class="element-group__label">{{ group.label }}</span>
                  <span class="element-group__count">{{ group.items.length }}</span>
                </div>
                <button
                  v-if="group.items.length > 0"
                  type="button"
                  class="element-group__add"
                  :aria-label="`在 ${group.label} 中添加`"
                  @click="handleAddToGroup(group.id)"
                >
                  <q-icon name="add" size="14px" />
                </button>
              </header>

              <div v-if="group.items.length > 0" class="element-group__items">
                <button
                  v-for="item in group.items"
                  :key="item.id"
                  type="button"
                  class="element-card"
                  :class="[
                    `element-card--${group.id}`,
                    { 'element-card--active': selectedElementId === item.id },
                  ]"
                  :aria-pressed="selectedElementId === item.id"
                  @click="handleElementSelect(item.id)"
                >
                  <div class="element-card__thumb" :aria-hidden="true">
                    <img
                      v-if="item.thumbnailUrl"
                      :src="item.thumbnailUrl"
                      :alt="''"
                      class="element-card__image"
                    >
                    <div v-else class="element-card__thumb-fallback">
                      <q-icon :name="group.icon" size="20px" color="grey-7" />
                    </div>
                    <span
                      v-if="item.syncState"
                      class="element-card__sync"
                      :class="`element-card__sync--${item.syncState}`"
                      :aria-label="syncLabel(item.syncState)"
                    >
                      <span class="element-card__sync-dot" />
                    </span>
                  </div>
                  <div class="element-card__body">
                    <div class="element-card__title ellipsis">{{ item.title || '未命名元素' }}</div>
                    <div v-if="item.preview" class="element-card__preview ellipsis-2">
                      {{ item.preview }}
                    </div>
                    <div class="element-card__meta">
                      <span class="element-card__meta-kind">{{ group.label }}</span>
                      <span v-if="item.timeLabel" class="element-card__meta-time">{{ item.timeLabel }}</span>
                    </div>
                  </div>
                </button>
              </div>

              <div v-else class="element-group__empty" :aria-label="`${group.label} 暂无素材`">
                <q-icon :name="group.icon" size="16px" color="grey-7" />
                <span>暂无{{ group.label }}</span>
              </div>
            </section>
          </div>
        </div>
      </aside>

      <!-- CENTER: active session conversation workspace ────────────── -->
      <section
        class="grid-column grid-column--center"
        role="main"
        :aria-label="'活跃会话工作区'"
      >
        <!--
          Slot: center session content
          ──────────────────────────────
          Parent (ProjectWorkspacePage) injects <SessionChatView> here, with
          all the existing useAgentSession props wired up. This is the primary
          work surface for the active project session.
        -->
        <div class="center-session-area">
          <slot name="center-session">
            <div class="center-session-empty" :aria-busy="isAssistantBusy">
              <div class="center-session-empty__art" aria-hidden="true">
                <div class="center-session-empty__ring" />
                <q-icon name="forum" size="28px" color="grey-6" />
              </div>
              <div class="center-session-empty__title">选择左侧会话</div>
              <div class="center-session-empty__hint">
                在左侧选择一个会话，或创建新会话开始对话。
              </div>
            </div>
          </slot>
        </div>

        <!-- Bottom shot strip — outputs from the active project, shot-like thumbnails -->
        <div class="shot-strip" :aria-label="'项目产出 — 镜头序列'">
          <header class="shot-strip__header">
            <h3 class="shot-strip__title">产出</h3>
            <span class="shot-strip__count">{{ outputs.length }}</span>
          </header>

          <div v-if="outputsLoading" class="shot-strip__loading" :aria-busy="true">
            <q-spinner-dots size="20px" color="grey-5" />
            <span>加载产出中…</span>
          </div>

          <div
            v-else-if="outputs.length > 0"
            class="shot-strip__rail"
            role="listbox"
            aria-label="'项目产出缩略图'"
          >
            <button
              v-for="(item, index) in outputs"
              :key="item.id"
              type="button"
              role="option"
              :aria-selected="selectedOutputId === item.id"
              class="shot-thumb"
              :class="{ 'shot-thumb--active': selectedOutputId === item.id }"
              :aria-label="`产出 ${index + 1} — ${item.filename || '产出'}`"
              @click="handleOutputSelect(item.id)"
            >
              <div class="shot-thumb__frame">
                <img
                  v-if="item.kind === 'image' && item.url"
                  :src="item.url"
                  :alt="''"
                  class="shot-thumb__image"
                >
                <div v-else-if="item.kind === 'video' && item.url" class="shot-thumb__video">
                  <img :src="item.url" :alt="''" class="shot-thumb__image">
                  <q-icon name="play_circle" size="22px" color="white" class="shot-thumb__play" />
                </div>
                <div v-else class="shot-thumb__generic">
                  <q-icon name="description" size="20px" color="grey-7" />
                </div>
              </div>
              <div class="shot-thumb__index">{{ String(index + 1).padStart(2, '0') }}</div>
            </button>
          </div>

          <div v-else class="shot-strip__empty" :aria-label="'暂无产出'">
            <q-icon name="image" size="18px" color="grey-7" />
            <span>暂无产出</span>
          </div>
        </div>
      </section>

      <!-- RIGHT: 产出预览 + 状态 ──────────────────────────────────── -->
      <aside
        class="grid-column grid-column--right"
        :aria-label="'产出预览与项目状态'"
        role="complementary"
      >
        <div class="grid-column__header">
          <div class="grid-column__title-block">
            <h2 class="grid-column__title">产出预览</h2>
            <p class="grid-column__subtitle">
              项目输出与资源概览
            </p>
          </div>
          <span
            v-if="assistantStatus"
            class="grid-column__status"
            :class="`grid-column__status--${assistantStatus.tone}`"
            :aria-label="`当前状态 — ${assistantStatus.label}`"
          >
            <span class="grid-column__status-dot" aria-hidden="true" />
            {{ assistantStatus.label }}
          </span>
        </div>

        <!-- Selected output feature preview — moved from center -->
        <div class="output-preview" :aria-label="'产出预览'">
          <div class="output-preview__frame">
            <img
              v-if="selectedOutput && selectedOutput.kind === 'image' && selectedOutput.url"
              :src="selectedOutput.url"
              :alt="selectedOutput.filename || '当前产出'"
              class="output-preview__image"
            >
            <div
              v-else-if="selectedOutput && selectedOutput.kind === 'video' && selectedOutput.url"
              class="output-preview__video"
              role="img"
              :aria-label="`视频预览 — ${selectedOutput.filename || '当前产出'}`"
            >
              <img :src="selectedOutput.url" :alt="''" class="output-preview__image">
              <button
                type="button"
                class="output-preview__play"
                :aria-label="'播放视频'"
                @click="handlePlaySelected"
              >
                <q-icon name="play_circle" size="40px" color="white" />
              </button>
            </div>
            <div v-else class="output-preview__empty">
              <q-icon name="image" size="24px" color="grey-6" />
              <div class="output-preview__empty-text">暂无选中产出</div>
            </div>
          </div>

          <div class="output-preview__body">
            <div class="output-preview__meta-row">
              <span v-if="selectedOutput" class="output-preview__filename">
                {{ selectedOutput.filename || '未命名产出' }}
              </span>
              <span v-else class="output-preview__filename output-preview__filename--placeholder">
                选择产出查看详情
              </span>
              <span v-if="selectedOutput && selectedOutput.kind" class="output-preview__kind">
                {{ kindLabel(selectedOutput.kind) }}
              </span>
              <span
                v-if="selectedOutput && selectedOutput.model"
                class="output-preview__model"
                :aria-label="`使用模型 ${selectedOutput.model}`"
              >
                {{ selectedOutput.model }}
              </span>
            </div>
            <div v-if="selectedOutput && selectedOutput.promptText" class="output-preview__prompt">
              {{ selectedOutput.promptText }}
            </div>
          </div>
        </div>

        <!-- Project status / production workflow -->
        <div class="production-status" :aria-label="'项目生产状态'">
          <h3 class="production-status__title">项目状态</h3>
          <dl class="production-status__metrics">
            <div class="production-status__metric">
              <dt class="production-status__metric-label">会话</dt>
              <dd class="production-status__metric-value">{{ sessionCount ?? 0 }}</dd>
            </div>
            <div class="production-status__metric">
              <dt class="production-status__metric-label">产出</dt>
              <dd class="production-status__metric-value">{{ outputCount ?? 0 }}</dd>
            </div>
            <div class="production-status__metric">
              <dt class="production-status__metric-label">元素</dt>
              <dd class="production-status__metric-value">{{ elementCount }}</dd>
            </div>
            <div class="production-status__metric">
              <dt class="production-status__metric-label">文件</dt>
              <dd class="production-status__metric-value">{{ fileCount }}</dd>
            </div>
          </dl>
        </div>
      </aside>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'

// ── Types (match existing OutputItem in ProjectWorkspacePage.vue) ────────────
//
// Scaffold uses the *same* local shapes the page already exposes. The coder is
// expected to forward the existing `OutputItem` / `OpenimagoProject` reactive
// refs into the matching props. New entities (Scene, Shot, Task, Approval) are
// deliberately NOT introduced — story elements are derived from existing data.

export interface ShotOutputItem {
  id: string
  url: string
  filename: string
  kind: 'image' | 'video' | 'audio'
  timeLabel: string
  promptText: string
  // Optional richer fields — only rendered when the page provides them
  model?: string | null
  resolution?: string | null
  durationLabel?: string | null
}

export type StoryElementKind = 'character' | 'scene' | 'prop' | 'reference'

export interface StoryElement {
  id: string
  title: string
  preview: string
  thumbnailUrl: string | null
  kind: StoryElementKind
  // Free-form sync state — page maps from real asset/workspace file sync.
  syncState?: 'synced' | 'pending' | 'error' | null
  timeLabel?: string
}

export type WorkspaceTabId =
  | 'overview'
  | 'storyboard'
  | 'timeline'
  | 'edit'
  | 'audio'
  | 'exports'

export type CenterTabId = 'prompt' | 'camera' | 'motion' | 'style' | 'negative'

export interface AssistantStatus {
  label: string
  tone: 'idle' | 'busy' | 'connected' | 'error'
}

export interface SessionCardItem {
  id: string
  title: string
  preview: string
  timeLabel: string
  clockLabel: string
  meta: string
  active: boolean
}

// ── Props ────────────────────────────────────────────────────────────────────

const props = withDefaults(
  defineProps<{
    projectName: string
    projectStatus: 'active' | 'archived'
    // Existing reactive data the page already owns
    outputs?: ShotOutputItem[]
    outputsLoading?: boolean
    selectedOutputId?: string | null
    storyElements?: StoryElement[]
    selectedElementId?: string | null
    sessionCount?: number | null
    outputCount?: number | null
    fileCount?: number
    // Optional right-panel wiring — page may pass; scaffold tolerates null
    hasSession?: boolean
    sessionLabel?: string | null
    isAssistantBusy?: boolean
    assistantStatus?: AssistantStatus | null
    // Optional credits / billing display
    creditsLabel?: string
    // Session list for left panel — primary navigation surface
    sessions?: SessionCardItem[]
    activeSessionId?: string | null
    isSessionSwitching?: boolean
  }>(),
  {
    outputs: () => [],
    outputsLoading: false,
    selectedOutputId: null,
    storyElements: () => [],
    selectedElementId: null,
    sessionCount: null,
    outputCount: null,
    fileCount: 0,
    hasSession: false,
    sessionLabel: null,
    isAssistantBusy: false,
    assistantStatus: null,
    creditsLabel: '—',
    sessions: () => [],
    activeSessionId: null,
    isSessionSwitching: false,
  },
)

const emit = defineEmits<{
  (e: 'back'): void
  (e: 'open-assets'): void
  (e: 'open-export'): void
  (e: 'workspace-tab-change', tab: WorkspaceTabId): void
  (e: 'output-select', id: string): void
  (e: 'element-select', id: string): void
  (e: 'add-element'): void
  (e: 'add-to-group', group: StoryElementKind): void
  (e: 'play-output', id: string): void
  (e: 'session-select', id: string): void
  (e: 'session-create'): void
}>()

// ── Local state (UI-only, no business logic) ─────────────────────────────────

const activeWorkspaceTab = ref<WorkspaceTabId>('storyboard')
const storyElementsExpanded = ref(false)

// ── Static tab definitions (table-driven to keep template tidy) ──────────────

interface TabDescriptor<TId extends string> {
  id: TId
  label: string
  icon?: string
}

const WORKSPACE_TABS: ReadonlyArray<TabDescriptor<WorkspaceTabId>> = [
  { id: 'overview', label: '概览' },
  { id: 'storyboard', label: '故事板' },
  { id: 'timeline', label: '时间线' },
  { id: 'edit', label: '剪辑' },
  { id: 'audio', label: '音频' },
  { id: 'exports', label: '导出记录' },
]

const STORY_ELEMENT_GROUPS: ReadonlyArray<{
  id: StoryElementKind
  label: string
  icon: string
}> = [
  { id: 'character', label: '角色', icon: 'person' },
  { id: 'scene', label: '场景', icon: 'landscape' },
  { id: 'prop', label: '道具', icon: 'category' },
  { id: 'reference', label: '参考图', icon: 'image' },
]

// ── Derived ──────────────────────────────────────────────────────────────────

const storyElementGroups = computed(() =>
  STORY_ELEMENT_GROUPS.map((group) => ({
    ...group,
    items: props.storyElements.filter((item) => item.kind === group.id),
  })),
)

const elementCount = computed(() => props.storyElements.length)

const selectedOutput = computed<ShotOutputItem | null>(
  () => props.outputs.find((item) => item.id === props.selectedOutputId) ?? null,
)

// ── Event handlers (named, not inline) ───────────────────────────────────────

function handleBack(): void {
  emit('back')
}

function handleOpenAssets(): void {
  emit('open-assets')
}

function handleOpenExport(): void {
  emit('open-export')
}

function handleWorkspaceTabSelect(tab: WorkspaceTabId): void {
  activeWorkspaceTab.value = tab
  emit('workspace-tab-change', tab)
}

function handleOutputSelect(id: string): void {
  emit('output-select', id)
}

function handleElementSelect(id: string): void {
  emit('element-select', id)
}

function handleAddElement(): void {
  emit('add-element')
}

function handleSessionSelect(id: string): void {
  emit('session-select', id)
}

function handleSessionCreate(): void {
  emit('session-create')
}

function handleAddToGroup(group: StoryElementKind): void {
  emit('add-to-group', group)
}

function handlePlaySelected(): void {
  if (props.selectedOutputId) emit('play-output', props.selectedOutputId)
}

function syncLabel(state: NonNullable<StoryElement['syncState']>): string {
  if (state === 'synced') return '已同步'
  if (state === 'pending') return '同步中'
  if (state === 'error') return '同步失败'
  return ''
}

function kindLabel(kind: ShotOutputItem['kind']): string {
  if (kind === 'image') return '图像'
  if (kind === 'video') return '视频'
  if (kind === 'audio') return '音频'
  return '文件'
}

// Expose for parent integration
defineExpose({
  setActiveWorkspaceTab: (tab: WorkspaceTabId) => {
    activeWorkspaceTab.value = tab
  },
})
</script>

<style lang="scss" scoped>
// ── Design tokens — read from the global imago system, never hardcode colors ─
//
// This scaffold does NOT introduce new color values. Every background, border,
// and accent is sourced from the existing --imago-* tokens defined in
// /packages/web/src/css/app.scss.

.project-workspace-grid {
  position: relative;
  display: flex;
  flex-direction: column;
  width: 100%;
  min-height: 100%;
  background: var(--imago-bg-void);
  color: var(--imago-text-primary);
  isolation: isolate; // keep the ambient orbs behind the grid
}

// ── Ambient backdrop ─────────────────────────────────────────────────────
.grid-ambient {
  position: absolute;
  inset: 0;
  pointer-events: none;
  z-index: 0;
  overflow: hidden;
}

.grid-ambient__orb {
  position: absolute;
  border-radius: 50%;
  filter: blur(90px);
  opacity: 0.35;
  animation: orb-drift 20s ease-in-out infinite;
}

.grid-ambient__orb--cyan {
  top: -80px;
  left: 18%;
  width: 380px;
  height: 380px;
  background: radial-gradient(circle, rgba(0, 240, 255, 0.10), transparent 65%);
}

.grid-ambient__orb--violet {
  top: 30%;
  right: -80px;
  width: 320px;
  height: 320px;
  background: radial-gradient(circle, rgba(168, 85, 247, 0.08), transparent 65%);
  animation-delay: -8s;
  animation-duration: 24s;
}

.grid-ambient__ambient-grid {
  position: absolute;
  inset: 0;
  background-image:
    linear-gradient(rgba(0, 240, 255, 0.020) 1px, transparent 1px),
    linear-gradient(90deg, rgba(0, 240, 255, 0.020) 1px, transparent 1px);
  background-size: 56px 56px;
  background-position: -1px -1px;
  mask-image: radial-gradient(ellipse 80% 60% at 50% 0%, black 30%, transparent 80%);
  -webkit-mask-image: radial-gradient(ellipse 80% 60% at 50% 0%, black 30%, transparent 80%);
}

@keyframes orb-drift {
  0%, 100% { transform: translate3d(0, 0, 0) scale(1); }
  33%      { transform: translate3d(40px, -20px, 0) scale(1.08); }
  66%      { transform: translate3d(-30px, 30px, 0) scale(0.95); }
}

@media (prefers-reduced-motion: reduce) {
  .grid-ambient__orb { animation: none !important; }
}

// ── Command bar ───────────────────────────────────────────────────────────
.command-bar {
  position: relative;
  z-index: 2;
  display: flex;
  align-items: center;
  gap: 16px;
  height: 60px;
  flex-shrink: 0;
  padding: 0 20px;
  border-bottom: 1px solid var(--imago-border-light);
  background: linear-gradient(180deg, rgba(8, 8, 15, 0.92), rgba(8, 8, 15, 0.78));
  backdrop-filter: var(--imago-blur-panel);
  -webkit-backdrop-filter: var(--imago-blur-panel);
}

.command-bar__left {
  display: flex;
  align-items: center;
  gap: 14px;
  min-width: 0;
  flex: 0 0 auto;
}

.command-bar__back {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  border: 1px solid var(--imago-border-light);
  border-radius: var(--imago-radius-md);
  background: transparent;
  color: var(--imago-text-muted);
  cursor: pointer;
  transition: color var(--imago-ease-fast), background var(--imago-ease-fast),
    border-color var(--imago-ease-fast);

  &:hover {
    color: var(--imago-text-primary);
    background: var(--imago-bg-raised);
    border-color: var(--imago-border-soft);
  }

  &:focus-visible {
    outline: 2px solid var(--imago-neon-cyan);
    outline-offset: 2px;
  }
}

.command-bar__title-block {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.command-bar__title {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
  color: var(--imago-text-primary);
  letter-spacing: -0.005em;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.command-bar__meta {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 11.5px;
  color: var(--imago-text-dim);
}

.command-bar__status {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 1px 8px;
  border-radius: var(--imago-radius-pill);
  font-size: 11px;
  font-weight: 500;
  background: var(--imago-cyan-08);
  color: rgba(0, 240, 255, 0.82);
  border: 1px solid var(--imago-border-cyan);
}

.command-bar__status--archived {
  background: var(--imago-bg-raised);
  color: var(--imago-text-dim);
  border-color: var(--imago-border-light);
}

.command-bar__status-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: var(--imago-neon-cyan);
  box-shadow: 0 0 6px var(--imago-cyan-08);
}

.command-bar__status--archived .command-bar__status-dot {
  background: var(--imago-text-faint);
  box-shadow: none;
}

.command-bar__meta-divider {
  color: var(--imago-text-faint);
}

.command-bar__meta-text {
  color: var(--imago-text-secondary);
  font-weight: 500;
}

// Tabs — segmented control
.command-bar__tabs {
  display: flex;
  align-items: center;
  gap: 2px;
  flex: 1 1 auto;
  min-width: 0;
  padding: 4px;
  border: 1px solid var(--imago-border-light);
  border-radius: var(--imago-radius-lg);
  background: var(--imago-bg-deep);
  overflow-x: auto;
  scrollbar-width: none;

  &::-webkit-scrollbar { display: none; }
}

.command-bar__tab {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  flex-shrink: 0;
  padding: 6px 12px;
  border: 1px solid transparent;
  border-radius: var(--imago-radius-md);
  background: transparent;
  color: var(--imago-text-muted);
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  white-space: nowrap;
  transition: color var(--imago-ease-fast), background var(--imago-ease-fast),
    border-color var(--imago-ease-fast);

  &:hover {
    color: var(--imago-text-primary);
    background: var(--imago-bg-raised);
  }

  &:focus-visible {
    outline: 2px solid var(--imago-neon-cyan);
    outline-offset: 2px;
  }
}

.command-bar__tab--active {
  color: var(--imago-neon-cyan);
  background: var(--imago-cyan-06);
  border-color: var(--imago-border-cyan-active);
  box-shadow: var(--imago-glow-cyan-inline);
}

.command-bar__tab-icon {
  opacity: 0.75;
}

.command-bar__right {
  display: flex;
  align-items: center;
  gap: 8px;
  flex: 0 0 auto;
}

.command-bar__action {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 6px 12px;
  border: 1px solid var(--imago-border-light);
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-raised);
  color: var(--imago-text-secondary);
  font-size: 12.5px;
  font-weight: 500;
  cursor: pointer;
  transition: color var(--imago-ease-fast), background var(--imago-ease-fast),
    border-color var(--imago-ease-fast);

  &:hover {
    color: var(--imago-text-primary);
    border-color: var(--imago-border-cyan);
    background: var(--imago-cyan-04);
  }

  &:focus-visible {
    outline: 2px solid var(--imago-neon-cyan);
    outline-offset: 2px;
  }
}

.command-bar__credits {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 5px 10px;
  border: 1px solid var(--imago-border-cyan);
  border-radius: var(--imago-radius-md);
  background: var(--imago-cyan-04);
  color: var(--imago-neon-cyan);
  font-size: 12px;
  font-weight: 600;
  font-variant-numeric: tabular-nums;
}

.command-bar__credits-icon { opacity: 0.85; }

// ── Three-column grid body ──────────────────────────────────────────────────
.grid-body {
  position: relative;
  z-index: 1;
  display: grid;
  grid-template-columns: 280px minmax(0, 1fr) 320px;
  gap: 0;
  flex: 1;
  min-height: 0;
  overflow: hidden;
}

@media (max-width: 1280px) {
  .grid-body {
    grid-template-columns: 240px minmax(0, 1fr) 280px;
  }
}

@media (max-width: 1024px) {
  .grid-body {
    grid-template-columns: 220px minmax(0, 1fr);
  }
  .grid-column--right {
    display: none;
  }
}

@media (max-width: 768px) {
  .grid-body {
    grid-template-columns: 1fr;
  }
  .grid-column--left {
    display: none;
  }
}

.grid-column {
  position: relative;
  display: flex;
  flex-direction: column;
  min-width: 0;
  min-height: 0;
  overflow: hidden;
}

.grid-column--left {
  border-right: 1px solid var(--imago-border-light);
  background: linear-gradient(180deg, var(--imago-bg-deep), var(--imago-bg-void) 40%);
}

.grid-column--center {
  background: var(--imago-bg-void);
}

.grid-column--right {
  border-left: 1px solid var(--imago-border-light);
  background: linear-gradient(180deg, var(--imago-bg-deep), var(--imago-bg-void) 40%);
}

.grid-column__header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 12px;
  padding: 18px 18px 12px;
  flex-shrink: 0;
}

.grid-column__title-block {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.grid-column__title {
  margin: 0;
  font-size: 14px;
  font-weight: 600;
  color: var(--imago-text-primary);
  letter-spacing: 0.005em;
}

.grid-column__subtitle {
  margin: 0;
  font-size: 11.5px;
  color: var(--imago-text-dim);
  line-height: 1.4;
}

.grid-column__add {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-raised);
  color: var(--imago-text-muted);
  cursor: pointer;
  transition: color var(--imago-ease-fast), background var(--imago-ease-fast),
    border-color var(--imago-ease-fast);

  &:hover {
    color: var(--imago-neon-cyan);
    background: var(--imago-cyan-06);
    border-color: var(--imago-border-cyan-active);
  }

  &:focus-visible {
    outline: 2px solid var(--imago-neon-cyan);
    outline-offset: 2px;
  }
}

.grid-column__status {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 2px 8px;
  border-radius: var(--imago-radius-pill);
  font-size: 10.5px;
  font-weight: 500;
  background: var(--imago-bg-raised);
  color: var(--imago-text-dim);
  border: 1px solid var(--imago-border-light);
}

.grid-column__status-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: var(--imago-text-faint);
}

.grid-column__status--idle .grid-column__status-dot { background: var(--imago-text-faint); }
.grid-column__status--connected {
  color: rgba(0, 240, 255, 0.82);
  border-color: var(--imago-border-cyan);
  background: var(--imago-cyan-06);
}
.grid-column__status--connected .grid-column__status-dot {
  background: var(--imago-neon-cyan);
  box-shadow: 0 0 6px var(--imago-cyan-08);
}
.grid-column__status--busy {
  color: rgba(168, 85, 247, 0.88);
  border-color: rgba(168, 85, 247, 0.24);
  background: rgba(168, 85, 247, 0.06);
}
.grid-column__status--busy .grid-column__status-dot {
  background: var(--imago-neon-purple);
  box-shadow: 0 0 6px rgba(168, 85, 247, 0.30);
}
.grid-column__status--error {
  color: #fda4af;
  border-color: rgba(244, 63, 94, 0.30);
  background: rgba(244, 63, 94, 0.06);
}
.grid-column__status--error .grid-column__status-dot {
  background: #f43f5e;
}

// ── LEFT: Session list (primary) ──────────────────────────────────────────────
.session-list-panel {
  flex: 1;
  min-height: 0;
  overflow-y: auto;
  padding: 4px 12px 8px 16px;
}

.session-group {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.session-group__title {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  padding: 0 2px;
  position: sticky;
  top: 0;
  z-index: 1;
  background: linear-gradient(180deg, var(--imago-bg-deep), transparent);
  font-size: 10.5px;
  font-weight: 600;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--imago-text-dim);
}

.session-group__count {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 20px;
  height: 16px;
  padding: 0 5px;
  border-radius: var(--imago-radius-pill);
  font-size: 10px;
  font-weight: 600;
  color: var(--imago-neon-cyan);
  background: var(--imago-cyan-06);
  border: 1px solid var(--imago-border-cyan);
  font-variant-numeric: tabular-nums;
}

.session-list {
  display: grid;
  gap: 8px;
}

.session-list-empty {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 12px;
  border: 1px dashed var(--imago-border-soft);
  border-radius: var(--imago-radius-md);
  color: var(--imago-text-faint);
  font-size: 11.5px;
  text-align: center;
  justify-content: center;
}

.session-card {
  display: flex;
  flex-direction: column;
  padding: 12px;
  border: 1px solid var(--imago-border-light);
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-surface);
  text-align: left;
  cursor: pointer;
  transition: border-color var(--imago-ease-default), background var(--imago-ease-default),
    box-shadow var(--imago-ease-default), transform var(--imago-ease-default);

  &:hover {
    border-color: var(--imago-border-cyan);
    background: var(--imago-bg-raised);
    transform: translateY(-1px);
    box-shadow: 0 0 26px rgba(0, 240, 255, 0.06);
  }

  &:focus-visible {
    outline: 2px solid var(--imago-neon-cyan);
    outline-offset: 2px;
  }
}

.session-card--active {
  border-color: var(--imago-border-cyan-active);
  background: var(--imago-cyan-04);
  box-shadow: inset 0 0 0 1px var(--imago-border-cyan),
    0 0 34px rgba(0, 240, 255, 0.1);
}

.session-card__body {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.session-card__row {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  gap: 8px;
}

.session-card__title {
  font-size: 13px;
  font-weight: 500;
  color: var(--imago-text-primary);
  line-height: 1.3;
}

.session-card__time {
  flex-shrink: 0;
  font-size: 11px;
  color: var(--imago-text-faint);
  white-space: nowrap;
}

.session-card__preview {
  font-size: 12px;
  color: var(--imago-text-dim);
  line-height: 1.45;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.session-card__meta {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 10.5px;
  color: var(--imago-text-faint);
}

.session-card__meta-label {
  color: var(--imago-text-muted);
  font-weight: 500;
}

.session-card__meta-time {
  color: var(--imago-text-faint);
  font-variant-numeric: tabular-nums;
}

// ── LEFT: Story elements (secondary, collapsed by default) ────────────────────
.elements-section {
  flex-shrink: 0;
  border-top: 1px solid var(--imago-border-light);
}

.elements-section__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  padding: 12px 16px 4px;
}

.elements-section__toggle {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 0;
  border: 0;
  background: transparent;
  color: inherit;
  cursor: pointer;
  flex: 1;
  min-width: 0;
  text-align: left;

  &:hover .elements-section__toggle-icon {
    color: var(--imago-neon-cyan);
  }
}

.elements-section__toggle-icon {
  color: var(--imago-text-muted);
  transition: color var(--imago-ease-fast);
}

// ── LEFT: Story elements (unchanged visual styling) ───────────────────────────
.elements-list {
  max-height: 320px;
  overflow-y: auto;
  padding: 4px 12px 16px 16px;
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.element-group {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.element-group__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  padding: 0 2px;
  position: sticky;
  top: 0;
  background: linear-gradient(180deg, var(--imago-bg-deep), transparent);
  z-index: 1;
}

.element-group__label-block {
  display: inline-flex;
  align-items: center;
  gap: 8px;
}

.element-group__label {
  font-size: 10.5px;
  font-weight: 600;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--imago-text-dim);
}

.element-group__count {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 20px;
  height: 16px;
  padding: 0 5px;
  border-radius: var(--imago-radius-pill);
  font-size: 10px;
  font-weight: 600;
  color: var(--imago-text-muted);
  background: var(--imago-bg-raised);
  border: 1px solid var(--imago-border-light);
  font-variant-numeric: tabular-nums;
}

.element-group__add {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 22px;
  height: 22px;
  padding: 0;
  border: 1px solid transparent;
  border-radius: var(--imago-radius-sm);
  background: transparent;
  color: var(--imago-text-muted);
  cursor: pointer;
  transition: color var(--imago-ease-fast), background var(--imago-ease-fast),
    border-color var(--imago-ease-fast);

  &:hover {
    color: var(--imago-neon-cyan);
    background: var(--imago-cyan-06);
    border-color: var(--imago-border-cyan);
  }

  &:focus-visible {
    outline: 2px solid var(--imago-neon-cyan);
    outline-offset: 2px;
  }
}

.element-group__items {
  display: grid;
  grid-template-columns: 1fr;
  gap: 8px;
}

.element-group__empty {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 10px 12px;
  border: 1px dashed var(--imago-border-soft);
  border-radius: var(--imago-radius-md);
  color: var(--imago-text-faint);
  font-size: 11.5px;
}

.element-card {
  display: flex;
  flex-direction: column;
  gap: 6px;
  padding: 6px;
  border: 1px solid var(--imago-border-light);
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-surface);
  text-align: left;
  cursor: pointer;
  transition: border-color var(--imago-ease-default), box-shadow var(--imago-ease-default),
    background var(--imago-ease-default);

  &:hover {
    border-color: var(--imago-border-cyan);
    background: var(--imago-bg-raised);
  }

  &:focus-visible {
    outline: 2px solid var(--imago-neon-cyan);
    outline-offset: 2px;
  }
}

.element-card--active {
  border-color: var(--imago-border-cyan-active);
  background: var(--imago-cyan-04);
  box-shadow: inset 0 0 0 1px var(--imago-border-cyan),
    0 0 16px rgba(0, 240, 255, 0.06);
}

.element-card__thumb {
  position: relative;
  aspect-ratio: 16 / 10;
  overflow: hidden;
  border-radius: var(--imago-radius-sm);
  background: var(--imago-bg-code);
  border: 1px solid var(--imago-border-subtle);
}

.element-card__image {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.element-card__thumb-fallback {
  width: 100%;
  height: 100%;
  display: grid;
  place-items: center;
  background: linear-gradient(135deg, var(--imago-bg-deep), var(--imago-bg-panel));
}

.element-card__sync {
  position: absolute;
  top: 6px;
  right: 6px;
  width: 18px;
  height: 18px;
  border-radius: 50%;
  background: var(--imago-bg-deep);
  border: 1px solid var(--imago-border-soft);
  display: grid;
  place-items: center;
}

.element-card__sync-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: var(--imago-text-faint);
}

.element-card__sync--synced {
  border-color: var(--imago-border-cyan);
  background: var(--imago-cyan-06);
}
.element-card__sync--synced .element-card__sync-dot {
  background: var(--imago-neon-cyan);
  box-shadow: 0 0 4px var(--imago-cyan-08);
}

.element-card__sync--pending {
  border-color: rgba(168, 85, 247, 0.24);
  background: rgba(168, 85, 247, 0.06);
}
.element-card__sync--pending .element-card__sync-dot {
  background: var(--imago-neon-purple);
  animation: sync-pulse 1.4s ease-in-out infinite;
}

.element-card__sync--error {
  border-color: rgba(244, 63, 94, 0.30);
  background: rgba(244, 63, 94, 0.08);
}
.element-card__sync--error .element-card__sync-dot { background: #f43f5e; }

@keyframes sync-pulse {
  0%, 100% { opacity: 0.4; transform: scale(0.85); }
  50%      { opacity: 1.0; transform: scale(1.15); }
}

@media (prefers-reduced-motion: reduce) {
  .element-card__sync--pending .element-card__sync-dot { animation: none; }
}

.element-card__body {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 0 2px 2px;
}

.element-card__title {
  font-size: 12.5px;
  font-weight: 500;
  color: var(--imago-text-primary);
}

.element-card__preview {
  font-size: 11px;
  color: var(--imago-text-dim);
  line-height: 1.45;
}

.element-card__meta {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 10.5px;
  color: var(--imago-text-faint);
}

.element-card__meta-kind {
  color: var(--imago-text-muted);
  font-weight: 500;
}

.element-card__meta-time {
  color: var(--imago-text-faint);
  font-variant-numeric: tabular-nums;
}

.ellipsis-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

// ── CENTER: Session conversation workspace ─────────────────────────────────

.center-session-area {
  flex: 1;
  min-height: 0;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.center-session-area > :slotted(*) {
  display: flex;
  flex-direction: column;
  flex: 1;
  min-height: 0;
  width: 100%;
}

.center-session-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 10px;
  height: 100%;
  padding: 32px 24px;
  text-align: center;
}

.center-session-empty__art {
  position: relative;
  width: 88px;
  height: 88px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.center-session-empty__ring {
  position: absolute;
  inset: 0;
  border-radius: 50%;
  border: 1.5px solid var(--imago-border-cyan);
  box-shadow: var(--imago-glow-cyan-soft);
  animation: empty-pulse 3.5s ease-in-out infinite;
}

.center-session-empty__title {
  font-size: 16px;
  font-weight: 600;
  color: var(--imago-text-secondary);
}

.center-session-empty__hint {
  max-width: 320px;
  font-size: 13px;
  color: var(--imago-text-dim);
  line-height: 1.55;
}

// ── RIGHT: Output preview ───────────────────────────────────────────────────

.output-preview {
  display: flex;
  flex-direction: column;
  gap: 10px;
  padding: 0 18px 12px;
  flex-shrink: 0;
}

.output-preview__frame {
  aspect-ratio: 16 / 9;
  overflow: hidden;
  border-radius: var(--imago-radius-lg);
  border: 1px solid var(--imago-border-soft);
  background: var(--imago-bg-surface);
}

.output-preview__image {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.output-preview__video {
  position: relative;
  width: 100%;
  height: 100%;
}

.output-preview__play {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 56px;
  height: 56px;
  padding: 0;
  border: 1px solid rgba(255, 255, 255, 0.20);
  border-radius: 50%;
  background: rgba(0, 0, 0, 0.35);
  cursor: pointer;
  opacity: 0.85;
  transition: opacity var(--imago-ease-fast), transform var(--imago-ease-fast),
    background var(--imago-ease-fast);

  &:hover {
    opacity: 1;
    background: rgba(0, 0, 0, 0.55);
    transform: translate(-50%, -50%) scale(1.05);
  }

  &:focus-visible {
    outline: 2px solid var(--imago-neon-cyan);
    outline-offset: 2px;
  }
}

.output-preview__empty {
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 16px;
  background: var(--imago-bg-deep);
}

.output-preview__empty-text {
  font-size: 12px;
  color: var(--imago-text-dim);
}

.output-preview__body {
  display: flex;
  flex-direction: column;
  gap: 6px;
  min-width: 0;
}

.output-preview__meta-row {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 6px;
  font-size: 11px;
  color: var(--imago-text-dim);
}

.output-preview__filename {
  font-size: 12px;
  font-weight: 600;
  color: var(--imago-text-primary);
  max-width: 200px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.output-preview__filename--placeholder {
  color: var(--imago-text-faint);
  font-weight: 500;
}

.output-preview__kind,
.output-preview__model {
  display: inline-flex;
  align-items: center;
  padding: 1px 6px;
  border-radius: var(--imago-radius-pill);
  font-size: 10px;
  font-weight: 500;
  background: var(--imago-bg-raised);
  color: var(--imago-text-muted);
  border: 1px solid var(--imago-border-light);
}

.output-preview__kind {
  color: var(--imago-neon-cyan);
  border-color: var(--imago-border-cyan);
  background: var(--imago-cyan-06);
}

.output-preview__prompt {
  font-size: 11.5px;
  color: var(--imago-text-dim);
  line-height: 1.5;
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

// ── OLD: Shot feature styles (kept for backward compat, used by right panel now) ─

.shot-feature {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 20px 24px 16px;
  flex-shrink: 0;
}

.shot-feature__frame {
  position: relative;
  aspect-ratio: 16 / 9;
  overflow: hidden;
  border-radius: var(--imago-radius-2xl);
  border: 1px solid var(--imago-border-cyan);
  background:
    linear-gradient(180deg, rgba(0, 240, 255, 0.02), transparent 30%),
    var(--imago-bg-deep);
  box-shadow: var(--imago-glow-cyan-soft);
}

.shot-feature__image {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.shot-feature__video {
  position: relative;
  width: 100%;
  height: 100%;
}

.shot-feature__play {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 72px;
  height: 72px;
  padding: 0;
  border: 1px solid rgba(255, 255, 255, 0.20);
  border-radius: 50%;
  background: rgba(0, 0, 0, 0.35);
  cursor: pointer;
  opacity: 0.85;
  transition: opacity var(--imago-ease-fast), transform var(--imago-ease-fast),
    background var(--imago-ease-fast);

  &:hover {
    opacity: 1;
    background: rgba(0, 0, 0, 0.55);
    transform: translate(-50%, -50%) scale(1.05);
  }

  &:focus-visible {
    outline: 2px solid var(--imago-neon-cyan);
    outline-offset: 2px;
  }
}

.shot-feature__empty {
  position: relative;
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 24px;
  text-align: center;
}

.shot-feature__empty-art {
  position: relative;
  width: 88px;
  height: 88px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.shot-feature__empty-ring {
  position: absolute;
  inset: 0;
  border-radius: 50%;
  border: 1.5px solid var(--imago-border-cyan);
  box-shadow: var(--imago-glow-cyan-soft);
  animation: empty-pulse 3.5s ease-in-out infinite;
}

@keyframes empty-pulse {
  0%, 100% { transform: scale(1); opacity: 0.6; }
  50%      { transform: scale(1.08); opacity: 1.0; }
}

@media (prefers-reduced-motion: reduce) {
  .shot-feature__empty-ring { animation: none; }
}

.shot-feature__empty-title {
  font-size: 14px;
  font-weight: 600;
  color: var(--imago-text-secondary);
}

.shot-feature__empty-hint {
  max-width: 320px;
  font-size: 12px;
  color: var(--imago-text-dim);
  line-height: 1.55;
}

.shot-feature__body {
  display: flex;
  flex-direction: column;
  gap: 6px;
  min-width: 0;
}

.shot-feature__meta-row {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 8px;
  font-size: 12px;
  color: var(--imago-text-dim);
}

.shot-feature__filename {
  font-size: 13px;
  font-weight: 600;
  color: var(--imago-text-primary);
  max-width: 360px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.shot-feature__filename--placeholder {
  color: var(--imago-text-faint);
  font-weight: 500;
}

.shot-feature__kind,
.shot-feature__model,
.shot-feature__resolution,
.shot-feature__duration {
  display: inline-flex;
  align-items: center;
  padding: 1px 8px;
  border-radius: var(--imago-radius-pill);
  font-size: 10.5px;
  font-weight: 500;
  background: var(--imago-bg-raised);
  color: var(--imago-text-muted);
  border: 1px solid var(--imago-border-light);
}

.shot-feature__kind {
  color: var(--imago-neon-cyan);
  border-color: var(--imago-border-cyan);
  background: var(--imago-cyan-06);
}

.shot-feature__prompt {
  font-size: 12.5px;
  color: var(--imago-text-dim);
  line-height: 1.5;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

// Center tabs
.center-tabs {
  display: flex;
  align-items: center;
  gap: 2px;
  padding: 0 20px;
  flex-shrink: 0;
  border-bottom: 1px solid var(--imago-border-light);
  overflow-x: auto;
  scrollbar-width: none;

  &::-webkit-scrollbar { display: none; }
}

.center-tab {
  position: relative;
  flex-shrink: 0;
  padding: 10px 14px;
  border: 0;
  background: transparent;
  color: var(--imago-text-muted);
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  white-space: nowrap;
  transition: color var(--imago-ease-fast);

  &::after {
    content: '';
    position: absolute;
    left: 12px;
    right: 12px;
    bottom: 0;
    height: 2px;
    border-radius: 2px;
    background: transparent;
    transition: background var(--imago-ease-fast);
  }

  &:hover { color: var(--imago-text-primary); }

  &:focus-visible {
    outline: 2px solid var(--imago-neon-cyan);
    outline-offset: -2px;
  }
}

.center-tab--active {
  color: var(--imago-neon-cyan);

  &::after {
    background: var(--imago-neon-cyan);
    box-shadow: 0 0 8px var(--imago-cyan-08);
  }
}

.center-panel {
  flex: 1;
  min-height: 0;
  overflow-y: auto;
  padding: 18px 24px 4px;
}

.center-panel__prompt {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.center-panel__field-label {
  font-size: 11.5px;
  font-weight: 600;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  color: var(--imago-text-dim);
}

.center-panel__prompt-input {
  width: 100%;
  min-height: 96px;
  padding: 14px 16px;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-lg);
  background: var(--imago-bg-surface);
  color: var(--imago-text-primary);
  font-size: 13.5px;
  line-height: 1.6;
  font-family: inherit;
  resize: vertical;
  transition: border-color var(--imago-ease-fast),
    box-shadow var(--imago-ease-fast),
    background var(--imago-ease-fast);

  &::placeholder { color: var(--imago-text-faint); }

  &:hover {
    border-color: var(--imago-border-dim);
  }

  &:focus {
    outline: none;
    border-color: var(--imago-border-cyan-active);
    background: var(--imago-cyan-04);
    box-shadow: 0 0 0 3px var(--imago-cyan-04);
  }
}

.center-panel__prompt-footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  font-size: 11.5px;
  color: var(--imago-text-dim);
}

.center-panel__prompt-hint {
  flex: 1;
  min-width: 0;
}

.center-panel__prompt-apply {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 6px 14px;
  border: 1px solid var(--imago-border-cyan-active);
  border-radius: var(--imago-radius-md);
  background: var(--imago-cyan-06);
  color: var(--imago-neon-cyan);
  font-size: 12px;
  font-weight: 600;
  cursor: pointer;
  transition: background var(--imago-ease-fast), color var(--imago-ease-fast),
    box-shadow var(--imago-ease-fast);

  &:hover:not(:disabled) {
    background: var(--imago-cyan-08);
    box-shadow: var(--imago-glow-cyan-inline);
  }

  &:disabled {
    opacity: 0.45;
    cursor: not-allowed;
  }

  &:focus-visible {
    outline: 2px solid var(--imago-neon-cyan);
    outline-offset: 2px;
  }
}

.center-panel__placeholder {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 40px 24px;
  border: 1px dashed var(--imago-border-light);
  border-radius: var(--imago-radius-lg);
  background: var(--imago-bg-surface);
  text-align: center;
}

.center-panel__placeholder-title {
  font-size: 14px;
  font-weight: 600;
  color: var(--imago-text-secondary);
}

.center-panel__placeholder-hint {
  max-width: 360px;
  font-size: 12px;
  color: var(--imago-text-dim);
  line-height: 1.55;
}

// Shot strip
.shot-strip {
  flex-shrink: 0;
  border-top: 1px solid var(--imago-border-light);
  background: linear-gradient(180deg, var(--imago-bg-deep), var(--imago-bg-void));
}

.shot-strip__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 24px 8px;
}

.shot-strip__title {
  margin: 0;
  font-size: 11.5px;
  font-weight: 600;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--imago-text-dim);
}

.shot-strip__count {
  font-size: 11px;
  font-weight: 500;
  color: var(--imago-text-muted);
  font-variant-numeric: tabular-nums;
}

.shot-strip__loading {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 12px 24px 18px;
  color: var(--imago-text-dim);
  font-size: 12px;
}

.shot-strip__empty {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 12px 24px 18px;
  color: var(--imago-text-faint);
  font-size: 12px;
}

.shot-strip__rail {
  display: flex;
  align-items: stretch;
  gap: 10px;
  padding: 0 24px 16px;
  overflow-x: auto;
  scrollbar-width: thin;
  scrollbar-color: var(--imago-border-soft) transparent;

  &::-webkit-scrollbar {
    height: 6px;
  }
  &::-webkit-scrollbar-track { background: transparent; }
  &::-webkit-scrollbar-thumb {
    background: var(--imago-border-soft);
    border-radius: 3px;
  }
}

.shot-thumb {
  position: relative;
  flex-shrink: 0;
  width: 96px;
  padding: 0;
  border: 1px solid var(--imago-border-light);
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-surface);
  cursor: pointer;
  overflow: hidden;
  transition: border-color var(--imago-ease-default), box-shadow var(--imago-ease-default),
    transform var(--imago-ease-default);

  &:hover {
    border-color: var(--imago-border-cyan);
    transform: translateY(-1px);
  }

  &:focus-visible {
    outline: 2px solid var(--imago-neon-cyan);
    outline-offset: 2px;
  }
}

.shot-thumb--active {
  border-color: var(--imago-border-cyan-active);
  box-shadow: inset 0 0 0 1px var(--imago-border-cyan),
    0 0 14px rgba(0, 240, 255, 0.18);
}

.shot-thumb__frame {
  aspect-ratio: 16 / 9;
  overflow: hidden;
  background: var(--imago-bg-code);
}

.shot-thumb__image {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.shot-thumb__video {
  position: relative;
  width: 100%;
  height: 100%;
}

.shot-thumb__play {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  opacity: 0.85;
  pointer-events: none;
}

.shot-thumb__generic {
  width: 100%;
  height: 100%;
  display: grid;
  place-items: center;
  background: var(--imago-bg-code);
}

.shot-thumb__index {
  padding: 4px 0;
  text-align: center;
  font-size: 10px;
  font-weight: 500;
  color: var(--imago-text-dim);
  font-variant-numeric: tabular-nums;
  letter-spacing: 0.04em;
  border-top: 1px solid var(--imago-border-subtle);
  background: var(--imago-bg-deep);
}

.shot-thumb--active .shot-thumb__index {
  color: var(--imago-neon-cyan);
  background: var(--imago-cyan-04);
}

// ── RIGHT: output preview + status ───────────────────────────────────────────

// Right column internal layout: header + (flex) output preview + production status.
// Production status stays at the bottom.
.grid-column--right {
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.grid-column--right .grid-column__header {
  flex-shrink: 0;
}

.grid-column--right .output-preview {
  flex-shrink: 0;
}

.grid-column--right .production-status {
  flex-shrink: 0;
  margin-top: auto;
}

// Production status
.production-status {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 16px 18px 20px;
  border-top: 1px solid var(--imago-border-light);
}

.production-status__title {
  margin: 0;
  font-size: 11.5px;
  font-weight: 600;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--imago-text-dim);
}

.production-status__metrics {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 8px;
  margin: 0;
}

.production-status__metric {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 10px 12px;
  border: 1px solid var(--imago-border-light);
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-surface);
}

.production-status__metric-label {
  margin: 0;
  font-size: 10.5px;
  color: var(--imago-text-dim);
  letter-spacing: 0.04em;
  text-transform: uppercase;
}

.production-status__metric-value {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
  color: var(--imago-text-primary);
  font-variant-numeric: tabular-nums;
}

.production-status__workflow {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.workflow-card {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  padding: 10px 12px;
  border: 1px solid var(--imago-border-light);
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-surface);
}

.workflow-card--scaffold {
  border-style: dashed;
  border-color: var(--imago-border-soft);
  background: transparent;
  color: var(--imago-text-dim);
}

.workflow-card__body {
  display: flex;
  flex-direction: column;
  gap: 2px;
  min-width: 0;
}

.workflow-card__title {
  font-size: 12.5px;
  font-weight: 500;
  color: var(--imago-text-secondary);
}

.workflow-card__hint {
  font-size: 11px;
  color: var(--imago-text-faint);
  line-height: 1.4;
}
</style>
