// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change component structure or accessibility attributes
//
// ProjectWorkspaceStoryPanel
// ──────────────────────────
// Read-only story editor/panel for the ProjectWorkspace. Consumes the
// `Story*Summary` projections derived from ADR 0004 schema JSON files
// (openimago-1a3) and renders:
//
//   • series / episode selector (read-only)
//   • bible summary rail (characters, scenes, style seeds)
//   • current-episode scene strip + shot list
//   • selected-shot detail (description, dialogue, visualPrompt, refs)
//   • workflow step + run status for the selected shot
//
// Aesthetic direction: "production slate on a dark creative ops dashboard."
// The hero bar is anchored by a film-perforation strip; the shot rail
// is rendered as a contact-sheet style vertical strip with index numerals
// in monospace; the bible rail uses the same dashed-bordered card grammar
// as WorkspaceArtifactsPanel. Selection uses the cyan neon-active ring.
// Read-only MVP — edit/regenerate actions emit intents only.
//
// SCSS uses only `--imago-*` tokens from src/css/app.scss.

<template>
  <section
    class="story-panel"
    role="region"
    :aria-label="ariaLabel"
    :aria-busy="isLoading"
  >
    <!-- ── Sprocket strip — film-perforation motif along the hero bar ── -->
    <div class="story-panel__sprocket" aria-hidden="true">
      <span v-for="i in SPROCKET_COUNT" :key="i" class="story-panel__perf" />
    </div>

    <!-- ── Hero: series + episode selector ────────────────────────────── -->
    <header class="story-panel__hero">
      <div class="story-panel__hero-text">
        <p class="story-panel__eyebrow">故事工作台</p>
        <h2 class="story-panel__title">
          {{ seriesTitle || '未命名系列' }}
        </h2>
        <p v-if="seriesDescription" class="story-panel__subtitle">
          {{ seriesDescription }}
        </p>
      </div>

      <div class="story-panel__episode-picker">
        <label for="story-episode-select" class="story-panel__picker-label">
          当前集数
        </label>
        <div class="story-panel__select-wrap">
          <q-select
            v-model="selectedEpisodeIdModel"
            for="story-episode-select"
            :options="episodeSelectOptions"
            :disable="episodes.length === 0 || isLoading"
            :display-value="episodes.length === 0 ? '暂无集数' : undefined"
            dark
            outlined
            dense
            emit-value
            map-options
            aria-label="选择集数"
            class="story-panel__q-select"
            @update:model-value="handleEpisodeChange"
          />
        </div>
        <span
          v-if="currentEpisode"
          class="story-panel__episode-status"
          :class="`story-panel__episode-status--${currentEpisode.status}`"
          :aria-label="`当前集数状态 — ${episodeStatusLabel(currentEpisode.status)}`"
        >
          <span class="story-panel__episode-status-dot" aria-hidden="true" />
          {{ episodeStatusLabel(currentEpisode.status) }}
        </span>
      </div>
    </header>

    <!-- ── Body: 3 columns — bible rail · shot rail · detail ──────────── -->
    <div class="story-panel__body">
      <!-- LEFT RAIL: bible summaries ────────────────────────────────── -->
      <aside
        class="story-panel__bible-rail"
        :aria-label="'圣经总览'"
        role="complementary"
      >
        <div class="story-panel__rail-section">
          <header class="story-panel__rail-header">
            <h3 class="story-panel__rail-title">世界观</h3>
            <span class="story-panel__rail-count">{{ worldChipCount }}</span>
          </header>
          <p
            v-if="bible"
            class="story-panel__world-card"
            :aria-label="'世界观概览'"
          >
            <span class="story-panel__world-name">{{ bible.worldName || '未命名' }}</span>
            <span
              v-if="bible.era"
              class="story-panel__world-era"
            >{{ bible.era }}</span>
            <span
              v-if="bible.worldDescription"
              class="story-panel__world-desc ellipsis-3"
            >{{ bible.worldDescription }}</span>
            <span
              v-if="bible.moodKeywords.length > 0"
              class="story-panel__world-tags"
            >
              <span
                v-for="kw in bible.moodKeywords.slice(0, 6)"
                :key="kw"
                class="story-panel__world-tag"
              >{{ kw }}</span>
            </span>
          </p>
          <p
            v-else
            class="story-panel__rail-empty"
            :aria-label="'暂无世界观数据'"
          >
            <q-icon name="public" size="16px" color="grey-7" />
            <span>暂无世界观 — 由 Agent 写入 bible.json</span>
          </p>
        </div>

        <div class="story-panel__rail-section">
          <header class="story-panel__rail-header">
            <h3 class="story-panel__rail-title">角色</h3>
            <span class="story-panel__rail-count">{{ bible?.characters.length ?? 0 }}</span>
          </header>
          <div
            v-if="bible && bible.characters.length > 0"
            class="story-panel__cards"
            role="list"
            aria-label="'圣经角色'"
          >
            <button
              v-for="character in bible.characters"
              :key="character.id"
              type="button"
              role="listitem"
              class="story-panel__card"
              :class="{
                'story-panel__card--active': selectedCharacterId === character.id,
              }"
              :aria-pressed="selectedCharacterId === character.id"
              :aria-label="`选择角色 ${character.displayName}`"
              @click="handleCharacterSelect(character.id)"
            >
              <div class="story-panel__card-thumb" aria-hidden="true">
                <img
                  v-if="character.thumbnailUrl"
                  :src="character.thumbnailUrl"
                  :alt="''"
                  class="story-panel__card-image"
                >
                <div v-else class="story-panel__card-thumb-fallback">
                  <q-icon name="person" size="20px" color="grey-7" />
                </div>
              </div>
              <div class="story-panel__card-body">
                <div class="story-panel__card-title ellipsis">{{ character.displayName || '未命名角色' }}</div>
                <div class="story-panel__card-meta">
                  <span class="story-panel__card-role">{{ character.role || '未指定' }}</span>
                </div>
              </div>
            </button>
          </div>
          <p
            v-else
            class="story-panel__rail-empty"
            :aria-label="'暂无角色'"
          >
            <q-icon name="person" size="16px" color="grey-7" />
            <span>暂无角色</span>
          </p>
        </div>

        <div class="story-panel__rail-section">
          <header class="story-panel__rail-header">
            <h3 class="story-panel__rail-title">场景</h3>
            <span class="story-panel__rail-count">{{ bible?.scenes.length ?? 0 }}</span>
          </header>
          <div
            v-if="bible && bible.scenes.length > 0"
            class="story-panel__cards"
            role="list"
            aria-label="'圣经场景'"
          >
            <button
              v-for="scene in bible.scenes"
              :key="scene.id"
              type="button"
              role="listitem"
              class="story-panel__card"
              :class="{
                'story-panel__card--active': currentSceneId === scene.id,
              }"
              :aria-pressed="currentSceneId === scene.id"
              :aria-label="`选择场景 ${scene.displayName}`"
              @click="handleSceneSelect(scene.id)"
            >
              <div class="story-panel__card-thumb" aria-hidden="true">
                <img
                  v-if="scene.thumbnailUrl"
                  :src="scene.thumbnailUrl"
                  :alt="''"
                  class="story-panel__card-image"
                >
                <div v-else class="story-panel__card-thumb-fallback">
                  <q-icon name="landscape" size="20px" color="grey-7" />
                </div>
              </div>
              <div class="story-panel__card-body">
                <div class="story-panel__card-title ellipsis">{{ scene.displayName || '未命名场景' }}</div>
                <div class="story-panel__card-meta">
                  <span class="story-panel__card-role">{{ scene.type || '未指定' }}</span>
                </div>
              </div>
            </button>
          </div>
          <p
            v-else
            class="story-panel__rail-empty"
            :aria-label="'暂无场景'"
          >
            <q-icon name="landscape" size="16px" color="grey-7" />
            <span>暂无场景</span>
          </p>
        </div>

        <div class="story-panel__rail-section">
          <header class="story-panel__rail-header">
            <h3 class="story-panel__rail-title">风格</h3>
            <span class="story-panel__rail-count">{{ bible?.styleSeeds.length ?? 0 }}</span>
          </header>
          <div
            v-if="bible && bible.styleSeeds.length > 0"
            class="story-panel__seed-list"
            role="list"
            aria-label="'风格种子'"
          >
            <button
              v-for="seed in bible.styleSeeds"
              :key="seed.id"
              type="button"
              role="listitem"
              class="story-panel__seed"
              :class="{
                'story-panel__seed--active': selectedStyleSeedId === seed.id,
              }"
              :aria-pressed="selectedStyleSeedId === seed.id"
              :aria-label="`选择风格 ${seed.displayName}`"
              @click="handleStyleSeedSelect(seed.id)"
            >
              <q-icon
                :name="selectedStyleSeedId === seed.id ? 'auto_awesome' : 'palette'"
                size="14px"
                class="story-panel__seed-icon"
              />
              <span class="story-panel__seed-label ellipsis">{{ seed.displayName || '未命名' }}</span>
            </button>
          </div>
          <p
            v-else
            class="story-panel__rail-empty"
            :aria-label="'暂无风格种子'"
          >
            <q-icon name="palette" size="16px" color="grey-7" />
            <span>暂无风格</span>
          </p>
        </div>
      </aside>

      <!-- CENTER: scene strip + shot rail ─────────────────────────────── -->
      <section
        class="story-panel__episode"
        :aria-label="currentEpisode ? `集数 ${currentEpisode.title || currentEpisode.id} 镜头列表` : '镜头列表'"
      >
        <header class="story-panel__episode-header">
          <div class="story-panel__episode-title-block">
            <h3 class="story-panel__episode-title">
              <span
                v-if="currentEpisode"
                class="story-panel__episode-num"
                :aria-label="`集数编号 ${currentEpisode.episodeNumber}`"
              >EP{{ String(currentEpisode.episodeNumber).padStart(2, '0') }}</span>
              <span class="story-panel__episode-name">
                {{ currentEpisode?.title || '未命名集数' }}
              </span>
            </h3>
            <p
              v-if="currentEpisode?.logline"
              class="story-panel__episode-logline"
            >{{ currentEpisode.logline }}</p>
          </div>
          <div class="story-panel__episode-meta">
            <span
              v-if="currentEpisode"
              class="story-panel__episode-metric"
              :aria-label="`${currentEpisode.shotCount ?? shots.length} 个镜头`"
            >
              <q-icon name="movie_creation" size="14px" />
              {{ currentEpisode.shotCount ?? shots.length }} 镜头
            </span>
            <span
              v-if="currentEpisode?.durationEstimate"
              class="story-panel__episode-metric"
              :aria-label="`预计时长 ${currentEpisode.durationEstimate} 秒`"
            >
              <q-icon name="schedule" size="14px" />
              {{ currentEpisode.durationEstimate }}s
            </span>
          </div>
        </header>

        <!-- Scene strip (pills) -->
        <div
          v-if="episodeScenes.length > 0"
          class="story-panel__scene-strip"
          role="tablist"
          aria-label="'场景筛选'"
        >
          <button
            type="button"
            role="tab"
            class="story-panel__scene-pill"
            :class="{ 'story-panel__scene-pill--active': selectedSceneIdFromShot === null }"
            :aria-selected="selectedSceneIdFromShot === null"
            :aria-label="'显示全部场景的镜头'"
            @click="handleSceneFilterClear"
          >
            全部 · {{ shots.length }}
          </button>
          <button
            v-for="scene in episodeScenes"
            :key="scene.id"
            type="button"
            role="tab"
            class="story-panel__scene-pill"
            :class="{
              'story-panel__scene-pill--active': selectedSceneIdFromShot === scene.id,
            }"
            :aria-selected="selectedSceneIdFromShot === scene.id"
            :aria-label="`仅显示 ${scene.displayName} 的镜头`"
            @click="handleSceneFilterSelect(scene.id)"
          >
            <span class="story-panel__scene-pill-name ellipsis">{{ scene.displayName }}</span>
            <span class="story-panel__scene-pill-count">{{ shotCountByScene[scene.id] ?? 0 }}</span>
          </button>
        </div>

        <!-- Shot list (contact-sheet) -->
        <div
          v-if="filteredShots.length > 0"
          class="story-panel__shot-rail"
          role="listbox"
          aria-label="'镜头列表'"
        >
          <button
            v-for="shot in filteredShots"
            :key="shot.id"
            type="button"
            role="option"
            class="story-panel__shot"
            :class="{
              'story-panel__shot--active': currentShotId === shot.id,
            }"
            :aria-selected="currentShotId === shot.id"
            :aria-label="`镜头 ${String(shot.shotNumber).padStart(2, '0')} — ${shot.description || '未命名镜头'}`"
            @click="handleShotSelect(shot.id)"
          >
            <span class="story-panel__shot-index" aria-hidden="true">
              {{ String(shot.shotNumber).padStart(2, '0') }}
            </span>
            <span class="story-panel__shot-body">
              <span class="story-panel__shot-title ellipsis">
                {{ shot.description || shot.visualPrompt || '未命名镜头' }}
              </span>
              <span class="story-panel__shot-meta">
                <span
                  class="story-panel__shot-status"
                  :class="`story-panel__shot-status--${shot.status}`"
                >{{ shotStatusLabel(shot.status) }}</span>
                <span
                  v-if="shot.latestRunId"
                  class="story-panel__shot-run"
                  :aria-label="`最近运行 ${shot.latestRunId}`"
                >↻ {{ shot.latestRunId }}</span>
              </span>
            </span>
          </button>
        </div>

        <div
          v-else-if="shots.length > 0 && filteredShots.length === 0"
          class="story-panel__rail-empty story-panel__rail-empty--centered"
          :aria-label="'当前场景筛选下无镜头'"
        >
          <q-icon name="movie_filter" size="16px" color="grey-7" />
          <span>该场景下暂无镜头 — 切换或清除筛选</span>
        </div>

        <div
          v-else
          class="story-panel__rail-empty story-panel__rail-empty--centered"
          :aria-label="'当前集数暂无镜头'"
        >
          <q-icon name="movie_creation" size="16px" color="grey-7" />
          <span>当前集数暂无镜头 — 由 Agent 写入 episode JSON</span>
        </div>
      </section>

      <!-- RIGHT: shot detail (description / dialogue / refs / workflow) -->
      <aside
        class="story-panel__detail"
        :aria-label="selectedShot ? '镜头详情' : '镜头详情（未选中）'"
        role="complementary"
      >
        <template v-if="selectedShot">
          <header class="story-panel__detail-header">
            <div class="story-panel__detail-title-block">
              <span class="story-panel__detail-eyebrow">镜头详情</span>
              <h3 class="story-panel__detail-title">
                SHOT {{ String(selectedShot.shotNumber).padStart(2, '0') }}
              </h3>
            </div>
            <span
              class="story-panel__detail-status"
              :class="`story-panel__detail-status--${selectedShot.status}`"
              :aria-label="`当前状态 — ${shotStatusLabel(selectedShot.status)}`"
            >
              <span class="story-panel__detail-status-dot" aria-hidden="true" />
              {{ shotStatusLabel(selectedShot.status) }}
            </span>
          </header>

          <div class="story-panel__detail-body">
            <section
              v-if="selectedShot.description"
              class="story-panel__detail-section"
              :aria-label="'镜头描述'"
            >
              <h4 class="story-panel__detail-section-title">描述</h4>
              <p class="story-panel__detail-prose">{{ selectedShot.description }}</p>
            </section>

            <section
              v-if="selectedShot.visualPrompt"
              class="story-panel__detail-section"
              :aria-label="'视觉提示词'"
            >
              <h4 class="story-panel__detail-section-title">视觉提示词</h4>
              <p class="story-panel__detail-prompt">{{ selectedShot.visualPrompt }}</p>
            </section>

            <section
              v-if="dialogLines.length > 0"
              class="story-panel__detail-section"
              :aria-label="'对白'"
            >
              <h4 class="story-panel__detail-section-title">对白</h4>
              <ul class="story-panel__dialog" role="list">
                <li
                  v-for="(line, index) in dialogLines"
                  :key="`${line.characterId}-${index}`"
                  class="story-panel__dialog-line"
                  role="listitem"
                >
                  <span
                    class="story-panel__dialog-character"
                    :aria-label="`角色 ${line.characterId}`"
                  >{{ line.characterId }}</span>
                  <span v-if="line.emotion" class="story-panel__dialog-emotion">
                    [{{ line.emotion }}]
                  </span>
                  <p class="story-panel__dialog-text">{{ line.text }}</p>
                </li>
              </ul>
            </section>

            <section
              v-if="cameraAndLighting.length > 0"
              class="story-panel__detail-section"
              :aria-label="'摄影与灯光备注'"
            >
              <h4 class="story-panel__detail-section-title">摄影 · 灯光</h4>
              <dl class="story-panel__kv">
                <div
                  v-for="entry in cameraAndLighting"
                  :key="entry.key"
                  class="story-panel__kv-row"
                >
                  <dt class="story-panel__kv-key">{{ entry.key }}</dt>
                  <dd class="story-panel__kv-value">{{ entry.value }}</dd>
                </div>
              </dl>
            </section>

            <section
              v-if="selectedShot.characterIds.length > 0"
              class="story-panel__detail-section"
              :aria-label="'登场角色'"
            >
              <h4 class="story-panel__detail-section-title">角色</h4>
              <div class="story-panel__chip-row">
                <span
                  v-for="charId in selectedShot.characterIds"
                  :key="charId"
                  class="story-panel__chip story-panel__chip--character"
                >{{ characterNameById[charId] ?? charId }}</span>
              </div>
            </section>

            <section
              v-if="selectedShot.referenceArtifactIds.length > 0"
              class="story-panel__detail-section"
              :aria-label="'参考制品'"
            >
              <h4 class="story-panel__detail-section-title">参考制品</h4>
              <div class="story-panel__chip-row">
                <button
                  v-for="artifactId in selectedShot.referenceArtifactIds"
                  :key="artifactId"
                  type="button"
                  class="story-panel__chip story-panel__chip--button"
                  :aria-label="`打开制品 ${artifactId}`"
                  @click="handleArtifactOpen(artifactId)"
                >
                  <q-icon name="image" size="12px" />
                  <span class="ellipsis">{{ artifactId }}</span>
                </button>
              </div>
            </section>

            <!-- Workflow step + runs for the selected shot -->
            <section
              v-if="shotWorkflowNodes.length > 0"
              class="story-panel__detail-section"
              :aria-label="'工作流节点'"
            >
              <h4 class="story-panel__detail-section-title">工作流</h4>
              <ol class="story-panel__workflow" role="list">
                <li
                  v-for="node in shotWorkflowNodes"
                  :key="node.id"
                  class="story-panel__workflow-node"
                  role="listitem"
                >
                  <div class="story-panel__workflow-row">
                    <span
                      class="story-panel__workflow-tool"
                      :class="`story-panel__workflow-tool--${node.toolKind}`"
                    >{{ node.toolKind }}</span>
                    <span
                      class="story-panel__workflow-label ellipsis"
                    >{{ node.label }}</span>
                  </div>
                  <p
                    v-if="node.promptTemplate"
                    class="story-panel__workflow-prompt ellipsis-2"
                    :aria-label="'提示词模板'"
                  >{{ node.promptTemplate }}</p>
                  <p
                    v-if="node.dependsOn.length > 0"
                    class="story-panel__workflow-deps"
                    :aria-label="`依赖 ${node.dependsOn.length} 个上游节点`"
                  >
                    <q-icon name="account_tree" size="12px" />
                    依赖 {{ node.dependsOn.length }} 个节点
                  </p>
                </li>
              </ol>
            </section>

            <section
              v-if="shotRuns.length > 0"
              class="story-panel__detail-section"
              :aria-label="'运行历史'"
            >
              <h4 class="story-panel__detail-section-title">运行</h4>
              <ol class="story-panel__runs" role="list">
                <li
                  v-for="run in shotRuns"
                  :key="run.id"
                  class="story-panel__run"
                  role="listitem"
                >
                  <div class="story-panel__run-row">
                    <span
                      class="story-panel__run-status"
                      :class="`story-panel__run-status--${run.status}`"
                    >{{ runStatusLabel(run.status) }}</span>
                    <span class="story-panel__run-id">{{ run.id }}</span>
                  </div>
                  <p
                    v-if="run.model"
                    class="story-panel__run-model"
                    :aria-label="`使用模型 ${run.model}`"
                  >{{ run.model }}</p>
                </li>
              </ol>
            </section>
          </div>

          <footer class="story-panel__detail-actions" :aria-label="'未来可执行操作（当前只读）'">
            <button
              type="button"
              class="story-panel__action story-panel__action--ghost"
              :aria-label="`编辑镜头 ${selectedShot.id}（待接入）`"
              @click="handleShotEdit"
            >
              <q-icon name="edit" size="14px" />
              <span>编辑</span>
            </button>
            <button
              type="button"
              class="story-panel__action story-panel__action--primary"
              :aria-label="`重新生成镜头 ${selectedShot.id}（待接入）`"
              @click="handleShotRegenerate"
            >
              <q-icon name="refresh" size="14px" />
              <span>重新生成</span>
            </button>
          </footer>
        </template>

        <div
          v-else
          class="story-panel__detail-empty"
          :aria-label="'请选择镜头以查看详情'"
        >
          <q-icon name="touch_app" size="22px" color="grey-6" />
          <p class="story-panel__detail-empty-title">选择左侧镜头</p>
          <p class="story-panel__detail-empty-hint">
            点击镜头列表中的任意条目，查看描述、对白、参考与运行历史。
          </p>
        </div>
      </aside>
    </div>

    <!-- ── Loading / Error overlay ────────────────────────────────────── -->
    <div
      v-if="isLoading"
      class="story-panel__overlay story-panel__overlay--loading"
      role="status"
      aria-live="polite"
    >
      <q-spinner-dots size="28px" color="cyan-5" />
      <span>加载故事数据…</span>
    </div>

    <div
      v-if="errorMessage"
      class="story-panel__overlay story-panel__overlay--error"
      role="alert"
    >
      <q-icon name="error_outline" size="20px" color="negative" />
      <span>{{ errorMessage }}</span>
    </div>
  </section>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import type {
  StoryBibleSummary,
  StoryEditIntent,
  StoryEpisodeSummary,
  StoryRunSummary,
  StorySceneSummary,
  StorySelection,
  StoryShotSummary,
  StoryWorkflowNodeSummary,
} from './types'

// ── Props ────────────────────────────────────────────────────────────────────

const props = withDefaults(
  defineProps<{
    /** Read-only series/episode index. */
    seriesTitle?: string
    seriesDescription?: string
    /** All episodes in the series (index order = display order). */
    episodes?: StoryEpisodeSummary[]
    /** Currently focused episode (must exist in `episodes` when provided). */
    currentEpisodeId?: string | null
    /** Currently focused shot (must exist in current episode's shots). */
    currentShotId?: string | null
    /** Currently focused scene from the bible (independent of shot selection). */
    currentSceneId?: string | null
    /** Shots of the current episode, pre-derived by the page from episode JSON. */
    shots?: StoryShotSummary[]
    /** Optional workflow nodes for the current episode. */
    workflowNodes?: StoryWorkflowNodeSummary[]
    /** Optional run history for the current episode. */
    runs?: StoryRunSummary[]
    /** Optional bible summary — when absent, panel renders the "missing bible" empty state. */
    bible?: StoryBibleSummary | null
    /** Externally selected character id (optional, used to highlight the rail). */
    selectedCharacterId?: string | null
    /** Externally selected style seed id (optional, used to highlight the rail). */
    selectedStyleSeedId?: string | null
    /** Loading state for the whole panel. */
    isLoading?: boolean
    /** Error message to surface as a non-blocking alert. */
    errorMessage?: string | null
  }>(),
  {
    seriesTitle: '',
    seriesDescription: '',
    episodes: () => [],
    currentEpisodeId: null,
    currentShotId: null,
    currentSceneId: null,
    shots: () => [],
    workflowNodes: () => [],
    runs: () => [],
    bible: null,
    selectedCharacterId: null,
    selectedStyleSeedId: null,
    isLoading: false,
    errorMessage: null,
  },
)

const emit = defineEmits<{
  (e: 'select', selection: StorySelection): void
  (e: 'episode-change', episodeId: string): void
  (e: 'intent', intent: StoryEditIntent): void
}>()

// ── Local UI state ───────────────────────────────────────────────────────────

/** Local copy of the selected episode — keeps the <select> in sync when prop changes. */
const selectedEpisodeIdModel = ref<string>('')

/** Scene filter for the shot rail (null = show all). */
const sceneFilter = ref<string | null>(null)

// ── Derived ─────────────────────────────────────────────────────────────────

const SPROCKET_COUNT = 28

/** q-select options for the episode picker — same label/value shape the native
 *  <option>s produced (value = episode id). */
const episodeSelectOptions = computed(() =>
  props.episodes.map((episode) => ({
    label: `EP${String(episode.episodeNumber).padStart(2, '0')} · ${episode.title || '未命名'}`,
    value: episode.id,
  })),
)

const ariaLabel = computed(() => {
  const ep = currentEpisode.value
  if (!ep) return '故事工作台'
  return `故事工作台 — ${props.seriesTitle || '未命名系列'} · EP${String(ep.episodeNumber).padStart(2, '0')}`
})

const currentEpisode = computed<StoryEpisodeSummary | null>(() => {
  const id = selectedEpisodeIdModel.value
  if (!id) return null
  return props.episodes.find((ep) => ep.id === id) ?? null
})

/** All distinct scene IDs referenced by the current episode's shots, joined with
 *  bible scene summaries (when the bible is loaded) so the strip has labels. */
const episodeScenes = computed<StorySceneSummary[]>(() => {
  const sceneIds = new Set<string>()
  for (const shot of props.shots) {
    if (shot.sceneId) sceneIds.add(shot.sceneId)
  }
  if (props.bible) {
    return props.bible.scenes.filter((scene) => sceneIds.has(scene.id))
  }
  // No bible — synthesize minimal placeholders so the strip still renders.
  return Array.from(sceneIds).map((id) => ({
    id,
    displayName: id,
    type: 'unspecified',
    description: '',
    mood: '',
    lighting: '',
    thumbnailUrl: null,
    referenceArtifactIds: [],
    tags: [],
  }))
})

const shotCountByScene = computed<Record<string, number>>(() => {
  const out: Record<string, number> = {}
  for (const shot of props.shots) {
    out[shot.sceneId] = (out[shot.sceneId] ?? 0) + 1
  }
  return out
})

const filteredShots = computed<StoryShotSummary[]>(() => {
  const filter = sceneFilter.value
  if (!filter) return props.shots
  return props.shots.filter((shot) => shot.sceneId === filter)
})

const selectedShot = computed<StoryShotSummary | null>(() => {
  const id = props.currentShotId
  if (!id) return null
  return props.shots.find((shot) => shot.id === id) ?? null
})

const selectedSceneIdFromShot = computed<string | null>(() => {
  if (sceneFilter.value) return sceneFilter.value
  if (selectedShot.value) return selectedShot.value.sceneId
  return null
})

const dialogLines = computed(() => selectedShot.value?.dialog ?? [])

const cameraAndLighting = computed<{ key: string; value: string }[]>(() => {
  const shot = selectedShot.value
  if (!shot) return []
  const rows: { key: string; value: string }[] = []
  if (shot.cameraNotes) rows.push({ key: '摄影', value: shot.cameraNotes })
  if (shot.lightingNotes) rows.push({ key: '灯光', value: shot.lightingNotes })
  if (shot.durationEstimate) {
    rows.push({ key: '时长', value: `${shot.durationEstimate}s` })
  }
  return rows
})

const characterNameById = computed<Record<string, string>>(() => {
  if (!props.bible) return {}
  const out: Record<string, string> = {}
  for (const ch of props.bible.characters) {
    out[ch.id] = ch.displayName
  }
  return out
})

const shotWorkflowNodes = computed<StoryWorkflowNodeSummary[]>(() => {
  const shot = selectedShot.value
  if (!shot) return []
  return props.workflowNodes.filter((node) => node.shotId === shot.id)
})

const shotRuns = computed<StoryRunSummary[]>(() => {
  const shot = selectedShot.value
  if (!shot) return []
  return props.runs.filter((run) => run.shotId === shot.id)
})

const worldChipCount = computed<number>(() => {
  if (!props.bible) return 0
  return props.bible.moodKeywords.length
})

// ── Watchers (keep internal state in sync with prop changes) ────────────────

watch(
  () => props.currentEpisodeId,
  (next) => {
    if (next) selectedEpisodeIdModel.value = next
  },
  { immediate: true },
)

// Reset scene filter when the user switches episodes
watch(
  () => selectedEpisodeIdModel.value,
  () => {
    sceneFilter.value = null
  },
)

// ── Event handlers (named, not inline) ───────────────────────────────────────

function handleEpisodeChange(episodeId: string): void {
  if (!episodeId) return
  selectedEpisodeIdModel.value = episodeId
  sceneFilter.value = null
  emit('episode-change', episodeId)
  emit('select', { kind: 'episode', id: episodeId })
}

function handleShotSelect(shotId: string): void {
  emit('select', { kind: 'shot', id: shotId })
}

function handleSceneFilterSelect(sceneId: string): void {
  sceneFilter.value = sceneId
}

function handleSceneFilterClear(): void {
  sceneFilter.value = null
}

function handleCharacterSelect(characterId: string): void {
  emit('select', { kind: 'character', id: characterId })
}

function handleSceneSelect(sceneId: string): void {
  emit('select', { kind: 'scene', id: sceneId })
}

function handleStyleSeedSelect(seedId: string): void {
  emit('select', { kind: 'styleSeed', id: seedId })
}

function handleArtifactOpen(artifactId: string): void {
  const ep = currentEpisode.value
  if (!ep) return
  emit('intent', { kind: 'open-artifact', episodeId: ep.id, artifactId })
}

function handleShotEdit(): void {
  const ep = currentEpisode.value
  const shot = selectedShot.value
  if (!ep || !shot) return
  // TODO (openimago-9so): wire the edit-shot intent to the prompt editor
  emit('intent', { kind: 'edit-shot', episodeId: ep.id, shotId: shot.id })
}

function handleShotRegenerate(): void {
  const ep = currentEpisode.value
  const shot = selectedShot.value
  if (!ep || !shot) return
  // TODO (openimago-9so): wire the regenerate-shot intent to the workflow runner
  emit('intent', { kind: 'regenerate-shot', episodeId: ep.id, shotId: shot.id })
}

// ── Label helpers (UI-side mapping of status enums) ──────────────────────────

function episodeStatusLabel(status: StoryEpisodeSummary['status']): string {
  switch (status) {
    case 'draft': return '草稿'
    case 'storyboard': return '分镜'
    case 'generating': return '生成中'
    case 'review': return '审核中'
    case 'done': return '完成'
    default: return String(status)
  }
}

function shotStatusLabel(status: StoryShotSummary['status']): string {
  switch (status) {
    case 'pending': return '待生成'
    case 'in_progress': return '生成中'
    case 'generated': return '已生成'
    case 'review': return '审核中'
    case 'approved': return '已通过'
    default: return String(status)
  }
}

function runStatusLabel(status: StoryRunSummary['status']): string {
  switch (status) {
    case 'queued': return '排队'
    case 'running': return '运行中'
    case 'completed': return '完成'
    case 'failed': return '失败'
    default: return String(status)
  }
}
</script>

<style lang="scss" scoped>
//
// ── All colors / radii / motion sourced from --imago-* tokens ───────────────
// (defined in packages/web/src/css/app.scss). No hardcoded values introduced.
//

.story-panel {
  position: relative;
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
  min-height: 0;
  background: var(--imago-bg-void);
  color: var(--imago-text-primary);
  border: 1px solid var(--imago-border-light);
  border-radius: var(--imago-radius-xl);
  overflow: hidden;
  isolation: isolate;
}

// ── Sprocket strip (film perforations along the hero) ────────────────────────
.story-panel__sprocket {
  position: relative;
  display: flex;
  align-items: center;
  gap: 10px;
  height: 14px;
  padding: 0 18px;
  background: var(--imago-bg-deep);
  border-bottom: 1px solid var(--imago-border-subtle);
  overflow: hidden;
}

.story-panel__perf {
  flex: 1 1 0;
  min-width: 14px;
  max-width: 28px;
  height: 6px;
  border-radius: 2px;
  background: var(--imago-bg-void);
  border: 1px solid var(--imago-border-soft);
  box-shadow: inset 0 0 2px rgba(0, 240, 255, 0.05);
}

// ── Hero (series + episode selector) ─────────────────────────────────────────
.story-panel__hero {
  position: relative;
  display: flex;
  align-items: flex-end;
  justify-content: space-between;
  gap: 16px;
  padding: 18px 22px 16px;
  border-bottom: 1px solid var(--imago-border-light);
  background:
    linear-gradient(180deg, rgba(0, 240, 255, 0.04), transparent 80%),
    var(--imago-bg-deep);

  &::after {
    content: '';
    position: absolute;
    left: 22px;
    right: 22px;
    bottom: -1px;
    height: 1px;
    background: linear-gradient(90deg, transparent, var(--imago-border-cyan) 30%, var(--imago-border-cyan) 70%, transparent);
    opacity: 0.5;
  }
}

.story-panel__hero-text {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.story-panel__eyebrow {
  margin: 0;
  font-size: 10.5px;
  font-weight: 600;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--imago-text-dim);
}

.story-panel__title {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
  color: var(--imago-text-primary);
  letter-spacing: -0.01em;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.story-panel__subtitle {
  margin: 0;
  font-size: 12px;
  color: var(--imago-text-dim);
  line-height: 1.5;
  display: -webkit-box;
  -webkit-line-clamp: 1;
  -webkit-box-orient: vertical;
  overflow: hidden;
  max-width: 56ch;
}

.story-panel__episode-picker {
  display: flex;
  align-items: center;
  gap: 10px;
  flex-shrink: 0;
}

.story-panel__picker-label {
  font-size: 10.5px;
  font-weight: 600;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--imago-text-dim);
}

.story-panel__select-wrap {
  position: relative;
  display: inline-flex;
  align-items: center;
}

// ── Episode picker (Quasar q-select on the dark imago surface) ───────────────
.story-panel__q-select {
  min-width: 220px;
  max-width: 320px;

  :deep(.q-field__control) {
    border-radius: var(--imago-radius-md);
    background: var(--imago-bg-surface);
    color: var(--imago-text-primary);
    font-size: 13px;
    font-weight: 500;
  }

  &.q-field--outlined :deep(.q-field__control)::before {
    border-color: var(--imago-border-light);
  }

  &.q-field--outlined:hover :deep(.q-field__control)::before {
    border-color: var(--imago-border-cyan);
  }

  &.q-field--outlined.q-field--focused :deep(.q-field__control)::after {
    border-color: var(--imago-border-cyan-active);
  }

  &.q-field--disabled { opacity: 0.5; }

  :deep(.q-field__native),
  :deep(.q-field__append) {
    color: var(--imago-text-muted);
  }
}

.story-panel__episode-status {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 2px 8px;
  border-radius: var(--imago-radius-pill);
  font-size: 10.5px;
  font-weight: 500;
  background: var(--imago-bg-raised);
  color: var(--imago-text-muted);
  border: 1px solid var(--imago-border-light);
}

.story-panel__episode-status-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: var(--imago-text-faint);
}

.story-panel__episode-status--generating,
.story-panel__episode-status--in_progress {
  color: var(--imago-neon-cyan);
  border-color: var(--imago-border-cyan);
  background: var(--imago-cyan-06);

  .story-panel__episode-status-dot {
    background: var(--imago-neon-cyan);
    box-shadow: 0 0 6px var(--imago-cyan-08);
  }
}
.story-panel__episode-status--done,
.story-panel__episode-status--approved {
  color: var(--imago-neon-green);
  border-color: var(--imago-green-20);
  background: rgba(57, 255, 20, 0.05);
  .story-panel__episode-status-dot { background: var(--imago-neon-green); }
}
.story-panel__episode-status--review {
  color: rgba(245, 158, 11, 0.92);
  border-color: var(--imago-warning-border);
  background: var(--imago-warning-bg);
  .story-panel__episode-status-dot { background: #f59e0b; }
}

// ── Body grid: 3 columns ────────────────────────────────────────────────────
.story-panel__body {
  flex: 1;
  min-height: 0;
  display: grid;
  grid-template-columns: 240px minmax(0, 1fr) 340px;
  gap: 0;
  overflow: hidden;
}

@media (max-width: 1280px) {
  .story-panel__body {
    grid-template-columns: 220px minmax(0, 1fr) 300px;
  }
}

@media (max-width: 1024px) {
  .story-panel__body {
    grid-template-columns: 200px minmax(0, 1fr);
  }
  .story-panel__detail { display: none; }
}

@media (max-width: 768px) {
  .story-panel__body {
    grid-template-columns: 1fr;
  }
  .story-panel__bible-rail { display: none; }
}

// ── LEFT RAIL: bible ────────────────────────────────────────────────────────
.story-panel__bible-rail {
  display: flex;
  flex-direction: column;
  gap: 18px;
  padding: 16px 14px 18px 16px;
  border-right: 1px solid var(--imago-border-light);
  background: linear-gradient(180deg, var(--imago-bg-deep), var(--imago-bg-void) 30%);
  overflow-y: auto;
  min-height: 0;
}

.story-panel__rail-section {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.story-panel__rail-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 6px;
  padding: 0 2px;
}

.story-panel__rail-title {
  margin: 0;
  font-size: 10.5px;
  font-weight: 600;
  letter-spacing: 0.10em;
  text-transform: uppercase;
  color: var(--imago-text-dim);
}

.story-panel__rail-count {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 20px;
  height: 16px;
  padding: 0 5px;
  border-radius: var(--imago-radius-pill);
  font-size: 10px;
  font-weight: 600;
  color: var(--imago-text-muted);
  background: var(--imago-bg-raised);
  border: 1px solid var(--imago-border-light);
  font-variant-numeric: tabular-nums;
}

.story-panel__rail-empty {
  display: flex;
  align-items: center;
  gap: 8px;
  margin: 0;
  padding: 10px 12px;
  border: 1px dashed var(--imago-border-soft);
  border-radius: var(--imago-radius-md);
  color: var(--imago-text-faint);
  font-size: 11.5px;
  line-height: 1.4;
}

.story-panel__rail-empty--centered {
  flex-direction: column;
  text-align: center;
  padding: 24px 16px;
  gap: 6px;
  color: var(--imago-text-dim);
}

.story-panel__world-card {
  display: flex;
  flex-direction: column;
  gap: 6px;
  margin: 0;
  padding: 12px;
  border: 1px solid var(--imago-border-light);
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-surface);
}

.story-panel__world-name {
  font-size: 13px;
  font-weight: 600;
  color: var(--imago-text-primary);
}

.story-panel__world-era {
  font-size: 10.5px;
  font-weight: 500;
  letter-spacing: 0.04em;
  color: var(--imago-text-muted);
}

.story-panel__world-desc {
  margin: 0;
  font-size: 12px;
  color: var(--imago-text-dim);
  line-height: 1.5;
}

.story-panel__world-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  margin-top: 2px;
}

.story-panel__world-tag {
  padding: 1px 6px;
  border-radius: var(--imago-radius-pill);
  font-size: 10px;
  font-weight: 500;
  background: var(--imago-cyan-06);
  color: var(--imago-neon-cyan);
  border: 1px solid var(--imago-border-cyan);
}

.story-panel__cards {
  display: grid;
  grid-template-columns: 1fr;
  gap: 6px;
}

.story-panel__card {
  display: flex;
  align-items: stretch;
  gap: 8px;
  padding: 6px;
  border: 1px solid var(--imago-border-light);
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-surface);
  text-align: left;
  cursor: pointer;
  transition: border-color var(--imago-ease-fast), background var(--imago-ease-fast);

  &:hover {
    border-color: var(--imago-border-cyan);
    background: var(--imago-bg-raised);
  }
  &:focus-visible {
    outline: 2px solid var(--imago-neon-cyan);
    outline-offset: 2px;
  }
}

.story-panel__card--active {
  border-color: var(--imago-border-cyan-active);
  background: var(--imago-cyan-04);
  box-shadow: inset 0 0 0 1px var(--imago-border-cyan);
}

.story-panel__card-thumb {
  flex-shrink: 0;
  width: 40px;
  aspect-ratio: 1 / 1;
  overflow: hidden;
  border-radius: var(--imago-radius-sm);
  background: var(--imago-bg-code);
  border: 1px solid var(--imago-border-subtle);
}

.story-panel__card-image {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.story-panel__card-thumb-fallback {
  width: 100%;
  height: 100%;
  display: grid;
  place-items: center;
  background: linear-gradient(135deg, var(--imago-bg-deep), var(--imago-bg-panel));
}

.story-panel__card-body {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
  justify-content: center;
}

.story-panel__card-title {
  font-size: 12.5px;
  font-weight: 500;
  color: var(--imago-text-primary);
  line-height: 1.3;
}

.story-panel__card-meta {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 10.5px;
  color: var(--imago-text-faint);
}

.story-panel__card-role {
  color: var(--imago-text-muted);
  font-weight: 500;
  text-transform: capitalize;
}

.story-panel__seed-list {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.story-panel__seed {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 8px;
  border: 1px solid transparent;
  border-radius: var(--imago-radius-sm);
  background: transparent;
  color: var(--imago-text-secondary);
  font-size: 12px;
  text-align: left;
  cursor: pointer;
  transition: border-color var(--imago-ease-fast), background var(--imago-ease-fast), color var(--imago-ease-fast);

  &:hover {
    color: var(--imago-text-primary);
    background: var(--imago-bg-raised);
    border-color: var(--imago-border-soft);
  }
  &:focus-visible {
    outline: 2px solid var(--imago-neon-cyan);
    outline-offset: 2px;
  }
}

.story-panel__seed--active {
  color: var(--imago-neon-cyan);
  background: var(--imago-cyan-06);
  border-color: var(--imago-border-cyan);
}

.story-panel__seed-icon { opacity: 0.8; }
.story-panel__seed-label { flex: 1; min-width: 0; }

// ── CENTER: episode / scene strip / shot rail ────────────────────────────────
.story-panel__episode {
  display: flex;
  flex-direction: column;
  min-height: 0;
  border-right: 1px solid var(--imago-border-light);
  background: var(--imago-bg-void);
}

.story-panel__episode-header {
  display: flex;
  align-items: flex-end;
  justify-content: space-between;
  gap: 12px;
  padding: 14px 18px 8px;
  border-bottom: 1px solid var(--imago-border-subtle);
}

.story-panel__episode-title-block { min-width: 0; }

.story-panel__episode-title {
  display: flex;
  align-items: baseline;
  gap: 8px;
  margin: 0;
  font-size: 15px;
  font-weight: 600;
  color: var(--imago-text-primary);
  letter-spacing: -0.005em;
}

.story-panel__episode-num {
  font-family: var(--imago-font-mono, ui-monospace, SFMono-Regular, monospace);
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.08em;
  color: var(--imago-neon-cyan);
  padding: 1px 6px;
  border-radius: var(--imago-radius-sm);
  background: var(--imago-cyan-06);
  border: 1px solid var(--imago-border-cyan);
}

.story-panel__episode-name {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 32ch;
}

.story-panel__episode-logline {
  margin: 4px 0 0;
  font-size: 12px;
  color: var(--imago-text-dim);
  line-height: 1.5;
  display: -webkit-box;
  -webkit-line-clamp: 1;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.story-panel__episode-meta {
  display: flex;
  align-items: center;
  gap: 12px;
  flex-shrink: 0;
  font-size: 11.5px;
  color: var(--imago-text-muted);
}

.story-panel__episode-metric {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-variant-numeric: tabular-nums;
}

// ── Scene strip ─────────────────────────────────────────────────────────────
.story-panel__scene-strip {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 10px 18px 8px;
  border-bottom: 1px solid var(--imago-border-subtle);
  overflow-x: auto;
  scrollbar-width: none;
  &::-webkit-scrollbar { display: none; }
}

.story-panel__scene-pill {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  flex-shrink: 0;
  padding: 5px 10px;
  border: 1px solid var(--imago-border-light);
  border-radius: var(--imago-radius-pill);
  background: var(--imago-bg-raised);
  color: var(--imago-text-secondary);
  font-size: 11.5px;
  font-weight: 500;
  cursor: pointer;
  white-space: nowrap;
  transition: border-color var(--imago-ease-fast), background var(--imago-ease-fast), color var(--imago-ease-fast);

  &:hover {
    color: var(--imago-text-primary);
    border-color: var(--imago-border-cyan);
  }
  &:focus-visible {
    outline: 2px solid var(--imago-neon-cyan);
    outline-offset: 2px;
  }
}

.story-panel__scene-pill--active {
  color: var(--imago-neon-cyan);
  background: var(--imago-cyan-06);
  border-color: var(--imago-border-cyan-active);
  box-shadow: var(--imago-glow-cyan-inline);
}

.story-panel__scene-pill-name {
  max-width: 14ch;
}

.story-panel__scene-pill-count {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 18px;
  height: 16px;
  padding: 0 5px;
  border-radius: var(--imago-radius-pill);
  font-size: 10px;
  font-weight: 600;
  background: var(--imago-bg-deep);
  color: var(--imago-text-muted);
  border: 1px solid var(--imago-border-subtle);
  font-variant-numeric: tabular-nums;
}

.story-panel__scene-pill--active .story-panel__scene-pill-count {
  color: var(--imago-neon-cyan);
  border-color: var(--imago-border-cyan);
}

// ── Shot rail (contact-sheet) ────────────────────────────────────────────────
.story-panel__shot-rail {
  flex: 1;
  min-height: 0;
  overflow-y: auto;
  padding: 8px 12px 18px 18px;
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.story-panel__shot {
  display: flex;
  align-items: stretch;
  gap: 12px;
  padding: 10px 12px;
  border: 1px solid var(--imago-border-light);
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-surface);
  text-align: left;
  cursor: pointer;
  transition: border-color var(--imago-ease-default), background var(--imago-ease-default),
    box-shadow var(--imago-ease-default), transform var(--imago-ease-default);

  &:hover {
    border-color: var(--imago-border-cyan);
    background: var(--imago-bg-raised);
    transform: translateX(2px);
  }
  &:focus-visible {
    outline: 2px solid var(--imago-neon-cyan);
    outline-offset: 2px;
  }
}

.story-panel__shot--active {
  border-color: var(--imago-border-cyan-active);
  background: var(--imago-cyan-04);
  box-shadow: inset 0 0 0 1px var(--imago-border-cyan), var(--imago-glow-cyan-soft);
  transform: translateX(2px);
}

.story-panel__shot-index {
  flex-shrink: 0;
  width: 36px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-family: var(--imago-font-mono, ui-monospace, SFMono-Regular, monospace);
  font-size: 13px;
  font-weight: 600;
  color: var(--imago-text-muted);
  border-right: 1px solid var(--imago-border-subtle);
  font-variant-numeric: tabular-nums;
  letter-spacing: 0.04em;
}

.story-panel__shot--active .story-panel__shot-index {
  color: var(--imago-neon-cyan);
  border-right-color: var(--imago-border-cyan);
  text-shadow: var(--imago-glow-cyan-text);
}

.story-panel__shot-body {
  min-width: 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.story-panel__shot-title {
  font-size: 12.5px;
  font-weight: 500;
  color: var(--imago-text-primary);
  line-height: 1.4;
}

.story-panel__shot-meta {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 10.5px;
  color: var(--imago-text-faint);
}

.story-panel__shot-status {
  display: inline-flex;
  align-items: center;
  padding: 1px 6px;
  border-radius: var(--imago-radius-pill);
  font-weight: 500;
  background: var(--imago-bg-raised);
  color: var(--imago-text-muted);
  border: 1px solid var(--imago-border-light);
}

.story-panel__shot-status--pending   { color: var(--imago-text-faint); }
.story-panel__shot-status--in_progress {
  color: var(--imago-neon-cyan);
  background: var(--imago-cyan-06);
  border-color: var(--imago-border-cyan);
}
.story-panel__shot-status--generated {
  color: var(--imago-neon-green);
  background: rgba(57, 255, 20, 0.06);
  border-color: var(--imago-green-20);
}
.story-panel__shot-status--review {
  color: rgba(245, 158, 11, 0.92);
  background: var(--imago-warning-bg);
  border-color: var(--imago-warning-border);
}
.story-panel__shot-status--approved {
  color: var(--imago-neon-green);
  background: var(--imago-cyan-04);
  border-color: var(--imago-border-cyan-active);
}

.story-panel__shot-run {
  font-family: var(--imago-font-mono, ui-monospace, SFMono-Regular, monospace);
  color: var(--imago-text-muted);
  font-variant-numeric: tabular-nums;
}

// ── RIGHT: shot detail ──────────────────────────────────────────────────────
.story-panel__detail {
  display: flex;
  flex-direction: column;
  min-height: 0;
  background: linear-gradient(180deg, var(--imago-bg-deep), var(--imago-bg-void) 30%);
}

.story-panel__detail-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 10px;
  padding: 16px 18px 10px;
  border-bottom: 1px solid var(--imago-border-subtle);
}

.story-panel__detail-title-block { min-width: 0; }

.story-panel__detail-eyebrow {
  display: block;
  font-size: 10.5px;
  font-weight: 600;
  letter-spacing: 0.10em;
  text-transform: uppercase;
  color: var(--imago-text-dim);
  margin-bottom: 4px;
}

.story-panel__detail-title {
  margin: 0;
  font-family: var(--imago-font-mono, ui-monospace, SFMono-Regular, monospace);
  font-size: 16px;
  font-weight: 600;
  color: var(--imago-text-primary);
  letter-spacing: 0.04em;
}

.story-panel__detail-status {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 3px 8px;
  border-radius: var(--imago-radius-pill);
  font-size: 10.5px;
  font-weight: 500;
  background: var(--imago-bg-raised);
  color: var(--imago-text-muted);
  border: 1px solid var(--imago-border-light);
}

.story-panel__detail-status-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: var(--imago-text-faint);
}

.story-panel__detail-status--in_progress {
  color: var(--imago-neon-cyan);
  border-color: var(--imago-border-cyan);
  background: var(--imago-cyan-06);
  .story-panel__detail-status-dot {
    background: var(--imago-neon-cyan);
    box-shadow: 0 0 6px var(--imago-cyan-08);
  }
}
.story-panel__detail-status--generated,
.story-panel__detail-status--approved {
  color: var(--imago-neon-green);
  border-color: var(--imago-green-20);
  background: rgba(57, 255, 20, 0.05);
  .story-panel__detail-status-dot { background: var(--imago-neon-green); }
}
.story-panel__detail-status--review {
  color: rgba(245, 158, 11, 0.92);
  border-color: var(--imago-warning-border);
  background: var(--imago-warning-bg);
  .story-panel__detail-status-dot { background: #f59e0b; }
}

.story-panel__detail-body {
  flex: 1;
  min-height: 0;
  overflow-y: auto;
  padding: 14px 18px 8px;
  display: flex;
  flex-direction: column;
  gap: 14px;
}

.story-panel__detail-section {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.story-panel__detail-section-title {
  margin: 0;
  font-size: 10.5px;
  font-weight: 600;
  letter-spacing: 0.10em;
  text-transform: uppercase;
  color: var(--imago-text-dim);
}

.story-panel__detail-prose,
.story-panel__detail-prompt {
  margin: 0;
  padding: 10px 12px;
  border: 1px solid var(--imago-border-light);
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-surface);
  font-size: 12.5px;
  line-height: 1.6;
  color: var(--imago-text-secondary);
  white-space: pre-wrap;
  word-break: break-word;
}

.story-panel__detail-prompt {
  font-family: var(--imago-font-mono, ui-monospace, SFMono-Regular, monospace);
  font-size: 12px;
  color: var(--imago-neon-cyan);
  background: var(--imago-cyan-04);
  border-color: var(--imago-border-cyan);
}

.story-panel__dialog {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.story-panel__dialog-line {
  padding: 8px 10px;
  border-left: 2px solid var(--imago-border-cyan);
  background: var(--imago-bg-surface);
  border-radius: 0 var(--imago-radius-sm) var(--imago-radius-sm) 0;
}

.story-panel__dialog-character {
  font-size: 11.5px;
  font-weight: 600;
  color: var(--imago-neon-cyan);
  margin-right: 6px;
}

.story-panel__dialog-emotion {
  font-size: 10.5px;
  color: var(--imago-text-faint);
  font-style: italic;
}

.story-panel__dialog-text {
  margin: 4px 0 0;
  font-size: 12.5px;
  color: var(--imago-text-primary);
  line-height: 1.5;
}

.story-panel__kv {
  display: grid;
  grid-template-columns: 1fr;
  gap: 6px;
  margin: 0;
  padding: 10px 12px;
  border: 1px solid var(--imago-border-light);
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-surface);
}

.story-panel__kv-row {
  display: grid;
  grid-template-columns: 56px 1fr;
  gap: 8px;
  align-items: baseline;
}

.story-panel__kv-key {
  margin: 0;
  font-size: 10.5px;
  font-weight: 600;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--imago-text-faint);
}

.story-panel__kv-value {
  margin: 0;
  font-size: 12.5px;
  color: var(--imago-text-secondary);
  line-height: 1.5;
}

.story-panel__chip-row {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
}

.story-panel__chip {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  padding: 2px 8px;
  border-radius: var(--imago-radius-pill);
  font-size: 11px;
  font-weight: 500;
  background: var(--imago-cyan-06);
  color: var(--imago-neon-cyan);
  border: 1px solid var(--imago-border-cyan);
  max-width: 100%;
}

.story-panel__chip--character {
  background: var(--imago-bg-raised);
  color: var(--imago-text-secondary);
  border-color: var(--imago-border-soft);
}

.story-panel__chip--button {
  cursor: pointer;
  font-family: var(--imago-font-mono, ui-monospace, SFMono-Regular, monospace);
  transition: background var(--imago-ease-fast), color var(--imago-ease-fast);

  &:hover {
    background: var(--imago-cyan-08);
    color: var(--imago-cyan-bright);
  }
  &:focus-visible {
    outline: 2px solid var(--imago-neon-cyan);
    outline-offset: 2px;
  }
}

.story-panel__workflow,
.story-panel__runs {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.story-panel__workflow-node,
.story-panel__run {
  padding: 8px 10px;
  border: 1px solid var(--imago-border-light);
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-surface);
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.story-panel__workflow-row,
.story-panel__run-row {
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 0;
}

.story-panel__workflow-tool {
  padding: 1px 6px;
  border-radius: var(--imago-radius-sm);
  font-size: 10px;
  font-weight: 600;
  letter-spacing: 0.04em;
  background: var(--imago-bg-raised);
  color: var(--imago-text-muted);
  border: 1px solid var(--imago-border-soft);
  font-family: var(--imago-font-mono, ui-monospace, SFMono-Regular, monospace);
  text-transform: lowercase;
}

.story-panel__workflow-tool--image_generate { color: var(--imago-neon-cyan); border-color: var(--imago-border-cyan); }
.story-panel__workflow-tool--video_generate  { color: var(--imago-neon-purple); border-color: var(--imago-border-purple); }
.story-panel__workflow-tool--image_edit      { color: var(--imago-neon-pink);  border-color: rgba(255, 45, 149, 0.24); }

.story-panel__workflow-label {
  flex: 1;
  min-width: 0;
  font-size: 12px;
  font-weight: 500;
  color: var(--imago-text-secondary);
}

.story-panel__workflow-prompt {
  margin: 0;
  font-family: var(--imago-font-mono, ui-monospace, SFMono-Regular, monospace);
  font-size: 11px;
  color: var(--imago-text-dim);
  line-height: 1.5;
}

.story-panel__workflow-deps {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  margin: 0;
  font-size: 10.5px;
  color: var(--imago-text-faint);
}

.story-panel__run-status {
  padding: 1px 6px;
  border-radius: var(--imago-radius-pill);
  font-size: 10px;
  font-weight: 600;
  background: var(--imago-bg-raised);
  color: var(--imago-text-muted);
  border: 1px solid var(--imago-border-light);
  letter-spacing: 0.04em;
}

.story-panel__run-status--queued   { color: var(--imago-text-muted); }
.story-panel__run-status--running  {
  color: var(--imago-neon-cyan);
  background: var(--imago-cyan-06);
  border-color: var(--imago-border-cyan);
}
.story-panel__run-status--completed {
  color: var(--imago-neon-green);
  background: rgba(57, 255, 20, 0.05);
  border-color: var(--imago-green-20);
}
.story-panel__run-status--failed {
  color: #fda4af;
  background: rgba(244, 63, 94, 0.06);
  border-color: rgba(244, 63, 94, 0.30);
}

.story-panel__run-id {
  font-family: var(--imago-font-mono, ui-monospace, SFMono-Regular, monospace);
  font-size: 10.5px;
  color: var(--imago-text-faint);
  font-variant-numeric: tabular-nums;
}

.story-panel__run-model {
  margin: 0;
  font-size: 10.5px;
  color: var(--imago-text-dim);
}

// ── Detail action footer ────────────────────────────────────────────────────
.story-panel__detail-actions {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 8px;
  padding: 10px 18px 14px;
  border-top: 1px solid var(--imago-border-subtle);
}

.story-panel__action {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 6px 12px;
  border-radius: var(--imago-radius-md);
  font-size: 12px;
  font-weight: 500;
  cursor: pointer;
  transition: background var(--imago-ease-fast), color var(--imago-ease-fast),
    border-color var(--imago-ease-fast), box-shadow var(--imago-ease-fast);
}

.story-panel__action--ghost {
  border: 1px solid var(--imago-border-light);
  background: var(--imago-bg-raised);
  color: var(--imago-text-secondary);

  &:hover {
    color: var(--imago-text-primary);
    border-color: var(--imago-border-cyan);
    background: var(--imago-cyan-04);
  }
  &:focus-visible {
    outline: 2px solid var(--imago-neon-cyan);
    outline-offset: 2px;
  }
}

.story-panel__action--primary {
  border: 1px solid var(--imago-border-cyan-active);
  background: var(--imago-cyan-06);
  color: var(--imago-neon-cyan);

  &:hover {
    background: var(--imago-cyan-08);
    box-shadow: var(--imago-glow-cyan-inline);
  }
  &:focus-visible {
    outline: 2px solid var(--imago-neon-cyan);
    outline-offset: 2px;
  }
}

.story-panel__detail-empty {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 6px;
  padding: 40px 24px;
  text-align: center;
}

.story-panel__detail-empty-title {
  margin: 8px 0 0;
  font-size: 14px;
  font-weight: 600;
  color: var(--imago-text-secondary);
}

.story-panel__detail-empty-hint {
  max-width: 280px;
  margin: 0;
  font-size: 12px;
  color: var(--imago-text-dim);
  line-height: 1.55;
}

// ── Overlay (loading / error) ───────────────────────────────────────────────
.story-panel__overlay {
  position: absolute;
  inset: 0;
  z-index: 2;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  font-size: 13px;
  pointer-events: none;
  backdrop-filter: var(--imago-blur-light);
  -webkit-backdrop-filter: var(--imago-blur-light);
}

.story-panel__overlay--loading {
  background: rgba(8, 8, 15, 0.55);
  color: var(--imago-text-secondary);
}

.story-panel__overlay--error {
  flex-direction: column;
  text-align: center;
  background: rgba(8, 8, 15, 0.72);
  color: var(--imago-text-secondary);
  padding: 24px;
}

// ── Utility text clamps (match ProjectWorkspaceGrid's convention) ───────────
.ellipsis {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.ellipsis-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.ellipsis-3 {
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>
