// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change component structure or accessibility attributes
//
// SessionWorkspaceSidebar
// ────────────────────────
// Left drawer content for the redesigned session workspace. Hosts the
// "新建会话" button + "会话流" collapsible list. Renders into a
// UILayoutDrawer side="left" slot on SessionWorkspacePage. The component is
// purely presentational — all state lives on the page (useAgentSession).
//
// Visual language matches the approved mockup (docs/images/session_worksapce.png):
//   • Top: pill "新建会话" button with the "+" icon
//   • Header row: "会话流" label + collapse caret
//   • Body: a vertical list of session cards, each with title + time + (optional)
//     preview
//   • Empty state: a "暂无会话" message

<template>
  <div class="session-sidebar" :aria-label="'会话列表'">
    <!-- ── New session button ────────────────────────────────────── -->
    <div class="session-sidebar__head">
      <button
        type="button"
        class="session-sidebar__new"
        :disabled="creating"
        :aria-label="'新建会话'"
        @click="emit('create')"
      >
        <span class="session-sidebar__new-icon" aria-hidden="true">
          <OiIcon name="plus" :size="14"></OiIcon>
        </span>
        <span class="session-sidebar__new-label">
          {{ creating ? '创建中…' : '新建会话' }}
        </span>
      </button>
    </div>

    <!-- ── Session stream ────────────────────────────────────────── -->
    <section class="session-sidebar__section" aria-label="会话流">
      <button
        type="button"
        class="session-sidebar__group-toggle"
        :aria-expanded="expanded"
        :aria-label="expanded ? '收起会话流' : '展开会话流'"
        @click="expanded = !expanded"
      >
        <span class="session-sidebar__group-title">会话流</span>
        <span class="session-sidebar__group-count">{{ sessions.length }}</span>
        <span :class="caretClass">
          <OiIcon name="chevron-down" :size="14"></OiIcon>
        </span>
      </button>

      <ol v-if="expanded && sessions.length > 0" class="session-sidebar__list">
        <li v-for="session in sessions" :key="session.id" class="session-sidebar__item">
          <span
            class="session-card"
            :class="{ 'session-card--active': session.active }"
            role="button"
            tabindex="0"
            :aria-pressed="session.active"
            :aria-label="`切换到会话 ${session.title}`"
            @click="emit('select', session.id)"
            @keydown.enter.prevent="emit('select', session.id)"
            @keydown.space.prevent="emit('select', session.id)"
          >
            <span class="session-card__body">
              <span class="session-card__row">
                <span class="session-card__title ellipsis">{{ session.title }}</span>
                <span class="session-card__time">{{ session.clockLabel }}</span>
              </span>
              <span v-if="session.preview" class="session-card__preview ellipsis-2">
                {{ session.preview }}
              </span>
            </span>
            <span
              role="button"
              tabindex="0"
              class="session-card__delete"
              :aria-label="`删除会话 ${session.title}`"
              @click.stop="emit('delete', session.id)"
              @keydown.enter.stop.prevent="emit('delete', session.id)"
              @keydown.space.stop.prevent="emit('delete', session.id)"
            >
              <q-icon name="close" size="14px"></q-icon>
            </span>
          </span>
        </li>
      </ol>

      <div v-else-if="expanded" class="session-sidebar__empty">
        <q-icon name="forum" size="16px" color="grey-7"></q-icon>
        <span>暂无会话，点击上方按钮创建</span>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import OiIcon from 'src/components/ui/OiIcon.vue'

// ── Public shape ────────────────────────────────────────────────────────────

export interface SidebarSessionItem {
  id: string
  title: string
  preview: string
  timeLabel: string
  clockLabel: string
  meta: string
  active: boolean
}

// ── Props / emits ───────────────────────────────────────────────────────────

withDefaults(defineProps<{
  sessions: SidebarSessionItem[]
  collapsed?: boolean
  creating?: boolean
}>(), {
  collapsed: false,
  creating: false,
})

const emit = defineEmits<{
  (e: 'create'): void
  (e: 'select', id: string): void
  (e: 'delete', id: string): void
  (e: 'toggleCollapse'): void
}>()

// Local expanded state — independent of the `collapsed` prop so the sidebar
// can manage its own accordion state.
const expanded = ref(true)

const caretClass = computed(() => expanded.value
  ? 'session-sidebar__group-caret session-sidebar__group-caret-open'
  : 'session-sidebar__group-caret')
</script>

<style lang="scss" scoped>
.session-sidebar {
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
  min-height: 0;
  background: linear-gradient(180deg, var(--imago-bg-deep), var(--imago-bg-void) 30%);
}

// ── New session button ─────────────────────────────────────────────────────

.session-sidebar__head {
  padding: 18px 16px 14px;
  flex-shrink: 0;
}

.session-sidebar__new {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  width: 100%;
  height: 38px;
  padding: 0 14px;
  border: 1px solid var(--imago-border-cyan);
  border-radius: var(--imago-radius-pill);
  background: var(--imago-cyan-08);
  color: var(--imago-neon-cyan);
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  transition: color 120ms ease, background 120ms ease, border-color 120ms ease, box-shadow 120ms ease;
}

.session-sidebar__new:hover {
  color: var(--imago-text-primary);
  background: var(--imago-cyan-06);
  border-color: var(--imago-border-cyan-active);
  box-shadow: 0 0 18px rgba(0, 240, 255, 0.12);
}

.session-sidebar__new:disabled {
  opacity: 0.55;
  cursor: not-allowed;
}

.session-sidebar__new-icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
}

.session-sidebar__new-label {
  letter-spacing: 0.01em;
}

// ── Section / group toggle ─────────────────────────────────────────────────

.session-sidebar__section {
  flex: 1 1 auto;
  min-height: 0;
  display: flex;
  flex-direction: column;
  padding: 0 16px 16px;
}

.session-sidebar__group-toggle {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 4px 10px;
  border: 0;
  background: transparent;
  cursor: pointer;
  text-align: left;
  color: var(--imago-text-secondary);
  font-size: 12px;
  font-weight: 600;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  width: 100%;
  border-bottom: 1px solid var(--imago-border-light);
}

.session-sidebar__group-title {
  flex: 1 1 auto;
}

.session-sidebar__group-count {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 20px;
  height: 18px;
  padding: 0 6px;
  border-radius: 9px;
  background: var(--imago-bg-raised);
  color: var(--imago-text-muted);
  font-size: 10.5px;
  font-weight: 600;
  letter-spacing: 0.04em;
}

.session-sidebar__group-caret {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  color: var(--imago-text-muted);
  transition: transform 140ms ease;
  transform: rotate(-90deg);
}

.session-sidebar__group-caret-open {
  transform: rotate(0deg);
}

// ── List ───────────────────────────────────────────────────────────────────

.session-sidebar__list {
  list-style: none;
  margin: 12px 0 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 6px;
  overflow-y: auto;
  flex: 1 1 auto;
  min-height: 0;
}

.session-sidebar__empty {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 14px 12px;
  margin-top: 12px;
  border: 1px dashed var(--imago-border-soft);
  border-radius: var(--imago-radius-md);
  color: var(--imago-text-faint);
  font-size: 12px;
}

.session-card {
  position: relative;
  display: flex;
  align-items: stretch;
  gap: 4px;
  width: 100%;
  padding: 10px 10px 10px 12px;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-surface);
  color: var(--imago-text-primary);
  text-align: left;
  cursor: pointer;
  transition: border-color 120ms ease, background 120ms ease, box-shadow 120ms ease;
}

.session-card:hover {
  border-color: var(--imago-border-cyan);
  background: var(--imago-cyan-04);
}

.session-card--active {
  border-color: var(--imago-border-cyan-active);
  background: var(--imago-cyan-08);
  box-shadow: inset 0 0 0 1px var(--imago-border-cyan-active);
}

.session-card__body {
  flex: 1 1 auto;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.session-card__row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  min-width: 0;
}

.session-card__title {
  font-size: 12.5px;
  font-weight: 600;
  color: var(--imago-text-primary);
  min-width: 0;
  flex: 1 1 auto;
}

.session-card__time {
  flex-shrink: 0;
  font-size: 10.5px;
  color: var(--imago-text-faint);
  font-variant-numeric: tabular-nums;
}

.session-card__preview {
  margin: 0;
  font-size: 11.5px;
  line-height: 1.45;
  color: var(--imago-text-muted);
}

.session-card__delete {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 22px;
  height: 22px;
  padding: 0;
  border: 0;
  background: transparent;
  color: var(--imago-text-faint);
  border-radius: 4px;
  cursor: pointer;
  opacity: 0;
  transition: color 120ms ease, background 120ms ease, opacity 120ms ease;
  align-self: center;
  flex-shrink: 0;
}

.session-card:hover .session-card__delete,
.session-card:focus-within .session-card__delete {
  opacity: 1;
}

.session-card__delete:hover {
  color: var(--imago-neon-pink, #ff2d95);
  background: rgba(255, 45, 149, 0.08);
}

.session-card__delete:focus-visible {
  outline: none;
  opacity: 1;
  box-shadow: 0 0 0 2px var(--imago-cyan-08);
}

// ── Utility ─────────────────────────────────────────────────────────────────

.ellipsis {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.ellipsis-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>
