<!--
  DESIGN SPEC — generated by Designer agent
  Coder: implement TODO items, do not change component structure or accessibility attributes

  Visual direction: APPROVED minimal CapCut/剪映 editor (docs/images/cut_panel.png).
  Flat pure-black canvas, generous negative space, NO glow / NO heavy gradients /
  NO thick neon borders. The cyan accent appears ONLY on the active play affordance
  and the selected clip (the latter lives in omniclip's shadow DOM, tuned via the
  --omni-* variables on .story-cut__editor + IMAGO_TO_OMNI_THEME). Everything Vue
  owns here — empty, orphan, transitions, BGM, loading/error — is redesigned to
  read as quiet chrome around the floating preview + filmstrip the editor renders.

  NOTE TO CODER: script setup logic, props, emits, the omniclip mount/hydrate flow,
  and defineExpose are unchanged from the prior revision and must stay so. Only the
  template structure and <style scoped> were reshaped for the new look.
  ──────────────────────────────────────────────────────────────────────────────

  StoryCutPanel — the 时间线 tab's NLE Cut editor (ADR 0006/0007, openimago-4eiw).
  Replaces the old workflow-DAG StoryTimelinePanel.

  Mounts the vendored omniclip fork's <construct-editor>, hydrates it from the
  episode's cut.json (canonical, ownership model A), and persists edits through
  the cut write endpoints with the cut's own optimistic-concurrency clock.

  BROWSER NOTE: the omniclip editor needs WebCodecs + SharedArrayBuffer +
  IndexedDB and is loaded via a runtime dynamic import of the vendored fork
  (excluded from repo typecheck). The data orchestration (hydrate mapping,
  media resolution, edit dispatch + 409 retry) lives in tested src/utils/cut
  modules. See src/vendor/omniclip-fork/LOCAL_VALIDATION.md for the manual
  browser checks.
-->
<template>
  <section class="story-cut" aria-label="时间线粗剪">
    <!-- ── Empty state: episode has no Cut yet → offer to assemble ── -->
    <div v-if="isEmptyCut" class="story-cut__empty">
      <div class="story-cut__empty-frame" aria-hidden="true">
        <OiIcon name="canvas" :size="24" />
      </div>
      <p class="story-cut__empty-title">尚未生成粗剪</p>
      <p class="story-cut__empty-hint">
        从本集已完成的镜头自动拼接一个粗剪，然后在时间线上修剪、排序与转场。
      </p>
      <button
        type="button"
        class="story-cut__assemble"
        :disabled="assembling"
        @click="onAssemble"
      >
        <OiIcon name="enhance-wave" :size="15" />
        {{ assembling ? '正在拼接…' : '自动拼接粗剪' }}
      </button>
    </div>

    <!-- ── Cut editor ── -->
    <template v-else>
      <div v-if="orphanCount > 0" class="story-cut__orphan-banner" role="status">
        <OiIcon name="layers" :size="13" />
        {{ orphanCount }} 个片段的源镜头已不存在，已标记为缺失（灰色虚线）。
      </div>

      <!-- omniclip's editor custom element (registered by the fork on load). -->
      <div ref="editorHost" class="story-cut__editor" data-testid="cut-editor-host">
        <!-- While hydrating, HIDE the real editor entirely (visibility:hidden — stays
             mounted so media isn't re-imported, but nothing paints) so its empty-timeline
             shell (gutter waveform icons, white playhead) can't bleed through above the
             skeleton overlay (openimago-l9qs). visibility inherits through the shadow
             boundary, so the whole editor goes invisible. Revealed when hydration ends. -->
        <construct-editor
          v-if="editorReady"
          class="story-cut__construct"
          :class="{ 'story-cut__construct--hidden': hydrating }"
        />
        <p v-if="!editorReady" class="story-cut__loading">
          {{ editorError ? editorError : '正在加载剪辑器…' }}
        </p>
        <!-- Editor mounted but hydration in flight (~7s import/place window): cover the
             not-yet-placed timeline with a skeleton shaped like the real editor —
             9:16 player, transport bar, 3 timeline tracks — so the wait feels
             intentional (the native "Your timeline is empty" placeholder is suppressed
             in the vendored view; openimago-l9qs). -->
        <div
          v-else-if="hydrating"
          class="story-cut__hydrating"
          role="status"
          aria-live="polite"
          aria-label="正在加载粗剪"
        >
          <!-- Top: player region (= editor height − 300px, flex:1). Centered 9:16 block
               sized to the region height, matching the real media-player preview. -->
          <div class="story-cut__hydrating-player">
            <q-skeleton animation="wave" class="story-cut__sk-player" />
          </div>

          <!-- Bottom: the FIXED 300px timeline pane (TIMELINE_PANE_PX). Internals match
               the real omni-timeline: transport bar (46px) · ruler (20px) · 3 lanes
               (50/25/25px, 8px gaps) with a 60px gutter icon per lane. -->
          <div class="story-cut__hydrating-timeline" :style="{ height: `${TIMELINE_PANE_PX}px` }">
            <!-- Transport bar (46px): control clusters + play + timecode. -->
            <div class="story-cut__hydrating-transport" aria-hidden="true">
              <div class="story-cut__hydrating-group">
                <q-skeleton animation="wave" class="story-cut__sk-ctl" />
                <q-skeleton animation="wave" class="story-cut__sk-ctl" />
                <q-skeleton animation="wave" class="story-cut__sk-ctl" />
              </div>
              <div class="story-cut__hydrating-group">
                <q-skeleton animation="wave" type="circle" class="story-cut__sk-play" />
                <q-skeleton animation="wave" class="story-cut__sk-timecode" />
              </div>
              <div class="story-cut__hydrating-group">
                <q-skeleton animation="wave" class="story-cut__sk-ctl" />
                <q-skeleton animation="wave" class="story-cut__sk-ctl" />
                <q-skeleton animation="wave" class="story-cut__sk-ctl" />
              </div>
            </div>

            <!-- Ruler (20px), offset past the 60px gutter like the real time-ruler. -->
            <div class="story-cut__hydrating-ruler" aria-hidden="true">
              <q-skeleton animation="wave" class="story-cut__sk-ruler" />
            </div>

            <!-- 3 lanes: gutter icon (60px) + lane bar; heights 50 / 25 / 25, 8px gaps. -->
            <div class="story-cut__hydrating-tracks" aria-hidden="true">
              <div class="story-cut__hydrating-row story-cut__hydrating-row--video">
                <div class="story-cut__hydrating-gutter">
                  <q-skeleton animation="wave" class="story-cut__sk-icon" />
                </div>
                <q-skeleton animation="wave" class="story-cut__sk-lane story-cut__sk-lane--video" />
              </div>
              <div class="story-cut__hydrating-row story-cut__hydrating-row--audio">
                <div class="story-cut__hydrating-gutter">
                  <q-skeleton animation="wave" class="story-cut__sk-icon" />
                </div>
                <q-skeleton animation="wave" class="story-cut__sk-lane story-cut__sk-lane--audio" />
              </div>
              <div class="story-cut__hydrating-row story-cut__hydrating-row--audio">
                <div class="story-cut__hydrating-gutter">
                  <q-skeleton animation="wave" class="story-cut__sk-icon" />
                </div>
                <q-skeleton animation="wave" class="story-cut__sk-lane story-cut__sk-lane--audio" />
              </div>
            </div>
          </div>

          <!-- Subtle label with a shimmer spinner. -->
          <div class="story-cut__hydrating-label">
            <q-spinner-dots size="16px" color="grey-6" />
            <span>正在加载粗剪…</span>
          </div>
        </div>

        <!-- 手动编辑 composer — a q-menu anchored to this editor element, sized to the
             player-preview region so it docks from the top down to the transport/
             timeline (openimago-7k46). The omniclip editor stays mounted underneath;
             closing returns the preview. -->
        <ClipGenerateDialog
          v-if="regenComposer"
          :open="true"
          :shot="regenComposer.shot"
          :latest-run="regenComposer.latestRun"
          :elements="regenElements ?? []"
          :generating="regenGenerating ?? false"
          :target="editorHost"
          :panel-height="playerRegionHeight"
          @update:open="(v) => { if (!v) emit('clip-generate-close') }"
          @generate="(p) => emit('clip-generate', p)"
        />
      </div>

      <!-- ── Selection-driven contextual control bar (openimago-e6k1) ──
           ONE slim row, CapCut-style: contextual transition controls on the LEFT
           (only when a clip with a following clip is selected), the global BGM
           chip on the RIGHT (always shown — BGM is a property of the whole cut).
           Replaces the old always-on all-boundaries dock. -->
      <div class="story-cut__bar" data-testid="cut-controls">
        <!-- While hydrating, skeletonize the footer too (openimago-l9qs) so the whole
             panel top-to-bottom is one cohesive skeleton — no real BGM control pokes through. -->
        <template v-if="hydrating">
          <div class="story-cut__bgm-chip story-cut__bgm-chip--sk" aria-hidden="true">
            <q-skeleton animation="wave" type="circle" class="story-cut__sk-bgm-icon" />
            <q-skeleton animation="wave" class="story-cut__sk-bgm-label" />
            <q-skeleton animation="wave" class="story-cut__sk-bgm-btn" />
          </div>
        </template>

        <template v-else>
        <!-- RIGHT: global BGM chip (always shown). -->
        <div class="story-cut__bgm-chip">
          <OiIcon name="enhance-wave" :size="13" class="story-cut__bgm-icon" />
          <span class="story-cut__bgm-current">
            {{ bgmLabel ?? '未设置背景音乐' }}
          </span>
          <button
            type="button"
            class="story-cut__bgm-pick"
            @click="toggleBgmPicker"
          >
            {{ bgmLabel ? '更换' : '选择' }}
          </button>
          <button
            v-if="bgmLabel"
            type="button"
            class="story-cut__clear"
            aria-label="清除背景音乐"
            @click="clearBgm"
          >
            <OiIcon name="canvas" :size="13" />
          </button>

          <!-- Picker popover — opens above the chip. -->
          <div v-if="bgmPickerOpen" class="story-cut__bgm-picker" data-testid="bgm-picker">
            <p v-if="loadingAssets" class="story-cut__control-empty">正在加载音频…</p>
            <p v-else-if="audioAssets.length === 0" class="story-cut__control-empty">
              没有可用的音频素材。
            </p>
            <ul v-else class="story-cut__bgm-list">
              <li v-for="asset in audioAssets" :key="asset.id">
                <button
                  type="button"
                  class="story-cut__bgm-option"
                  :class="{ 'story-cut__bgm-option--active': props.cut?.bgm?.artifactId === asset.id }"
                  @click="selectBgm(asset.id)"
                >
                  {{ asset.name || asset.filename || asset.id }}
                </button>
              </li>
            </ul>
          </div>
        </div>
        </template>
      </div>
    </template>
  </section>
</template>

<script setup lang="ts">
import { computed, ref, watch, onMounted, onBeforeUnmount, nextTick } from 'vue'
import OiIcon from 'src/components/ui/OiIcon.vue'
import type { StoryRunSummary, StoryShotSummary } from 'src/components/session-workspace/types'
import { type EpisodeCut } from 'src/utils/cut/cut-types'
import { makeShotMediaResolver } from 'src/utils/cut/shot-media-resolver'
import { buildHydrationPayload, type BgmMediaSource } from 'src/utils/cut/cut-hydration'
import { dispatchCutEdit, type CutEdit } from 'src/utils/cut/cut-edit-dispatcher'
import { buildClipMenuItems } from 'src/utils/cut/clip-menu-items'
import { resolveBgmLabel } from 'src/utils/cut/cut-controls'
import { bgmAuthHeaders } from 'src/utils/cut/bgm-auth'
import type { LoadOmniclipFork, OmniclipForkApi } from 'src/utils/cut/fork-contract'
import { api, ApiError, type OpenimagoAsset } from 'src/api/client'
import { useAuthStore } from 'src/stores/auth'
import ClipGenerateDialog from 'src/components/session-workspace/ClipGenerateDialog.vue'
import type { ElementCardVM } from 'src/components/session-workspace/left-panel/types'
import type { ShotGenerationParams } from 'src/utils/cut/clip-generate-form'

const props = defineProps<{
  projectId: string
  episodeId: string
  /** canonical cut for the episode (empty clips => never cut). */
  cut: EpisodeCut | null
  shots: StoryShotSummary[]
  runs: StoryRunSummary[]
  /** Active 手动编辑 regen target (openimago-7k46). When set, the full-width composer
   *  docks over the player-preview region. null → the player preview shows. */
  regenComposer?: { shot: StoryShotSummary; latestRun: StoryRunSummary | null } | null
  /** Bible elements for the composer's @-mention picker. */
  regenElements?: ElementCardVM[]
  /** Whether a regen is in flight (disables the composer's controls). */
  regenGenerating?: boolean
}>()

const emit = defineEmits<{
  /** ask the page to (re)assemble + refetch the cut. */
  (e: 'request-assemble'): void
  /** a persisted edit changed the cut — page should refetch. */
  (e: 'cut-changed'): void
  /** surface a conflict that lost after one retry. */
  (e: 'cut-conflict'): void
  /** a write failed for a NON-conflict reason (e.g. 400 from a stale/phantom id,
   *  openimago-vx2t): the editor is now out of sync with the server, so the page
   *  must show a visible error AND force a re-hydrate back to the server's truth. */
  (e: 'cut-error'): void
  /** clip menu (openimago-e0n3): regenerate the source shot's media. */
  (e: 'clip-regenerate', sourceShotId: string): void
  /** clip menu: open the 手动编辑 composer for the source shot (openimago-7k46 docks
   *  it over the player region; the page owns the composer state). */
  (e: 'clip-manual-edit', sourceShotId: string): void
  /** clip menu: delete the CLIP (not the shot). */
  (e: 'clip-delete', clipId: string): void
  /** clip menu: attach the clip's media to the chat as a reference. */
  (e: 'clip-add-to-chat', sourceShotId: string): void
  /** composer 生成 — re-run generation for the regen target's shot (openimago-7k46). */
  (e: 'clip-generate', params: ShotGenerationParams): void
  /** composer closed without generating (openimago-7k46). */
  (e: 'clip-generate-close'): void
}>()

const editorHost = ref<HTMLElement | null>(null)
const editorReady = ref(false)

// 手动编辑 composer sizing (openimago-7k46). The editor is a vertical two-pane layout:
// a flexible player-preview pane on top and a FIXED-height timeline pane below (bound
// to TIMELINE_PANE_PX in the fork's construct-editor-styles.patch.ts — mirrored here,
// that patch is the source of truth, kept in sync manually to avoid statically
// importing the browser-only vendor into the app build). So the player region the
// composer must fill = editor height − the fixed timeline pane.
const TIMELINE_PANE_PX = 300
const editorHeight = ref(0)
let editorResizeObserver: ResizeObserver | null = null
const playerRegionHeight = computed(() => Math.max(0, editorHeight.value - TIMELINE_PANE_PX))
// True while fork.hydrateFromCut runs (the ~7s import/place window). The editor is
// mounted but clips aren't placed yet, so we cover it with a design-matching loading
// overlay instead of letting the (now-suppressed) native empty timeline flash through
// (openimago-l9qs).
const hydrating = ref(false)
const editorError = ref<string | null>(null)
const assembling = ref(false)

// Auth store for the BGM media fetch (openimago-tc8t): the BGM resolves to the
// authed /api/.../download, so resolveBgmSource threads Authorization: Bearer
// <token> down to the fork. Clip /mock previews stay unauthenticated.
const auth = useAuthStore()

// Local optimistic-concurrency clock for cut writes (ADR 0008 #3). Seeded from
// the canonical cut and advanced by each write's returned updatedAt, so the
// panel does NOT re-hydrate on every edit (which would re-import media). The
// rare cross-actor agent-assemble race is still caught by emit('cut-changed') →
// page refetch + runCutMutation's 409 retry.
const lastUpdatedAt = ref<string | undefined>(props.cut?.updatedAt)

let fork: OmniclipForkApi | null = null
let unregisterClipMenu: (() => void) | null = null
let unsubscribeEdits: (() => void) | null = null

const isEmptyCut = computed(() => !props.cut || props.cut.clips.length === 0)

// Resolve clip media (shot -> latest completed run preview) for hydration.
const mediaResolver = computed(() => makeShotMediaResolver(props.shots, props.runs))

// Orphans: clips whose source shot has no usable media (rendered greyed).
const orphanCount = computed(() => {
  if (!props.cut) return 0
  return props.cut.clips.filter((c) => mediaResolver.value(c.sourceShotId) === null).length
})

/** Assemble the first cut from the episode's shots, then refetch. */
async function onAssemble(): Promise<void> {
  if (assembling.value) return
  assembling.value = true
  try {
    await api.assembleEpisodeCut(props.projectId, props.episodeId, props.cut?.updatedAt)
    emit('request-assemble')
  } catch (err) {
    if (err instanceof ApiError && err.status === 409) {
      emit('cut-conflict')
    } else {
      editorError.value = '拼接失败'
    }
  } finally {
    assembling.value = false
  }
}

/** Persist one editor edit through the cut endpoints (tested dispatcher). */
async function persistEdit(edit: CutEdit): Promise<void> {
  let outcome
  try {
    outcome = await dispatchCutEdit(
      {
        api,
        projectId: props.projectId,
        episodeId: props.episodeId,
        // Read the LOCAL clock (decision 3): structural edits chain off each
        // other's returned updatedAt without a refetch between them.
        currentUpdatedAt: () => lastUpdatedAt.value,
        refetch: async () => {
          const fresh = await api.projectStoryCut(props.projectId, props.episodeId)
          lastUpdatedAt.value = fresh?.updatedAt
          return fresh?.updatedAt
        },
        // Advance the local clock from each write so the next edit's expected
        // updatedAt is current — no re-hydration, no per-edit refetch.
        onWritten: (updatedAt) => {
          lastUpdatedAt.value = updatedAt
        },
      },
      edit,
    )
  } catch (err) {
    // A NON-conflict write failure (e.g. 400 from a stale/phantom clip id, or a
    // network error) means the editor's omniclip state has diverged from the
    // server. runCutMutation only retries 409s; everything else used to reject
    // here and be SILENTLY swallowed by the fire-and-forget onEdit caller
    // (openimago-vx2t). Surface it to the page, which shows a visible error AND
    // refetches+rehydrates the editor back to the server's truth (via the exposed
    // `rehydrate`) so the user never keeps editing against a phantom timeline.
    console.error('StoryCutPanel: cut write failed (non-conflict)', err)
    emit('cut-error')
    return
  }
  if (outcome === 'conflict') emit('cut-conflict')
  else emit('cut-changed')
}

/**
 * Rebuild the editor from the CURRENT props.cut (openimago-vx2t reconcile). The
 * page calls this AFTER it has refetched the canonical cut on a `cut-error`, so
 * props.cut already holds the server truth; remounting drops any phantom/un-saved
 * omniclip effect. Re-seeds the local concurrency clock from the fresh cut.
 */
function rehydrate(): void {
  lastUpdatedAt.value = props.cut?.updatedAt
  remountEditor()
}

// ── HOST-DRIVEN transition + BGM controls (ADR 0008 #1b, openimago-ofdw) ──
//
// BGM is NOT captured from omniclip's gesture diff. This host control originates
// the edits: calls the fork setter for live editor preview + persistEdit.

// Audio assets for the BGM picker (api.listAssets type-filtered to audio).
const audioAssets = ref<OpenimagoAsset[]>([])
const bgmPickerOpen = ref(false)
const loadingAssets = ref(false)

const bgmLabel = computed(() => resolveBgmLabel(props.cut?.bgm, audioAssets.value))

/** Lazily load audio assets the first time the BGM picker is opened. */
async function loadAudioAssets(): Promise<void> {
  if (loadingAssets.value) return
  loadingAssets.value = true
  try {
    audioAssets.value = await api.listAssets({ type: 'audio' })
  } catch (err) {
    console.error('StoryCutPanel: failed to load audio assets', err)
  } finally {
    loadingAssets.value = false
  }
}

async function toggleBgmPicker(): Promise<void> {
  bgmPickerOpen.value = !bgmPickerOpen.value
  if (bgmPickerOpen.value && audioAssets.value.length === 0) {
    await loadAudioAssets()
  }
}

/** Choose the Cut's single BGM bed. */
async function selectBgm(artifactId: string): Promise<void> {
  bgmPickerOpen.value = false
  await persistEdit({ kind: 'set-bgm', artifactId })
  // Live-update the fork's BGM track so the green waveform lane appears immediately
  // without a full re-hydration (openimago-tc8t). resolveBgmSource fetches the
  // asset URL; the fork's updateBgmTrack swaps the audio effect on track 2.
  // Fire-and-forget: the import is slow; errors are non-fatal (warn + empty lane).
  const bgmResolved = await resolveBgmSource(artifactId)
  void fork?.updateBgmTrack(
    bgmResolved
      ? {
          id: bgmResolved.id,
          url: bgmResolved.source.url,
          name: bgmResolved.source.name,
          ...(bgmResolved.source.headers ? { headers: bgmResolved.source.headers } : {}),
        }
      : null,
  )
}

/** Remove the Cut's BGM bed. */
async function clearBgm(): Promise<void> {
  await persistEdit({ kind: 'clear-bgm' })
  // Remove the BGM audio effect from the fork's track 2 immediately.
  void fork?.updateBgmTrack(null)
}

/**
 * Resolve a BGM artifactId → its servable media (url + display name) for
 * hydration (openimago-w5bu). Prefers the already-loaded audioAssets, falling
 * back to a single getAsset fetch when the picker hasn't loaded yet (the common
 * case on a fresh mount). Returns null on any failure so the lane is just
 * skipped rather than blocking the editor.
 */
async function resolveBgmSource(
  artifactId: string | undefined,
): Promise<{ id: string; source: BgmMediaSource } | null> {
  if (!artifactId) return null
  // The BGM url is the authed /api/.../download, so carry Bearer auth on the
  // fork's fetch (openimago-tc8t). Built from the auth store here in the host;
  // the fork never reaches into it.
  const headers = bgmAuthHeaders(auth.token)
  const cached = audioAssets.value.find((a) => a.id === artifactId)
  if (cached?.url) {
    return {
      id: artifactId,
      source: { url: cached.url, name: cached.name || cached.filename || artifactId, headers },
    }
  }
  try {
    const asset = await api.getAsset(artifactId)
    if (!asset?.url) return null
    return {
      id: artifactId,
      source: { url: asset.url, name: asset.name || asset.filename || artifactId, headers },
    }
  } catch (err) {
    console.error('StoryCutPanel: failed to resolve BGM asset for hydration', err)
    return null
  }
}

// ── BROWSER-ONLY: load the fork, mount the editor, hydrate from cut.json ──
//
// Guarded behind the runtime loader so the repo typecheck never reaches the
// vendored omniclip code. Hydration imports each clip's media via the fork and
// builds omniclip state from the canonical cut.

async function mountAndHydrate(): Promise<void> {
  if (isEmptyCut.value || !editorHost.value || editorReady.value) return

  // Phase 1 — load the fork module. A failure here is a bundling / module-load
  // problem (e.g. Vite dep-optimizer timeout), NOT a browser-capability issue.
  let loaded: OmniclipForkApi
  let applyImagoTheme: (wrapper: HTMLElement) => HTMLElement
  try {
    // Dynamic import via a runtime-computed path so the repo typecheck never
    // follows into the browser-only vendored fork (excluded from tsconfig).
    // Must be an ABSOLUTE app path (leading slash + extension): with
    // `@vite-ignore` the specifier reaches the browser verbatim, and a bare
    // 'src/vendor/...' would fail as a bare module specifier. (openimago-y90v)
    const forkModulePath = ['', 'src', 'vendor', 'omniclip-fork', 'load.ts'].join('/')
    const mod = (await import(/* @vite-ignore */ forkModulePath)) as unknown as {
      loadOmniclipFork: LoadOmniclipFork
    }
    ;({ fork: loaded, applyImagoTheme } = await mod.loadOmniclipFork())
  } catch (err) {
    editorError.value = '剪辑器模块加载失败（请检查 omniclip 依赖与构建配置）'
    console.error('StoryCutPanel: failed to load omniclip fork module', err)
    return
  }

  // Phase 2 — mount + wire. A failure here is a runtime / browser-API issue
  // (WebCodecs / SharedArrayBuffer / IndexedDB unavailable, or not isolated).
  try {
    fork = loaded
    applyImagoTheme(editorHost.value)

    // Register the per-clip context menu (openimago-e0n3). The menu items +
    // orphan-gating are the unit-tested buildClipMenuItems; each item emits to
    // the page, which runs the real action. isEnabled hides shot-bound items on
    // orphan clips (sourceShotId gone) but keeps 删除.
    unregisterClipMenu = fork.registerClipMenuItems(
      buildClipMenuItems({
        onRegenerate: (sourceShotId) => emit('clip-regenerate', sourceShotId),
        onManualEdit: (sourceShotId) => emit('clip-manual-edit', sourceShotId),
        onDeleteClip: (clipId) => emit('clip-delete', clipId),
        onAddToChat: (sourceShotId) => emit('clip-add-to-chat', sourceShotId),
      }),
    )

    // Resolve a clicked effect id → its sourceShotId for the context menu's
    // orphan-gating (effect id === CutClip.id). (openimago-1mcb)
    fork.setClipContextResolver(
      (effectId) => props.cut?.clips.find((c) => c.id === effectId)?.sourceShotId,
    )

    // Render <construct-editor> now that the fork is loaded.
    editorReady.value = true

    // Hydrate from the canonical cut (openimago-addv). buildHydrationPayload is
    // pure + unit-tested: it maps cut.json clips (ordered) + the media resolver
    // → the fork's HydrateClip[] (url + trim) and the transitions in omniclip
    // ms, splitting out orphans (which surface via the data-no-file path). The
    // fork imports each clip's media (importFromUrl) and places it as a trimmed
    // effect, then applies transitions.
    if (props.cut) {
      // Resolve the Cut's BGM artifact → a fetchable url up front (the bgm
      // resolver is sync; the asset lookup is async), then build the payload.
      // The fork places it on its own audio track → the green waveform lane
      // (openimago-w5bu). An unresolvable bgm is simply omitted.
      const bgmSource = await resolveBgmSource(props.cut.bgm?.artifactId)
      const { clips, transitions, bgm } = buildHydrationPayload(
        props.cut,
        mediaResolver.value,
        (artifactId) => (bgmSource && bgmSource.id === artifactId ? bgmSource.source : null),
      )
      // Cover the editor with our loading overlay for the hydration window
      // (openimago-l9qs); finally so it clears on success OR if hydrate throws
      // (the throw still propagates to the outer catch which rolls editorReady back).
      hydrating.value = true
      try {
        await fork.hydrateFromCut(clips, transitions, bgm)
      } finally {
        hydrating.value = false
      }
    }

    // Subscribe to committed editor gestures ONLY AFTER hydration has fully
    // settled (openimago-3xbg). hydrateFromCut serially imports + places every
    // clip; each import is an async state mutation that on-edit's effects-diff
    // would otherwise observe with a still-incomplete baseline. If a user split
    // landed in the same debounce window as a late clip import, the diff saw the
    // late clip AND the split half as two unrelated additions against a stale
    // baseline → the split was dropped or (in adjacent timing) misread as a
    // trim/reorder, corrupting clip order + source ranges. Subscribing here means
    // the baseline is the COMPLETE hydrated timeline and no hydration import is
    // ever diffed as a user gesture. (ADR 0008 #1/#1a: the fork diffs its effects
    // snapshot per settled gesture and hands us ONE semantic CutEdit — reorder /
    // trim / split / delete; persistEdit routes it through the cut endpoints.
    // Transition/BGM are host-driven and do NOT arrive here. JS's single thread +
    // persistEdit's per-edit await serialise these user-paced gestures.)
    // Serialise fork edits so split always commits before the following reorder
    // fires. Without this, a split+reorder landing close together sends the
    // reorder before the split is committed on the server → the server rejects
    // the reorder with 400 (orderedClipIds includes the new split-half id that
    // doesn't exist yet) → cut-error + rehydration undoes the move
    // (openimago-r7to).
    let editQueue: Promise<void> = Promise.resolve()
    unsubscribeEdits = fork.onEdit((edit) => {
      editQueue = editQueue.then(() => persistEdit(edit))
    })
  } catch (err) {
    // Roll editorReady back so the error <p> shows instead of an empty
    // <construct-editor> (openimago-ystd). editorReady is flipped true BEFORE
    // hydrateFromCut so omniclip mounts; a hydration throw (e.g. importFromUrl
    // failing on an unreachable/undecodable clip) must surface its message, not a
    // silent empty timeline.
    editorReady.value = false
    editorError.value = '剪辑器初始化失败（需要支持 WebCodecs 的浏览器环境）'
    console.error('StoryCutPanel: failed to initialise omniclip editor', err)
  }
}

/** Reset editor state and (re)mount once the host div is in the DOM. */
function remountEditor(): void {
  editorReady.value = false
  hydrating.value = false
  editorError.value = null
  // Re-seed the local clock from the (possibly newly-loaded) cut before the
  // fresh editor starts emitting edits.
  lastUpdatedAt.value = props.cut?.updatedAt
  unsubscribeEdits?.()
  unsubscribeEdits = null
  unregisterClipMenu?.()
  unregisterClipMenu = null
  // nextTick so the editorHost div is bound before mountAndHydrate reads it.
  // (GAP 1, openimago-addv: an immediate watch ran during setup() before the
  // ref existed → early return → the editor never mounted.)
  void nextTick(() => mountAndHydrate())
}

// First mount: the host div exists by onMounted, so this never early-returns.
// Also observe the editor host's height so the docked composer can size to the
// player-preview region (openimago-7k46).
onMounted(() => {
  remountEditor()
  if (editorHost.value) {
    editorHeight.value = editorHost.value.clientHeight
    editorResizeObserver = new ResizeObserver((entries) => {
      const rect = entries[0]?.contentRect
      if (rect) editorHeight.value = rect.height
    })
    editorResizeObserver.observe(editorHost.value)
  }
})

// Re-mount when the episode changes or the cut transitions empty↔non-empty.
watch(() => [props.episodeId, isEmptyCut.value] as const, remountEditor)

onBeforeUnmount(() => {
  editorResizeObserver?.disconnect()
  editorResizeObserver = null
  unsubscribeEdits?.()
  unsubscribeEdits = null
  unregisterClipMenu?.()
  unregisterClipMenu = null
  fork = null
})

// Expose persistEdit for the editor event bridge (wired during local validation).
defineExpose({ persistEdit, rehydrate })
</script>

<style lang="scss" scoped>
// ── Editor host ────────────────────────────────────────────────────────────────
//
// Flat pure-black canvas (no gradient — the approved image is a single deep black
// field so the floating 9:16 preview reads against pure negative space).
.story-cut {
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
  min-height: 0;
  background: var(--imago-bg-void);
}

.story-cut__editor {
  flex: 1 1 auto;
  min-height: 0;
  position: relative;
  // Map the imago tokens into omniclip's shadow DOM (applyImagoTheme also sets
  // these at runtime; declared here so an un-themed mount still reads them).
  // Tuned for the approved flat look: a WHITE 1px playhead, and a thin SOLID cyan
  // selected-clip accent with NO halo. Clip fill/border stay muted so unselected
  // frames recede; orphans quiet pink. (The green audio waveform is rendered by
  // omniclip itself and is not host-controllable, so no --omni-audio override.)
  //
  // AMBIENT GLOW (UPDATED reference docs/images/cut_panel.png): MUCH subtler and
  // cooler than the earlier cut_panel_v2 pass. Pixel-sampled from the canonical
  // image the wash is only ~2-6 RGB points above #08080f: a faint, near-uniform
  // COOL lift across the top (corners read ~(10,10,15) — blue +5, no cyan), plus
  // a barely-there WARM tint on the MID-LEFT only (~(14,11,12) — red +2). There
  // is NO strong cyan top-right and NO magenta top-left. Painted on the editor
  // HOST background so it shows in the dark margins around omniclip's 9:16
  // media-player pane. --omni-bg is transparent so the embedded panes do NOT
  // repaint solid void over this glow; the void base lives on the host instead.
  // Keep it dark and tasteful — barely perceptible, never a "glow".
  background:
    // faint cool lift across the whole top (neutral blue, very low alpha)
    radial-gradient(
      90% 55% at 50% 0%,
      color-mix(in srgb, var(--imago-neon-cyan) 3%, transparent),
      transparent 70%
    ),
    // barely-there warm tint on the mid-left only
    radial-gradient(
      45% 45% at 8% 42%,
      color-mix(in srgb, var(--imago-neon-pink) 3%, transparent),
      transparent 62%
    ),
    var(--imago-bg-void);
  --omni-bg: transparent;
  --omni-clip-fill: var(--imago-bg-surface);
  --omni-clip-border: var(--imago-border-soft);
  --omni-accent: var(--imago-neon-cyan);
  --omni-playhead: var(--imago-text-primary);
  --omni-text: var(--imago-text-primary);
  --omni-orphan: var(--imago-neon-pink);
}

// The editor now hosts a vertical two-pane layout (preview player above,
// timeline below — openimago-h8v6), so the <construct-editor> custom element
// must FILL the editor host for the panes to split its height. A custom element
// defaults to display:inline, so its :host{height:100%} would not take effect
// without an explicit block + full height here.
.story-cut__construct {
  display: block;
  width: 100%;
  height: 100%;
  min-height: 0;
  // The <construct-editor> element paints an opaque grey (~#111) by default,
  // which would cover the editor host's ambient glow. Make it transparent so the
  // warm/cool wash on .story-cut__editor shows through the panes' dark margins
  // (the timeline/player panes themselves are transparent via --omni-bg).
  background: transparent;
}

// While hydrating, hide the real editor entirely so its empty-timeline shell can't
// bleed through above the skeleton (openimago-l9qs). visibility (not display:none)
// keeps it laid out + mounted — no media re-import — and inherits through the shadow
// boundary, so all of omniclip's shadow content (gutter icons, playhead) goes invisible.
.story-cut__construct--hidden {
  visibility: hidden;
}

.story-cut__loading {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0;
  font-size: 12.5px;
  color: var(--imago-text-faint);
}

// ── Hydration SKELETON — pixel-coincident with the real editor (no jump on swap) ──
// Opaque void base covering the not-yet-hydrated editor. Layout mirrors the real
// metrics EXACTLY so the skeleton and the hydrated editor occupy the same boxes.
// Source of truth (mirrored — keep in sync):
//   • timeline pane   = TIMELINE_PANE_PX 300px  (construct-editor-styles.patch.ts)
//   • transport bar   = 46px               (toolbar-styles.ts .toolbar min-height)
//   • time ruler      = 20px               (time-ruler/styles.ts)
//   • gutter          = 60px               (timeline-gutter.ts GUTTER_PX)
//   • lanes           = 50 / 25 / 25 px    (timeline-lanes.ts VIDEO/AUDIO_LANE_PX)
//   • inter-lane gap  = 8px                (timeline-lanes.ts LANE_GAP_PX)
// No outer padding/gap → the player/timeline split is exact (player = height − 300).
.story-cut__hydrating {
  position: absolute;
  inset: 0;
  // Above the <construct-editor> sibling (which is also visibility:hidden while
  // hydrating) so the opaque cover wins regardless of the editor's internal stacking.
  z-index: 5;
  background: var(--imago-bg-void);
  display: flex;
  flex-direction: column;
}

// Skeletons: slightly lighter than the panel so they read on the dark bg, with a
// cooler wave sweep. --imago-* base; no hardcoded palette beyond low-alpha white.
.story-cut__hydrating :deep(.q-skeleton) {
  background: rgba(255, 255, 255, 0.05);
  border-radius: 6px;
}

.story-cut__hydrating :deep(.q-skeleton--anim-wave)::after {
  background: linear-gradient(
    90deg,
    transparent,
    color-mix(in srgb, var(--imago-neon-cyan) 8%, rgba(255, 255, 255, 0.08)),
    transparent
  );
}

// Top — player region = editor height − 300 (flex:1 above the fixed 300px pane).
.story-cut__hydrating-player {
  flex: 1 1 auto;
  min-height: 0;
  display: flex;
  align-items: center;
  justify-content: center;
}

// Centered 9:16 preview sized to the region HEIGHT (width = height × 9/16).
.story-cut__hydrating .story-cut__sk-player {
  height: 100%;
  aspect-ratio: 9 / 16;
  border-radius: 8px;
}

// Bottom — the FIXED 300px timeline pane (height bound to TIMELINE_PANE_PX inline).
.story-cut__hydrating-timeline {
  flex: 0 0 auto;
  display: flex;
  flex-direction: column;
  min-height: 0;
}

// Transport bar — real .toolbar min-height 46px.
.story-cut__hydrating-transport {
  flex: 0 0 46px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 0 12px;
}

.story-cut__hydrating-group {
  display: flex;
  align-items: center;
  gap: 8px;
}

.story-cut__hydrating .story-cut__sk-ctl {
  width: 20px;
  height: 20px;
}

.story-cut__hydrating .story-cut__sk-play {
  width: 34px;
  height: 34px;
}

.story-cut__hydrating .story-cut__sk-timecode {
  width: 92px;
  height: 12px;
  border-radius: 4px;
}

// Time ruler — real height 20px, content offset past the 60px gutter.
.story-cut__hydrating-ruler {
  flex: 0 0 20px;
  display: flex;
  align-items: center;
  padding-left: 60px;
}

.story-cut__hydrating .story-cut__sk-ruler {
  flex: 1 1 auto;
  height: 4px;
  border-radius: 2px;
}

// Lanes — each row = 60px gutter icon + lane bar; 50 / 25 / 25 px with 8px gaps.
.story-cut__hydrating-tracks {
  flex: 1 1 auto;
  min-height: 0;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.story-cut__hydrating-row {
  display: flex;
  align-items: stretch;
  gap: 0;
}

.story-cut__hydrating-row--video { height: 50px; }
.story-cut__hydrating-row--audio { height: 25px; }

// Gutter — real GUTTER_PX 60px column, icon centered per lane.
.story-cut__hydrating-gutter {
  flex: 0 0 60px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.story-cut__hydrating .story-cut__sk-icon {
  width: 24px;
  height: 24px;
}

.story-cut__hydrating-row--audio .story-cut__sk-icon {
  width: 18px;
  height: 18px;
}

.story-cut__hydrating .story-cut__sk-lane {
  flex: 1 1 auto;
  height: 100%;
  border-radius: 4px;
}

// Subtle centered label with a shimmer spinner, pinned near the top.
.story-cut__hydrating-label {
  position: absolute;
  top: 14px;
  left: 50%;
  transform: translateX(-50%);
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12.5px;
  color: var(--imago-text-faint);
}

// ── Footer (operations bar) skeleton — same dark wave treatment as the editor ──
// So the whole panel is one cohesive skeleton during hydration (no real transition
// hint / BGM control poking through). These skeletons live in .story-cut__bar, not
// .story-cut__hydrating, so they need the base color rule applied here too.
.story-cut__bar :deep(.q-skeleton) {
  background: rgba(255, 255, 255, 0.05);
  border-radius: 6px;
}

.story-cut__bar :deep(.q-skeleton--anim-wave)::after {
  background: linear-gradient(
    90deg,
    transparent,
    color-mix(in srgb, var(--imago-neon-cyan) 8%, rgba(255, 255, 255, 0.08)),
    transparent
  );
}

.story-cut__bar .story-cut__sk-hint {
  width: 168px;
  height: 12px;
  border-radius: 4px;
}

.story-cut__bgm-chip--sk {
  display: flex;
  align-items: center;
  gap: 8px;
}

.story-cut__bar .story-cut__sk-bgm-icon {
  width: 16px;
  height: 16px;
}

.story-cut__bar .story-cut__sk-bgm-label {
  width: 104px;
  height: 12px;
  border-radius: 4px;
}

.story-cut__bar .story-cut__sk-bgm-btn {
  width: 40px;
  height: 20px;
  border-radius: 6px;
}

// Quiet inline notice — NOT a loud alert. Muted pink derived from the token so no
// hex is hardcoded; a faint tint + hairline rule, sitting above the editor.
.story-cut__orphan-banner {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 7px 14px;
  font-size: 11.5px;
  color: color-mix(in srgb, var(--imago-neon-pink) 78%, var(--imago-text-muted));
  background: color-mix(in srgb, var(--imago-neon-pink) 6%, transparent);
  border-bottom: 1px solid color-mix(in srgb, var(--imago-neon-pink) 18%, transparent);
}

.story-cut__empty {
  flex: 1 1 auto;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 10px;
  padding: 40px 24px;
  text-align: center;
}

// 60px rounded frame, hairline border, subtle cyan glyph — NO glow (flat look).
.story-cut__empty-frame {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 60px;
  height: 60px;
  border-radius: var(--imago-radius-lg);
  background: var(--imago-cyan-04);
  border: 1px solid var(--imago-border-cyan);
  color: var(--imago-neon-cyan);
}

.story-cut__empty-title {
  margin: 0;
  font-size: 14px;
  font-weight: 600;
  color: var(--imago-text-primary);
}

.story-cut__empty-hint {
  margin: 0;
  max-width: 340px;
  font-size: 11.5px;
  line-height: 1.6;
  color: var(--imago-text-faint);
}

// Slim cyan pill CTA — flat fill, hairline cyan ring, no glow. Hover only deepens
// the fill. Visible keyboard focus via a thin cyan ring.
.story-cut__assemble {
  display: inline-flex;
  align-items: center;
  gap: 7px;
  margin-top: 6px;
  padding: 9px 18px;
  border-radius: var(--imago-radius-pill);
  border: 1px solid var(--imago-border-cyan-active);
  background: var(--imago-cyan-08);
  color: var(--imago-neon-cyan);
  font-size: 12.5px;
  font-weight: 600;
  cursor: pointer;
  transition: background 120ms ease, border-color 120ms ease;

  &:hover:not(:disabled) {
    background: var(--imago-cyan-06);
    border-color: var(--imago-neon-cyan);
  }

  &:focus-visible {
    outline: none;
    box-shadow: 0 0 0 2px var(--imago-border-cyan-active);
  }

  &:disabled {
    opacity: 0.6;
    cursor: default;
  }
}

// ── Selection-driven contextual control bar (openimago-e6k1) ──
//
// ONE slim flat-black row pinned at the bottom, separated from the canvas by a
// single hairline. Holds the global BGM chip.
.story-cut__bar {
  flex: 0 0 auto;
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 16px;
  padding: 10px 16px;
  min-height: 48px;
  border-top: 1px solid var(--imago-border-soft);
  background: var(--imago-bg-deep);
}

.story-cut__control-empty {
  margin: 0;
  font-size: 11.5px;
  color: var(--imago-text-faint);
}

.story-cut__clear {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 4px;
  border-radius: var(--imago-radius-sm);
  border: 1px solid transparent;
  background: transparent;
  color: var(--imago-text-muted);
  cursor: pointer;
  transition: color 120ms ease, background 120ms ease;

  &:hover:not(:disabled) {
    color: var(--imago-neon-pink);
    background: color-mix(in srgb, var(--imago-neon-pink) 7%, transparent);
  }

  &:focus-visible {
    outline: none;
    box-shadow: 0 0 0 2px var(--imago-border-cyan-active);
  }

  &:disabled {
    opacity: 0.35;
    cursor: default;
  }
}

// Global BGM chip — right side of the bar; relative so its picker popover anchors
// above it. Flat surface with a hairline, icon + label + pick + clear inline.
.story-cut__bgm-chip {
  position: relative;
  flex: 0 0 auto;
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 5px 8px 5px 12px;
  max-width: 320px;
  border-radius: var(--imago-radius-pill);
  border: 1px solid var(--imago-border-subtle);
  background: var(--imago-bg-raised);
}

.story-cut__bgm-icon {
  flex: 0 0 auto;
  color: var(--imago-text-muted);
}

.story-cut__bgm-current {
  flex: 0 1 auto;
  min-width: 0;
  max-width: 160px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-size: 12px;
  color: var(--imago-text-primary);
}

// Echoes the segmented-tab pill style: flat cyan tint, hairline ring, no glow.
.story-cut__bgm-pick {
  padding: 5px 14px;
  border-radius: var(--imago-radius-pill);
  border: 1px solid var(--imago-border-cyan-active);
  background: var(--imago-cyan-08);
  color: var(--imago-neon-cyan);
  font-size: 11.5px;
  font-weight: 600;
  cursor: pointer;
  transition: background 120ms ease, border-color 120ms ease;

  &:hover {
    background: var(--imago-cyan-06);
    border-color: var(--imago-neon-cyan);
  }

  &:focus-visible {
    outline: none;
    box-shadow: 0 0 0 2px var(--imago-border-cyan-active);
  }
}

// Popover anchored above the BGM chip (the bar is the bottom-most row, so the
// list opens upward). Right-aligned to the chip, raised above the editor.
.story-cut__bgm-picker {
  position: absolute;
  right: 0;
  bottom: calc(100% + 6px);
  z-index: 20;
  width: 240px;
  border-radius: var(--imago-radius-md);
  border: 1px solid var(--imago-border-subtle);
  background: var(--imago-bg-deep);
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.5);
  max-height: 220px;
  overflow-y: auto;
}

.story-cut__bgm-list {
  list-style: none;
  margin: 0;
  padding: 4px;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.story-cut__bgm-option {
  width: 100%;
  text-align: left;
  padding: 7px 10px;
  border-radius: var(--imago-radius-sm);
  border: 1px solid transparent;
  background: transparent;
  color: var(--imago-text-primary);
  font-size: 11.5px;
  cursor: pointer;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  transition: background 120ms ease, border-color 120ms ease;

  &:hover {
    background: var(--imago-cyan-06);
  }

  &:focus-visible {
    outline: none;
    box-shadow: inset 0 0 0 1px var(--imago-border-cyan-active);
  }

  &--active {
    border-color: var(--imago-border-cyan-active);
    background: var(--imago-cyan-08);
    color: var(--imago-neon-cyan);
  }
}

// ── Reduced motion ───────────────────────────────────────────────────────────
// Honour the user's preference: drop the chrome's hover/focus transitions.
@media (prefers-reduced-motion: reduce) {
  .story-cut__assemble,
  .story-cut__clear,
  .story-cut__bgm-pick,
  .story-cut__bgm-option {
    transition: none;
  }
}
</style>
