// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change component structure or accessibility attributes
//
// StoryTimelinePanel
// ──────────────────
// Center-area content for the project workspace "时间线" (timeline) tab. Renders
// the current episode's generation workflow DAG (top) and its run history
// timeline (bottom). Read-only MVP — surfaces the already-computed
// `currentStoryWorkflowNodes` / `currentStoryRuns` projections from
// ProjectWorkspacePage that are currently calculated but never rendered.
//
// All data is owned by the parent (page); this component is purely
// presentational. Selection is emitted so the page can open the relevant
// node / run detail. Re-run / regenerate affordances are out of scope here.
//
// Layout, top → bottom:
//   1. Workflow DAG — one card per node: tool-kind glyph, label, model,
//      dependency hints (dependsOn count), latest-run status dot. Dependency
//      *edges* are represented textually (count + names) rather than as a
//      drawn graph, which the coder may upgrade later.
//   2. Run history — reverse-chronological timeline: status badge, thumbnail,
//      truncated prompt, model, time. status drives the accent color.
// Each section degrades to a dashed empty placeholder when its data is empty.

<template>
  <section class="story-timeline" aria-label="生成时间线">
    <div class="story-timeline__scroll">
      <!-- ── 1. Workflow DAG ──────────────────────────────────────── -->
      <section class="dag" aria-labelledby="timeline-dag-heading">
        <div class="section-head">
          <OiIcon name="tool-cube" :size="15" />
          <h2 id="timeline-dag-heading" class="section-head__title">生成工作流</h2>
          <span class="section-head__count">{{ nodes.length }}</span>
        </div>

        <ul v-if="nodes.length > 0" class="node-grid">
          <li v-for="node in nodes" :key="node.id">
            <button
              type="button"
              class="node-card"
              :class="{ 'node-card--active': node.id === selectedNodeId }"
              :aria-pressed="node.id === selectedNodeId"
              :aria-label="`查看节点 ${node.label}`"
              @click="onNodeSelect(node.id)"
            >
              <div class="node-card__top">
                <span
                  :class="['tool-glyph', `tool-glyph--${node.toolKind}`]"
                  aria-hidden="true"
                >
                  <OiIcon :name="toolIcon(node.toolKind)" :size="15" />
                </span>
                <span class="node-card__label ellipsis-2">{{ node.label }}</span>
                <span
                  :class="['run-dot', `run-dot--${latestRunStatus(node)}`]"
                  :aria-label="`最新运行状态：${runStatusLabel(latestRunStatus(node))}`"
                  role="img"
                />
              </div>

              <p class="node-card__kind">{{ toolKindLabel(node.toolKind) }}</p>

              <dl class="node-card__meta">
                <div v-if="node.model" class="node-card__meta-row">
                  <dt class="node-card__meta-key">模型</dt>
                  <dd class="node-card__meta-val ellipsis">{{ node.model }}</dd>
                </div>
                <div v-if="node.aspectRatio" class="node-card__meta-row">
                  <dt class="node-card__meta-key">画幅</dt>
                  <dd class="node-card__meta-val">{{ node.aspectRatio }}</dd>
                </div>
              </dl>

              <p
                v-if="node.dependsOn.length > 0"
                class="node-card__deps"
              >
                <OiIcon name="layers" :size="12" />
                依赖 {{ node.dependsOn.length }} 个上游节点
              </p>
            </button>
          </li>
        </ul>

        <div v-else class="section-empty">
          <div class="section-empty__frame" aria-hidden="true">
            <OiIcon name="tool-cube" :size="22" />
          </div>
          <p class="section-empty__title">尚无生成节点</p>
          <p class="section-empty__hint">为剧集排程生成任务后，工作流节点会显示在这里</p>
        </div>
      </section>

      <!-- ── 2. Run history ───────────────────────────────────────── -->
      <section class="runs" aria-labelledby="timeline-runs-heading">
        <div class="section-head">
          <OiIcon name="history" :size="15" />
          <h2 id="timeline-runs-heading" class="section-head__title">运行历史</h2>
          <span class="section-head__count">{{ runs.length }}</span>
        </div>

        <ol v-if="runs.length > 0" class="run-list">
          <li v-for="run in runs" :key="run.id" class="run-line">
            <span class="run-line__rail" aria-hidden="true">
              <span :class="['run-line__marker', `run-line__marker--${run.status}`]" />
            </span>

            <button
              type="button"
              class="run-item"
              :class="{ 'run-item--active': run.id === selectedRunId }"
              :aria-pressed="run.id === selectedRunId"
              :aria-label="`查看运行 ${runStatusLabel(run.status)} ${run.model}`"
              @click="onRunSelect(run.id)"
            >
              <div class="run-item__thumb">
                <img
                  v-if="run.thumbnailUrl"
                  :src="run.thumbnailUrl"
                  :alt="`运行结果缩略图`"
                  class="run-item__image"
                  loading="lazy"
                >
                <span v-else class="run-item__thumb-fallback" aria-hidden="true">
                  <OiIcon name="image-card" :size="18" />
                </span>
              </div>

              <div class="run-item__body">
                <div class="run-item__head">
                  <span :class="['status-badge', `status-badge--${run.status}`]">
                    <span class="status-badge__dot" aria-hidden="true" />
                    {{ runStatusLabel(run.status) }}
                  </span>
                  <span class="run-item__model ellipsis">{{ run.model }}</span>
                </div>

                <p v-if="run.prompt" class="run-item__prompt ellipsis-2">
                  {{ run.prompt }}
                </p>

                <p v-if="run.error" class="run-item__error ellipsis-2">
                  {{ run.error }}
                </p>

                <div class="run-item__foot">
                  <time class="run-item__time" :datetime="run.startedAt">
                    <OiIcon name="clock-outline" :size="11" />
                    {{ formatRunTime(run.startedAt) }}
                  </time>
                </div>
              </div>
            </button>
          </li>
        </ol>

        <div v-else class="section-empty">
          <div class="section-empty__frame" aria-hidden="true">
            <OiIcon name="history" :size="22" />
          </div>
          <p class="section-empty__title">暂无运行记录</p>
          <p class="section-empty__hint">生成任务运行后，历史记录会按时间顺序显示在这里</p>
        </div>
      </section>
    </div>
  </section>
</template>

<script setup lang="ts">
import OiIcon from 'src/components/ui/OiIcon.vue'
import type { OiIconName } from 'src/components/ui/OiIcon.vue'
import type {
  StoryWorkflowNodeSummary,
  StoryRunSummary,
} from 'src/components/session-workspace/types'
import { resolveLatestRunStatus } from 'src/utils/story-timeline'
import { formatIsoRelative } from 'src/utils/format-time'

type RunStatus = StoryRunSummary['status']

// ── Props ────────────────────────────────────────────────────────────────────

const props = withDefaults(defineProps<{
  /** Workflow DAG nodes for the current episode. */
  nodes?: StoryWorkflowNodeSummary[]
  /** Generation runs, expected reverse-chronological (newest first). */
  runs?: StoryRunSummary[]
  /** Currently selected node (highlights its card). */
  selectedNodeId?: string | null
  /** Currently selected run (highlights its item). */
  selectedRunId?: string | null
}>(), {
  nodes: () => [],
  runs: () => [],
  selectedNodeId: null,
  selectedRunId: null,
})

const emit = defineEmits<{
  (e: 'node-select', id: string): void
  (e: 'run-select', id: string): void
}>()

// ── Handlers ──────────────────────────────────────────────────────────────────

function onNodeSelect(id: string): void {
  emit('node-select', id)
}

function onRunSelect(id: string): void {
  emit('run-select', id)
}

// ── Label / glyph helpers ─────────────────────────────────────────────────────

function toolIcon(kind: StoryWorkflowNodeSummary['toolKind']): OiIconName {
  switch (kind) {
    case 'image_generate': return 'image-card'
    case 'video_generate': return 'canvas'
    case 'image_edit': return 'enhance-wave'
  }
}

function toolKindLabel(kind: StoryWorkflowNodeSummary['toolKind']): string {
  // TODO(coder): localize via i18n if a translation layer is introduced.
  switch (kind) {
    case 'image_generate': return '图像生成'
    case 'video_generate': return '视频生成'
    case 'image_edit': return '图像编辑'
  }
}

function runStatusLabel(status: RunStatus | 'none'): string {
  // TODO(coder): localize via i18n if a translation layer is introduced.
  switch (status) {
    case 'completed': return '已完成'
    case 'running': return '进行中'
    case 'failed': return '失败'
    case 'queued': return '排队中'
    case 'none': return '未运行'
  }
}

/** Latest-run status for a node, resolved against `runs` by `latestRunId`. */
function latestRunStatus(node: StoryWorkflowNodeSummary): RunStatus | 'none' {
  return resolveLatestRunStatus(node.latestRunId, props.runs)
}

/** Human-readable relative label for a run's start time. */
function formatRunTime(startedAt: string): string {
  return formatIsoRelative(startedAt) || startedAt
}
</script>

<style lang="scss" scoped>
.story-timeline {
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
  min-height: 0;
  background: linear-gradient(180deg, var(--imago-bg-deep), var(--imago-bg-void) 40%);
}

.story-timeline__scroll {
  flex: 1 1 auto;
  min-height: 0;
  overflow-y: auto;
  padding: 22px 22px 28px;
  display: flex;
  flex-direction: column;
  gap: 26px;
}

// ── Section heading (shared) ──────────────────────────────────────────────────

.section-head {
  display: flex;
  align-items: center;
  gap: 8px;
  color: var(--imago-text-secondary);
  margin-bottom: 12px;
}

.section-head__title {
  margin: 0;
  font-size: 13.5px;
  font-weight: 600;
  color: var(--imago-text-primary);
}

.section-head__count {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 20px;
  height: 20px;
  padding: 0 6px;
  border-radius: var(--imago-radius-pill);
  background: var(--imago-bg-raised);
  color: var(--imago-text-dim);
  font-size: 11px;
  font-weight: 600;
  font-variant-numeric: tabular-nums;
}

// ── Section empty state (shared) ──────────────────────────────────────────────

.section-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 30px 18px;
  border: 1px dashed var(--imago-border-soft);
  border-radius: var(--imago-radius-lg);
  text-align: center;
}

.section-empty__frame {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 52px;
  height: 52px;
  border-radius: var(--imago-radius-lg);
  background: radial-gradient(circle at center, rgba(0, 240, 255, 0.05), transparent 70%);
  border: 1px solid var(--imago-border-soft);
  color: var(--imago-neon-cyan);
}

.section-empty__title {
  margin: 0;
  font-size: 12.5px;
  font-weight: 600;
  color: var(--imago-text-secondary);
}

.section-empty__hint {
  margin: 0;
  max-width: 280px;
  font-size: 11px;
  line-height: 1.55;
  color: var(--imago-text-faint);
}

// ── 1. Workflow DAG ───────────────────────────────────────────────────────────

.node-grid {
  list-style: none;
  margin: 0;
  padding: 0;
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  gap: 12px;
}

.node-card {
  display: flex;
  flex-direction: column;
  gap: 8px;
  width: 100%;
  padding: 12px 14px;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-lg);
  background: var(--imago-bg-surface);
  text-align: left;
  cursor: pointer;
  transition: border-color 120ms ease, background 120ms ease, box-shadow 120ms ease;
}

.node-card:hover {
  border-color: var(--imago-border-cyan);
  background: var(--imago-cyan-04);
}

.node-card--active {
  border-color: var(--imago-border-cyan-active);
  background: var(--imago-cyan-04);
  box-shadow:
    inset 0 0 0 1px var(--imago-border-cyan-active),
    0 0 18px rgba(0, 240, 255, 0.08);
}

.node-card__top {
  display: flex;
  align-items: flex-start;
  gap: 8px;
}

.tool-glyph {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  border-radius: var(--imago-radius-md);
  background: var(--imago-bg-raised);
  border: 1px solid var(--imago-border-soft);
  color: var(--imago-text-secondary);
  flex-shrink: 0;
}

.tool-glyph--image_generate {
  color: var(--imago-neon-cyan);
  border-color: var(--imago-border-cyan);
}

.tool-glyph--video_generate {
  color: var(--imago-neon-purple);
  border-color: var(--imago-border-purple);
}

.tool-glyph--image_edit {
  color: var(--imago-neon-pink);
  border-color: rgba(255, 45, 149, 0.32);
}

.node-card__label {
  flex: 1 1 auto;
  min-width: 0;
  font-size: 13px;
  font-weight: 600;
  line-height: 1.35;
  color: var(--imago-text-primary);
}

.node-card__kind {
  margin: 0;
  font-size: 10.5px;
  font-weight: 600;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  color: var(--imago-text-dim);
}

.node-card__meta {
  display: flex;
  flex-direction: column;
  gap: 3px;
  margin: 0;
}

.node-card__meta-row {
  display: flex;
  align-items: baseline;
  gap: 8px;
  min-width: 0;
}

.node-card__meta-key {
  flex-shrink: 0;
  width: 30px;
  font-size: 10.5px;
  color: var(--imago-text-faint);
}

.node-card__meta-val {
  margin: 0;
  min-width: 0;
  font-size: 11px;
  color: var(--imago-text-muted);
  font-variant-numeric: tabular-nums;
}

.node-card__deps {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  margin: 0;
  padding-top: 2px;
  font-size: 10.5px;
  color: var(--imago-text-dim);
}

// Run-status dot on the node card
.run-dot {
  width: 9px;
  height: 9px;
  border-radius: 50%;
  flex-shrink: 0;
  margin-top: 4px;
  background: var(--imago-text-faint);
}

.run-dot--completed { background: var(--imago-neon-green); box-shadow: 0 0 6px rgba(57, 255, 20, 0.5); }
.run-dot--running { background: var(--imago-neon-cyan); box-shadow: 0 0 6px rgba(0, 240, 255, 0.6); }
.run-dot--failed { background: var(--imago-neon-pink); box-shadow: 0 0 6px rgba(255, 45, 149, 0.5); }
.run-dot--queued { background: var(--imago-text-dim); }
.run-dot--none { background: transparent; border: 1px solid var(--imago-border-soft); }

// ── 2. Run history timeline ───────────────────────────────────────────────────

.run-list {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
}

.run-line {
  display: flex;
  gap: 12px;
}

.run-line__rail {
  position: relative;
  flex-shrink: 0;
  width: 14px;
  display: flex;
  justify-content: center;
}

// Connecting vertical line through the rail
.run-line__rail::before {
  content: '';
  position: absolute;
  top: 0;
  bottom: 0;
  left: 50%;
  width: 1px;
  background: var(--imago-border-soft);
  transform: translateX(-50%);
}

.run-line:first-child .run-line__rail::before { top: 18px; }
.run-line:last-child .run-line__rail::before { bottom: calc(100% - 18px); }

.run-line__marker {
  position: relative;
  z-index: 1;
  width: 12px;
  height: 12px;
  border-radius: 50%;
  margin-top: 14px;
  background: var(--imago-bg-void);
  border: 2px solid var(--imago-text-dim);
}

.run-line__marker--completed { border-color: var(--imago-neon-green); }
.run-line__marker--running {
  border-color: var(--imago-neon-cyan);
  box-shadow: 0 0 8px rgba(0, 240, 255, 0.6);
  animation: run-pulse 1.4s ease-in-out infinite;
}
.run-line__marker--failed { border-color: var(--imago-neon-pink); }
.run-line__marker--queued { border-color: var(--imago-text-dim); }

@keyframes run-pulse {
  0%, 100% { box-shadow: 0 0 4px rgba(0, 240, 255, 0.4); }
  50% { box-shadow: 0 0 12px rgba(0, 240, 255, 0.85); }
}

.run-item {
  flex: 1 1 auto;
  min-width: 0;
  display: flex;
  gap: 12px;
  margin: 8px 0;
  padding: 10px;
  border: 1px solid var(--imago-border-soft);
  border-radius: var(--imago-radius-lg);
  background: var(--imago-bg-surface);
  text-align: left;
  cursor: pointer;
  transition: border-color 120ms ease, background 120ms ease, box-shadow 120ms ease;
}

.run-item:hover {
  border-color: var(--imago-border-cyan);
  background: var(--imago-cyan-04);
}

.run-item--active {
  border-color: var(--imago-border-cyan-active);
  background: var(--imago-cyan-04);
  box-shadow:
    inset 0 0 0 1px var(--imago-border-cyan-active),
    0 0 18px rgba(0, 240, 255, 0.08);
}

.run-item__thumb {
  position: relative;
  width: 64px;
  height: 64px;
  flex-shrink: 0;
  border-radius: var(--imago-radius-md);
  overflow: hidden;
  background: var(--imago-bg-raised);
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--imago-text-faint);
}

.run-item__image {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.run-item__thumb-fallback {
  display: inline-flex;
  align-items: center;
  justify-content: center;
}

.run-item__body {
  flex: 1 1 auto;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 5px;
}

.run-item__head {
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 0;
}

.run-item__model {
  font-size: 11px;
  color: var(--imago-text-muted);
  font-variant-numeric: tabular-nums;
  min-width: 0;
}

.run-item__prompt {
  margin: 0;
  font-size: 11.5px;
  line-height: 1.45;
  color: var(--imago-text-secondary);
}

.run-item__error {
  margin: 0;
  font-size: 11px;
  line-height: 1.4;
  color: var(--imago-neon-pink);
}

.run-item__foot {
  display: flex;
  align-items: center;
}

.run-item__time {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-size: 10.5px;
  color: var(--imago-text-faint);
  font-variant-numeric: tabular-nums;
}

// ── Status badge (run) ────────────────────────────────────────────────────────

.status-badge {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  flex-shrink: 0;
  padding: 2px 9px;
  border-radius: var(--imago-radius-pill);
  font-size: 10px;
  font-weight: 600;
  letter-spacing: 0.02em;
  border: 1px solid var(--imago-border-soft);
  background: var(--imago-bg-raised);
  color: var(--imago-text-dim);
}

.status-badge__dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: currentColor;
  flex-shrink: 0;
}

.status-badge--completed {
  border-color: rgba(57, 255, 20, 0.32);
  background: var(--imago-green-20);
  color: var(--imago-neon-green);
}

.status-badge--running {
  border-color: var(--imago-border-cyan-active);
  background: var(--imago-cyan-08);
  color: var(--imago-neon-cyan);
}

.status-badge--failed {
  border-color: rgba(255, 45, 149, 0.4);
  background: rgba(255, 45, 149, 0.1);
  color: var(--imago-neon-pink);
}

// `queued` keeps the neutral base styling.

// ── Utility ──────────────────────────────────────────────────────────────────

.ellipsis {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.ellipsis-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

// ── Responsive ────────────────────────────────────────────────────────────────

@media (max-width: 900px) {
  .story-timeline__scroll {
    padding: 16px 14px 22px;
    gap: 20px;
  }

  .node-grid {
    grid-template-columns: 1fr;
  }
}

@media (prefers-reduced-motion: reduce) {
  .node-card,
  .run-item {
    transition: none;
  }

  .run-line__marker--running {
    animation: none;
  }
}
</style>
