<!--
  DESIGN SPEC — generated by Designer agent
  Coder: implement TODO items, do not change component structure or accessibility attributes

  Visual direction: APPROVED minimal CapCut/剪映 editor (docs/images/cut_panel.png).
  Flat pure-black canvas, generous negative space, NO glow / NO heavy gradients /
  NO thick neon borders. The cyan accent appears ONLY on the active play affordance
  and the selected clip (the latter lives in omniclip's shadow DOM, tuned via the
  --omni-* variables on .story-cut__editor + IMAGO_TO_OMNI_THEME). Everything Vue
  owns here — empty, orphan, transitions, BGM, loading/error — is redesigned to
  read as quiet chrome around the floating preview + filmstrip the editor renders.

  NOTE TO CODER: script setup logic, props, emits, the omniclip mount/hydrate flow,
  and defineExpose are unchanged from the prior revision and must stay so. Only the
  template structure and <style scoped> were reshaped for the new look.
  ──────────────────────────────────────────────────────────────────────────────

  StoryCutPanel — the 时间线 tab's NLE Cut editor (ADR 0006/0007, openimago-4eiw).
  Replaces the old workflow-DAG StoryTimelinePanel.

  Mounts the vendored omniclip fork's <construct-editor>, hydrates it from the
  episode's cut.json (canonical, ownership model A), and persists edits through
  the cut write endpoints with the cut's own optimistic-concurrency clock.

  BROWSER NOTE: the omniclip editor needs WebCodecs + SharedArrayBuffer +
  IndexedDB and is loaded via a runtime dynamic import of the vendored fork
  (excluded from repo typecheck). The data orchestration (hydrate mapping,
  media resolution, edit dispatch + 409 retry) lives in tested src/utils/cut
  modules. See src/vendor/omniclip-fork/LOCAL_VALIDATION.md for the manual
  browser checks.
-->
<template>
  <section class="story-cut" aria-label="时间线粗剪">
    <!-- ── Empty state: episode has no Cut yet → offer to assemble ── -->
    <div v-if="isEmptyCut" class="story-cut__empty">
      <div class="story-cut__empty-frame" aria-hidden="true">
        <OiIcon name="canvas" :size="24" />
      </div>
      <p class="story-cut__empty-title">尚未生成粗剪</p>
      <p class="story-cut__empty-hint">
        从本集已完成的镜头自动拼接一个粗剪，然后在时间线上修剪、排序与转场。
      </p>
      <button
        type="button"
        class="story-cut__assemble"
        :disabled="assembling"
        @click="onAssemble"
      >
        <OiIcon name="enhance-wave" :size="15" />
        {{ assembling ? '正在拼接…' : '自动拼接粗剪' }}
      </button>
    </div>

    <!-- ── Cut editor ── -->
    <template v-else>
      <div v-if="orphanCount > 0" class="story-cut__orphan-banner" role="status">
        <OiIcon name="layers" :size="13" />
        {{ orphanCount }} 个片段的源镜头已不存在，已标记为缺失（灰色虚线）。
      </div>

      <!-- omniclip's editor custom element (registered by the fork on load). -->
      <div ref="editorHost" class="story-cut__editor" data-testid="cut-editor-host">
        <construct-editor v-if="editorReady" class="story-cut__construct" />
        <p v-else class="story-cut__loading">
          {{ editorError ? editorError : '正在加载剪辑器…' }}
        </p>
      </div>

      <!-- ── Selection-driven contextual control bar (openimago-e6k1) ──
           ONE slim row, CapCut-style: contextual transition controls on the LEFT
           (only when a clip with a following clip is selected), the global BGM
           chip on the RIGHT (always shown — BGM is a property of the whole cut).
           Replaces the old always-on all-boundaries dock. -->
      <div class="story-cut__bar" data-testid="cut-controls">
        <!-- LEFT: contextual transition editor for the selected clip's boundary. -->
        <div class="story-cut__bar-context">
          <div
            v-if="selectedBoundary"
            class="story-cut__transition"
            data-testid="transition-boundary"
          >
            <span class="story-cut__transition-label">
              <OiIcon name="layers" :size="13" />
              片段 {{ selectedBoundary.position }} → {{ selectedBoundary.position + 1 }} 转场
            </span>
            <div class="story-cut__kinds" role="group" aria-label="转场类型">
              <button
                v-for="k in transitionKinds"
                :key="k"
                type="button"
                class="story-cut__kind"
                :class="{ 'story-cut__kind--active': selectedBoundary.transition?.kind === k }"
                :aria-pressed="selectedBoundary.transition?.kind === k"
                @click="onTransitionKind(selectedBoundary.afterClipId, k)"
              >
                {{ TRANSITION_KIND_LABELS[k] }}
              </button>
            </div>
            <label class="story-cut__duration">
              <span class="story-cut__duration-text">时长</span>
              <input
                class="story-cut__duration-input"
                type="number"
                min="0"
                step="0.1"
                :value="selectedBoundary.transition && selectedBoundary.transition.kind !== 'cut' ? selectedBoundary.transition.durationSeconds : 0"
                :disabled="!selectedBoundary.transition || selectedBoundary.transition.kind === 'cut'"
                aria-label="转场时长（秒）"
                @change="onTransitionDuration(selectedBoundary.afterClipId, Number(($event.target as HTMLInputElement).value))"
              />
              <span class="story-cut__duration-unit">秒</span>
            </label>
            <button
              type="button"
              class="story-cut__clear"
              :disabled="!selectedBoundary.transition"
              aria-label="清除转场"
              @click="clearTransitionAt(selectedBoundary.afterClipId)"
            >
              <OiIcon name="canvas" :size="13" />
            </button>
          </div>
          <p v-else class="story-cut__bar-hint">
            选中一个片段以编辑其转场
          </p>
        </div>

        <!-- RIGHT: global BGM chip (always shown). -->
        <div class="story-cut__bgm-chip">
          <OiIcon name="enhance-wave" :size="13" class="story-cut__bgm-icon" />
          <span class="story-cut__bgm-current">
            {{ bgmLabel ?? '未设置背景音乐' }}
          </span>
          <button
            type="button"
            class="story-cut__bgm-pick"
            @click="toggleBgmPicker"
          >
            {{ bgmLabel ? '更换' : '选择' }}
          </button>
          <button
            v-if="bgmLabel"
            type="button"
            class="story-cut__clear"
            aria-label="清除背景音乐"
            @click="clearBgm"
          >
            <OiIcon name="canvas" :size="13" />
          </button>

          <!-- Picker popover — opens above the chip. -->
          <div v-if="bgmPickerOpen" class="story-cut__bgm-picker" data-testid="bgm-picker">
            <p v-if="loadingAssets" class="story-cut__control-empty">正在加载音频…</p>
            <p v-else-if="audioAssets.length === 0" class="story-cut__control-empty">
              没有可用的音频素材。
            </p>
            <ul v-else class="story-cut__bgm-list">
              <li v-for="asset in audioAssets" :key="asset.id">
                <button
                  type="button"
                  class="story-cut__bgm-option"
                  :class="{ 'story-cut__bgm-option--active': props.cut?.bgm?.artifactId === asset.id }"
                  @click="selectBgm(asset.id)"
                >
                  {{ asset.name || asset.filename || asset.id }}
                </button>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </template>
  </section>
</template>

<script setup lang="ts">
import { computed, ref, watch, onMounted, onBeforeUnmount, nextTick } from 'vue'
import OiIcon from 'src/components/ui/OiIcon.vue'
import type { StoryRunSummary, StoryShotSummary } from 'src/components/session-workspace/types'
import { CUT_TRANSITION_KINDS, type CutTransitionKind, type EpisodeCut } from 'src/utils/cut/cut-types'
import { makeShotMediaResolver } from 'src/utils/cut/shot-media-resolver'
import { buildHydrationPayload, type BgmMediaSource } from 'src/utils/cut/cut-hydration'
import { dispatchCutEdit, type CutEdit } from 'src/utils/cut/cut-edit-dispatcher'
import { buildClipMenuItems } from 'src/utils/cut/clip-menu-items'
import { transitionBoundaries, resolveBgmLabel } from 'src/utils/cut/cut-controls'
import { bgmAuthHeaders } from 'src/utils/cut/bgm-auth'
import type { LoadOmniclipFork, OmniclipForkApi } from 'src/utils/cut/fork-contract'
import { api, ApiError, type OpenimagoAsset } from 'src/api/client'
import { useAuthStore } from 'src/stores/auth'

/** Default transition length (s) when a kind is first chosen on a boundary. */
const DEFAULT_TRANSITION_SECONDS = 0.5
/** Localised transition-kind labels (kinds mirror backend CUT_TRANSITION_KINDS). */
const TRANSITION_KIND_LABELS: Record<CutTransitionKind, string> = {
  cut: '硬切',
  dissolve: '溶解',
  fade: '淡入淡出',
}

const props = defineProps<{
  projectId: string
  episodeId: string
  /** canonical cut for the episode (empty clips => never cut). */
  cut: EpisodeCut | null
  shots: StoryShotSummary[]
  runs: StoryRunSummary[]
}>()

const emit = defineEmits<{
  /** ask the page to (re)assemble + refetch the cut. */
  (e: 'request-assemble'): void
  /** a persisted edit changed the cut — page should refetch. */
  (e: 'cut-changed'): void
  /** surface a conflict that lost after one retry. */
  (e: 'cut-conflict'): void
  /** clip menu (openimago-e0n3): regenerate the source shot's media. */
  (e: 'clip-regenerate', sourceShotId: string): void
  /** clip menu: edit the source shot's description. */
  (e: 'clip-manual-edit', sourceShotId: string): void
  /** clip menu: delete the CLIP (not the shot). */
  (e: 'clip-delete', clipId: string): void
  /** clip menu: attach the clip's media to the chat as a reference. */
  (e: 'clip-add-to-chat', sourceShotId: string): void
}>()

const editorHost = ref<HTMLElement | null>(null)
const editorReady = ref(false)
const editorError = ref<string | null>(null)
const assembling = ref(false)

// Auth store for the BGM media fetch (openimago-tc8t): the BGM resolves to the
// authed /api/.../download, so resolveBgmSource threads Authorization: Bearer
// <token> down to the fork. Clip /mock previews stay unauthenticated.
const auth = useAuthStore()

// Local optimistic-concurrency clock for cut writes (ADR 0008 #3). Seeded from
// the canonical cut and advanced by each write's returned updatedAt, so the
// panel does NOT re-hydrate on every edit (which would re-import media). The
// rare cross-actor agent-assemble race is still caught by emit('cut-changed') →
// page refetch + runCutMutation's 409 retry.
const lastUpdatedAt = ref<string | undefined>(props.cut?.updatedAt)

let fork: OmniclipForkApi | null = null
let unregisterClipMenu: (() => void) | null = null
let unsubscribeEdits: (() => void) | null = null
let unsubscribeSelection: (() => void) | null = null

const isEmptyCut = computed(() => !props.cut || props.cut.clips.length === 0)

// Currently-selected clip id (from the fork's onSelectionChange channel) — drives
// the SELECTION-DRIVEN contextual transition controls (openimago-e6k1). null when
// nothing is selected. NOT persisted; pure UI state.
const selectedClipId = ref<string | null>(null)

// Resolve clip media (shot -> latest completed run preview) for hydration.
const mediaResolver = computed(() => makeShotMediaResolver(props.shots, props.runs))

// Orphans: clips whose source shot has no usable media (rendered greyed).
const orphanCount = computed(() => {
  if (!props.cut) return 0
  return props.cut.clips.filter((c) => mediaResolver.value(c.sourceShotId) === null).length
})

/** Assemble the first cut from the episode's shots, then refetch. */
async function onAssemble(): Promise<void> {
  if (assembling.value) return
  assembling.value = true
  try {
    await api.assembleEpisodeCut(props.projectId, props.episodeId, props.cut?.updatedAt)
    emit('request-assemble')
  } catch (err) {
    if (err instanceof ApiError && err.status === 409) {
      emit('cut-conflict')
    } else {
      editorError.value = '拼接失败'
    }
  } finally {
    assembling.value = false
  }
}

/** Persist one editor edit through the cut endpoints (tested dispatcher). */
async function persistEdit(edit: CutEdit): Promise<void> {
  const outcome = await dispatchCutEdit(
    {
      api,
      projectId: props.projectId,
      episodeId: props.episodeId,
      // Read the LOCAL clock (decision 3): structural edits chain off each
      // other's returned updatedAt without a refetch between them.
      currentUpdatedAt: () => lastUpdatedAt.value,
      refetch: async () => {
        const fresh = await api.projectStoryCut(props.projectId, props.episodeId)
        lastUpdatedAt.value = fresh?.updatedAt
        return fresh?.updatedAt
      },
      // Advance the local clock from each write so the next edit's expected
      // updatedAt is current — no re-hydration, no per-edit refetch.
      onWritten: (updatedAt) => {
        lastUpdatedAt.value = updatedAt
      },
    },
    edit,
  )
  if (outcome === 'conflict') emit('cut-conflict')
  else emit('cut-changed')
}

// ── HOST-DRIVEN transition + BGM controls (ADR 0008 #1b, openimago-ofdw) ──
//
// Transitions + BGM are NOT captured from omniclip's gesture diff (omniclip
// 1.0.7 has no native UI for them). These host controls originate the edits:
// each calls the fork setter for live editor preview where it makes sense, AND
// persistEdit with the matching CutEdit (already wired through dispatchCutEdit).
// The pure data-shaping (which boundaries exist, current BGM label) lives in the
// unit-tested cut-controls helpers.

const transitionKinds = CUT_TRANSITION_KINDS

/** The clip boundaries (N-1) that can hold a transition, with their current one. */
const boundaries = computed(() =>
  transitionBoundaries(props.cut?.clips ?? [], props.cut?.transitions ?? []),
)

/**
 * The boundary AFTER the selected clip — what the contextual transition editor
 * binds to (openimago-e6k1). Null when nothing is selected OR the selected clip
 * is the last one (no following clip → no boundary), so the controls show a quiet
 * hint instead. A transition lives on the boundary whose `afterClipId` is the
 * selected clip.
 */
const selectedBoundary = computed(
  () => boundaries.value.find((b) => b.afterClipId === selectedClipId.value) ?? null,
)

// Audio assets for the BGM picker (api.listAssets type-filtered to audio).
const audioAssets = ref<OpenimagoAsset[]>([])
const bgmPickerOpen = ref(false)
const loadingAssets = ref(false)

const bgmLabel = computed(() => resolveBgmLabel(props.cut?.bgm, audioAssets.value))

/** Lazily load audio assets the first time the BGM picker is opened. */
async function loadAudioAssets(): Promise<void> {
  if (loadingAssets.value) return
  loadingAssets.value = true
  try {
    audioAssets.value = await api.listAssets({ type: 'audio' })
  } catch (err) {
    console.error('StoryCutPanel: failed to load audio assets', err)
  } finally {
    loadingAssets.value = false
  }
}

async function toggleBgmPicker(): Promise<void> {
  bgmPickerOpen.value = !bgmPickerOpen.value
  if (bgmPickerOpen.value && audioAssets.value.length === 0) {
    await loadAudioAssets()
  }
}

/** Set/replace a boundary's transition: live preview via the fork + persist. */
async function applyTransition(
  afterClipId: string,
  kind: CutTransitionKind,
  durationSeconds: number,
): Promise<void> {
  fork?.setTransition({ afterEffectId: afterClipId, kind, durationMs: durationSeconds * 1000 })
  await persistEdit({ kind: 'set-transition', afterClipId, transitionKind: kind, durationSeconds })
}

/** Change a boundary's transition kind, keeping (or seeding) its duration. */
function onTransitionKind(afterClipId: string, kind: CutTransitionKind): void {
  const current = boundaries.value.find((b) => b.afterClipId === afterClipId)?.transition
  // 'cut' is an instantaneous boundary — duration is always 0 (backend clamps it
  // too, but keep the UI honest so the number field disables sensibly).
  const duration =
    kind === 'cut' ? 0 : (current && current.kind !== 'cut' ? current.durationSeconds : DEFAULT_TRANSITION_SECONDS)
  void applyTransition(afterClipId, kind, duration)
}

/** Change a boundary's transition duration (kind unchanged). */
function onTransitionDuration(afterClipId: string, durationSeconds: number): void {
  const current = boundaries.value.find((b) => b.afterClipId === afterClipId)?.transition
  if (!current || current.kind === 'cut') return
  if (!Number.isFinite(durationSeconds) || durationSeconds < 0) return
  void applyTransition(afterClipId, current.kind, durationSeconds)
}

/** Remove a boundary's transition: clear the preview + persist. */
async function clearTransitionAt(afterClipId: string): Promise<void> {
  fork?.clearTransition(afterClipId)
  await persistEdit({ kind: 'clear-transition', afterClipId })
}

/** Choose the Cut's single BGM bed. */
async function selectBgm(artifactId: string): Promise<void> {
  bgmPickerOpen.value = false
  await persistEdit({ kind: 'set-bgm', artifactId })
}

/** Remove the Cut's BGM bed. */
async function clearBgm(): Promise<void> {
  await persistEdit({ kind: 'clear-bgm' })
}

/**
 * Resolve a BGM artifactId → its servable media (url + display name) for
 * hydration (openimago-w5bu). Prefers the already-loaded audioAssets, falling
 * back to a single getAsset fetch when the picker hasn't loaded yet (the common
 * case on a fresh mount). Returns null on any failure so the lane is just
 * skipped rather than blocking the editor.
 */
async function resolveBgmSource(
  artifactId: string | undefined,
): Promise<{ id: string; source: BgmMediaSource } | null> {
  if (!artifactId) return null
  // The BGM url is the authed /api/.../download, so carry Bearer auth on the
  // fork's fetch (openimago-tc8t). Built from the auth store here in the host;
  // the fork never reaches into it.
  const headers = bgmAuthHeaders(auth.token)
  const cached = audioAssets.value.find((a) => a.id === artifactId)
  if (cached?.url) {
    return {
      id: artifactId,
      source: { url: cached.url, name: cached.name || cached.filename || artifactId, headers },
    }
  }
  try {
    const asset = await api.getAsset(artifactId)
    if (!asset?.url) return null
    return {
      id: artifactId,
      source: { url: asset.url, name: asset.name || asset.filename || artifactId, headers },
    }
  } catch (err) {
    console.error('StoryCutPanel: failed to resolve BGM asset for hydration', err)
    return null
  }
}

// ── BROWSER-ONLY: load the fork, mount the editor, hydrate from cut.json ──
//
// Guarded behind the runtime loader so the repo typecheck never reaches the
// vendored omniclip code. Hydration imports each clip's media via the fork and
// builds omniclip state from the canonical cut.

async function mountAndHydrate(): Promise<void> {
  if (isEmptyCut.value || !editorHost.value || editorReady.value) return

  // Phase 1 — load the fork module. A failure here is a bundling / module-load
  // problem (e.g. Vite dep-optimizer timeout), NOT a browser-capability issue.
  let loaded: OmniclipForkApi
  let applyImagoTheme: (wrapper: HTMLElement) => HTMLElement
  try {
    // Dynamic import via a runtime-computed path so the repo typecheck never
    // follows into the browser-only vendored fork (excluded from tsconfig).
    // Must be an ABSOLUTE app path (leading slash + extension): with
    // `@vite-ignore` the specifier reaches the browser verbatim, and a bare
    // 'src/vendor/...' would fail as a bare module specifier. (openimago-y90v)
    const forkModulePath = ['', 'src', 'vendor', 'omniclip-fork', 'load.ts'].join('/')
    const mod = (await import(/* @vite-ignore */ forkModulePath)) as unknown as {
      loadOmniclipFork: LoadOmniclipFork
    }
    ;({ fork: loaded, applyImagoTheme } = await mod.loadOmniclipFork())
  } catch (err) {
    editorError.value = '剪辑器模块加载失败（请检查 omniclip 依赖与构建配置）'
    console.error('StoryCutPanel: failed to load omniclip fork module', err)
    return
  }

  // Phase 2 — mount + wire. A failure here is a runtime / browser-API issue
  // (WebCodecs / SharedArrayBuffer / IndexedDB unavailable, or not isolated).
  try {
    fork = loaded
    applyImagoTheme(editorHost.value)

    // Register the per-clip context menu (openimago-e0n3). The menu items +
    // orphan-gating are the unit-tested buildClipMenuItems; each item emits to
    // the page, which runs the real action. isEnabled hides shot-bound items on
    // orphan clips (sourceShotId gone) but keeps 删除.
    unregisterClipMenu = fork.registerClipMenuItems(
      buildClipMenuItems({
        onRegenerate: (sourceShotId) => emit('clip-regenerate', sourceShotId),
        onManualEdit: (sourceShotId) => emit('clip-manual-edit', sourceShotId),
        onDeleteClip: (clipId) => emit('clip-delete', clipId),
        onAddToChat: (sourceShotId) => emit('clip-add-to-chat', sourceShotId),
      }),
    )

    // Resolve a clicked effect id → its sourceShotId for the context menu's
    // orphan-gating (effect id === CutClip.id). (openimago-1mcb)
    fork.setClipContextResolver(
      (effectId) => props.cut?.clips.find((c) => c.id === effectId)?.sourceShotId,
    )

    // Subscribe to clip-selection changes (openimago-e6k1) so the contextual
    // transition controls follow the selected clip. Pure UI state — does NOT
    // touch the persist/dispatch flow, so it is safe to wire before hydration.
    unsubscribeSelection = fork.onSelectionChange((id) => {
      selectedClipId.value = id
    })

    // Render <construct-editor> now that the fork is loaded.
    editorReady.value = true

    // Hydrate from the canonical cut (openimago-addv). buildHydrationPayload is
    // pure + unit-tested: it maps cut.json clips (ordered) + the media resolver
    // → the fork's HydrateClip[] (url + trim) and the transitions in omniclip
    // ms, splitting out orphans (which surface via the data-no-file path). The
    // fork imports each clip's media (importFromUrl) and places it as a trimmed
    // effect, then applies transitions.
    if (props.cut) {
      // Resolve the Cut's BGM artifact → a fetchable url up front (the bgm
      // resolver is sync; the asset lookup is async), then build the payload.
      // The fork places it on its own audio track → the green waveform lane
      // (openimago-w5bu). An unresolvable bgm is simply omitted.
      const bgmSource = await resolveBgmSource(props.cut.bgm?.artifactId)
      const { clips, transitions, bgm } = buildHydrationPayload(
        props.cut,
        mediaResolver.value,
        (artifactId) => (bgmSource && bgmSource.id === artifactId ? bgmSource.source : null),
      )
      await fork.hydrateFromCut(clips, transitions, bgm)
    }

    // Subscribe to committed editor gestures ONLY AFTER hydration has fully
    // settled (openimago-3xbg). hydrateFromCut serially imports + places every
    // clip; each import is an async state mutation that on-edit's effects-diff
    // would otherwise observe with a still-incomplete baseline. If a user split
    // landed in the same debounce window as a late clip import, the diff saw the
    // late clip AND the split half as two unrelated additions against a stale
    // baseline → the split was dropped or (in adjacent timing) misread as a
    // trim/reorder, corrupting clip order + source ranges. Subscribing here means
    // the baseline is the COMPLETE hydrated timeline and no hydration import is
    // ever diffed as a user gesture. (ADR 0008 #1/#1a: the fork diffs its effects
    // snapshot per settled gesture and hands us ONE semantic CutEdit — reorder /
    // trim / split / delete; persistEdit routes it through the cut endpoints.
    // Transition/BGM are host-driven and do NOT arrive here. JS's single thread +
    // persistEdit's per-edit await serialise these user-paced gestures.)
    unsubscribeEdits = fork.onEdit((edit) => {
      void persistEdit(edit)
    })
  } catch (err) {
    // Roll editorReady back so the error <p> shows instead of an empty
    // <construct-editor> (openimago-ystd). editorReady is flipped true BEFORE
    // hydrateFromCut so omniclip mounts; a hydration throw (e.g. importFromUrl
    // failing on an unreachable/undecodable clip) must surface its message, not a
    // silent empty timeline.
    editorReady.value = false
    editorError.value = '剪辑器初始化失败（需要支持 WebCodecs 的浏览器环境）'
    console.error('StoryCutPanel: failed to initialise omniclip editor', err)
  }
}

/** Reset editor state and (re)mount once the host div is in the DOM. */
function remountEditor(): void {
  editorReady.value = false
  editorError.value = null
  // Re-seed the local clock from the (possibly newly-loaded) cut before the
  // fresh editor starts emitting edits.
  lastUpdatedAt.value = props.cut?.updatedAt
  unsubscribeEdits?.()
  unsubscribeEdits = null
  unsubscribeSelection?.()
  unsubscribeSelection = null
  selectedClipId.value = null
  unregisterClipMenu?.()
  unregisterClipMenu = null
  // nextTick so the editorHost div is bound before mountAndHydrate reads it.
  // (GAP 1, openimago-addv: an immediate watch ran during setup() before the
  // ref existed → early return → the editor never mounted.)
  void nextTick(() => mountAndHydrate())
}

// First mount: the host div exists by onMounted, so this never early-returns.
onMounted(remountEditor)

// Re-mount when the episode changes or the cut transitions empty↔non-empty.
watch(() => [props.episodeId, isEmptyCut.value] as const, remountEditor)

onBeforeUnmount(() => {
  unsubscribeEdits?.()
  unsubscribeEdits = null
  unsubscribeSelection?.()
  unsubscribeSelection = null
  unregisterClipMenu?.()
  unregisterClipMenu = null
  fork = null
})

// Expose persistEdit for the editor event bridge (wired during local validation).
defineExpose({ persistEdit })
</script>

<style lang="scss" scoped>
// ── Editor host ────────────────────────────────────────────────────────────────
//
// Flat pure-black canvas (no gradient — the approved image is a single deep black
// field so the floating 9:16 preview reads against pure negative space).
.story-cut {
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
  min-height: 0;
  background: var(--imago-bg-void);
}

.story-cut__editor {
  flex: 1 1 auto;
  min-height: 0;
  position: relative;
  // Map the imago tokens into omniclip's shadow DOM (applyImagoTheme also sets
  // these at runtime; declared here so an un-themed mount still reads them).
  // Tuned for the approved flat look: a WHITE 1px playhead, and a thin SOLID cyan
  // selected-clip accent with NO halo. Clip fill/border stay muted so unselected
  // frames recede; orphans quiet pink. (The green audio waveform is rendered by
  // omniclip itself and is not host-controllable, so no --omni-audio override.)
  //
  // AMBIENT GLOW (UPDATED reference docs/images/cut_panel.png): MUCH subtler and
  // cooler than the earlier cut_panel_v2 pass. Pixel-sampled from the canonical
  // image the wash is only ~2-6 RGB points above #08080f: a faint, near-uniform
  // COOL lift across the top (corners read ~(10,10,15) — blue +5, no cyan), plus
  // a barely-there WARM tint on the MID-LEFT only (~(14,11,12) — red +2). There
  // is NO strong cyan top-right and NO magenta top-left. Painted on the editor
  // HOST background so it shows in the dark margins around omniclip's 9:16
  // media-player pane. --omni-bg is transparent so the embedded panes do NOT
  // repaint solid void over this glow; the void base lives on the host instead.
  // Keep it dark and tasteful — barely perceptible, never a "glow".
  background:
    // faint cool lift across the whole top (neutral blue, very low alpha)
    radial-gradient(
      90% 55% at 50% 0%,
      color-mix(in srgb, var(--imago-neon-cyan) 3%, transparent),
      transparent 70%
    ),
    // barely-there warm tint on the mid-left only
    radial-gradient(
      45% 45% at 8% 42%,
      color-mix(in srgb, var(--imago-neon-pink) 3%, transparent),
      transparent 62%
    ),
    var(--imago-bg-void);
  --omni-bg: transparent;
  --omni-clip-fill: var(--imago-bg-surface);
  --omni-clip-border: var(--imago-border-soft);
  --omni-accent: var(--imago-neon-cyan);
  --omni-playhead: var(--imago-text-primary);
  --omni-text: var(--imago-text-primary);
  --omni-orphan: var(--imago-neon-pink);
}

// The editor now hosts a vertical two-pane layout (preview player above,
// timeline below — openimago-h8v6), so the <construct-editor> custom element
// must FILL the editor host for the panes to split its height. A custom element
// defaults to display:inline, so its :host{height:100%} would not take effect
// without an explicit block + full height here.
.story-cut__construct {
  display: block;
  width: 100%;
  height: 100%;
  min-height: 0;
  // The <construct-editor> element paints an opaque grey (~#111) by default,
  // which would cover the editor host's ambient glow. Make it transparent so the
  // warm/cool wash on .story-cut__editor shows through the panes' dark margins
  // (the timeline/player panes themselves are transparent via --omni-bg).
  background: transparent;
}

.story-cut__loading {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0;
  font-size: 12.5px;
  color: var(--imago-text-faint);
}

// Quiet inline notice — NOT a loud alert. Muted pink derived from the token so no
// hex is hardcoded; a faint tint + hairline rule, sitting above the editor.
.story-cut__orphan-banner {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 7px 14px;
  font-size: 11.5px;
  color: color-mix(in srgb, var(--imago-neon-pink) 78%, var(--imago-text-muted));
  background: color-mix(in srgb, var(--imago-neon-pink) 6%, transparent);
  border-bottom: 1px solid color-mix(in srgb, var(--imago-neon-pink) 18%, transparent);
}

.story-cut__empty {
  flex: 1 1 auto;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 10px;
  padding: 40px 24px;
  text-align: center;
}

// 60px rounded frame, hairline border, subtle cyan glyph — NO glow (flat look).
.story-cut__empty-frame {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 60px;
  height: 60px;
  border-radius: var(--imago-radius-lg);
  background: var(--imago-cyan-04);
  border: 1px solid var(--imago-border-cyan);
  color: var(--imago-neon-cyan);
}

.story-cut__empty-title {
  margin: 0;
  font-size: 14px;
  font-weight: 600;
  color: var(--imago-text-primary);
}

.story-cut__empty-hint {
  margin: 0;
  max-width: 340px;
  font-size: 11.5px;
  line-height: 1.6;
  color: var(--imago-text-faint);
}

// Slim cyan pill CTA — flat fill, hairline cyan ring, no glow. Hover only deepens
// the fill. Visible keyboard focus via a thin cyan ring.
.story-cut__assemble {
  display: inline-flex;
  align-items: center;
  gap: 7px;
  margin-top: 6px;
  padding: 9px 18px;
  border-radius: var(--imago-radius-pill);
  border: 1px solid var(--imago-border-cyan-active);
  background: var(--imago-cyan-08);
  color: var(--imago-neon-cyan);
  font-size: 12.5px;
  font-weight: 600;
  cursor: pointer;
  transition: background 120ms ease, border-color 120ms ease;

  &:hover:not(:disabled) {
    background: var(--imago-cyan-06);
    border-color: var(--imago-neon-cyan);
  }

  &:focus-visible {
    outline: none;
    box-shadow: 0 0 0 2px var(--imago-border-cyan-active);
  }

  &:disabled {
    opacity: 0.6;
    cursor: default;
  }
}

// ── Selection-driven contextual control bar (openimago-e6k1) ──
//
// ONE slim flat-black row pinned at the bottom, separated from the canvas by a
// single hairline (replaces the old always-on all-boundaries dock). Left holds
// the contextual transition editor for the SELECTED clip's boundary (or a quiet
// hint); right holds the global BGM chip. No glow; cyan only on the active
// transition pill + the BGM pick button.
.story-cut__bar {
  flex: 0 0 auto;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  padding: 10px 16px;
  min-height: 48px;
  border-top: 1px solid var(--imago-border-soft);
  background: var(--imago-bg-deep);
}

// Left half flexes to absorb the row; its content (transition editor or hint) is
// left-aligned and may wrap on narrow widths.
.story-cut__bar-context {
  flex: 1 1 auto;
  min-width: 0;
  display: flex;
  align-items: center;
}

// Quiet hint when nothing actionable is selected — muted, no chrome.
.story-cut__bar-hint {
  margin: 0;
  font-size: 11.5px;
  color: var(--imago-text-faint);
}

// The contextual transition editor: a single inline row of label + kind pills +
// duration + clear, bound to the selected clip's boundary.
.story-cut__transition {
  display: flex;
  align-items: center;
  gap: 12px;
  flex-wrap: wrap;
}

.story-cut__transition-label {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  font-size: 11.5px;
  font-weight: 600;
  color: var(--imago-text-muted);
  white-space: nowrap;
}

.story-cut__control-empty {
  margin: 0;
  font-size: 11.5px;
  color: var(--imago-text-faint);
}

.story-cut__kinds {
  display: inline-flex;
  gap: 4px;
}

// Pill toggles 硬切/溶解/淡入淡出 — text-only when inactive, a flat cyan tint when
// active (the only place cyan appears in this dock). No glow.
.story-cut__kind {
  padding: 4px 11px;
  border-radius: var(--imago-radius-pill);
  border: 1px solid var(--imago-border-soft);
  background: transparent;
  color: var(--imago-text-muted);
  font-size: 11px;
  cursor: pointer;
  transition: color 120ms ease, border-color 120ms ease, background 120ms ease;

  &:hover {
    color: var(--imago-text-primary);
    border-color: var(--imago-border-dim);
  }

  &:focus-visible {
    outline: none;
    box-shadow: 0 0 0 2px var(--imago-border-cyan-active);
  }

  &--active {
    color: var(--imago-neon-cyan);
    border-color: var(--imago-border-cyan-active);
    background: var(--imago-cyan-08);
  }
}

.story-cut__duration {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  font-size: 11px;
  color: var(--imago-text-faint);
}

.story-cut__duration-input {
  width: 56px;
  padding: 3px 6px;
  border-radius: var(--imago-radius-sm);
  border: 1px solid var(--imago-border-soft);
  background: var(--imago-bg-void);
  color: var(--imago-text-primary);
  font-size: 11px;

  &:focus {
    outline: none;
    border-color: var(--imago-border-cyan-active);
  }

  &:disabled {
    opacity: 0.45;
    cursor: default;
  }
}

.story-cut__clear {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 4px;
  border-radius: var(--imago-radius-sm);
  border: 1px solid transparent;
  background: transparent;
  color: var(--imago-text-muted);
  cursor: pointer;
  transition: color 120ms ease, background 120ms ease;

  &:hover:not(:disabled) {
    color: var(--imago-neon-pink);
    background: color-mix(in srgb, var(--imago-neon-pink) 7%, transparent);
  }

  &:focus-visible {
    outline: none;
    box-shadow: 0 0 0 2px var(--imago-border-cyan-active);
  }

  &:disabled {
    opacity: 0.35;
    cursor: default;
  }
}

// Global BGM chip — right side of the bar; relative so its picker popover anchors
// above it. Flat surface with a hairline, icon + label + pick + clear inline.
.story-cut__bgm-chip {
  position: relative;
  flex: 0 0 auto;
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 5px 8px 5px 12px;
  max-width: 320px;
  border-radius: var(--imago-radius-pill);
  border: 1px solid var(--imago-border-subtle);
  background: var(--imago-bg-raised);
}

.story-cut__bgm-icon {
  flex: 0 0 auto;
  color: var(--imago-text-muted);
}

.story-cut__bgm-current {
  flex: 0 1 auto;
  min-width: 0;
  max-width: 160px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-size: 12px;
  color: var(--imago-text-primary);
}

// Echoes the segmented-tab pill style: flat cyan tint, hairline ring, no glow.
.story-cut__bgm-pick {
  padding: 5px 14px;
  border-radius: var(--imago-radius-pill);
  border: 1px solid var(--imago-border-cyan-active);
  background: var(--imago-cyan-08);
  color: var(--imago-neon-cyan);
  font-size: 11.5px;
  font-weight: 600;
  cursor: pointer;
  transition: background 120ms ease, border-color 120ms ease;

  &:hover {
    background: var(--imago-cyan-06);
    border-color: var(--imago-neon-cyan);
  }

  &:focus-visible {
    outline: none;
    box-shadow: 0 0 0 2px var(--imago-border-cyan-active);
  }
}

// Popover anchored above the BGM chip (the bar is the bottom-most row, so the
// list opens upward). Right-aligned to the chip, raised above the editor.
.story-cut__bgm-picker {
  position: absolute;
  right: 0;
  bottom: calc(100% + 6px);
  z-index: 20;
  width: 240px;
  border-radius: var(--imago-radius-md);
  border: 1px solid var(--imago-border-subtle);
  background: var(--imago-bg-deep);
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.5);
  max-height: 220px;
  overflow-y: auto;
}

.story-cut__bgm-list {
  list-style: none;
  margin: 0;
  padding: 4px;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.story-cut__bgm-option {
  width: 100%;
  text-align: left;
  padding: 7px 10px;
  border-radius: var(--imago-radius-sm);
  border: 1px solid transparent;
  background: transparent;
  color: var(--imago-text-primary);
  font-size: 11.5px;
  cursor: pointer;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  transition: background 120ms ease, border-color 120ms ease;

  &:hover {
    background: var(--imago-cyan-06);
  }

  &:focus-visible {
    outline: none;
    box-shadow: inset 0 0 0 1px var(--imago-border-cyan-active);
  }

  &--active {
    border-color: var(--imago-border-cyan-active);
    background: var(--imago-cyan-08);
    color: var(--imago-neon-cyan);
  }
}

// ── Reduced motion ───────────────────────────────────────────────────────────
// Honour the user's preference: drop the chrome's hover/focus transitions.
@media (prefers-reduced-motion: reduce) {
  .story-cut__assemble,
  .story-cut__kind,
  .story-cut__clear,
  .story-cut__bgm-pick,
  .story-cut__bgm-option,
  .story-cut__duration-input {
    transition: none;
  }
}
</style>
