import { describe, it, expect } from 'vitest'
import { mount } from '@vue/test-utils'
import AuthPanel from '../../../components/auth/AuthPanel.vue'

// DESIGN SPEC — generated by Designer agent
// These tests pin the public contract of AuthPanel so the coder can wire
// global token-expiry handling against a stable interface.
describe('AuthPanel', () => {
  function mountPanel(props: Record<string, unknown> = {}) {
    const QInputStub = {
      template: '<label class="q-input-stub"><span class="q-input-stub__label">{{ label }}</span><input :value="modelValue" @input="$emit(\'update:modelValue\', $event.target.value)" /></label>',
      props: ['modelValue', 'label', 'rules', 'type'],
      emits: ['update:modelValue'],
    }
    const QFormStub = {
      template: '<form @submit.prevent="$emit(\'submit\', $event)"><slot /></form>',
      emits: ['submit'],
    }
    return mount(AuthPanel, {
      props: { variant: 'page', ...props },
      global: {
        stubs: {
          'router-link': true,
          'q-input': QInputStub,
          'q-form': QFormStub,
        },
      },
    })
  }

  it('renders the brand and login form by default', () => {
    const wrapper = mountPanel()
    expect(wrapper.text()).toContain('openimago')
    expect(wrapper.text()).toContain('邮箱地址')
    expect(wrapper.text()).toContain('密码')
  })

  it('emits "login" with credentials and rememberMe=false when the login form is submitted', async () => {
    const wrapper = mountPanel()
    const inputs = wrapper.findAll('input')
    // The q-input stub renders real <input> elements; fill them in
    if (inputs[0]) await inputs[0].setValue('user@example.com')
    if (inputs[1]) await inputs[1].setValue('hunter2')
    await wrapper.find('form').trigger('submit')
    const loginEvents = wrapper.emitted('login')
    expect(loginEvents).toBeTruthy()
    expect(loginEvents?.[0]?.[0]).toEqual({
      email: 'user@example.com',
      password: 'hunter2',
      rememberMe: false,
    })
  })

  it('emits "register" with username/email/password when the register form is submitted', async () => {
    const wrapper = mountPanel({ initialMode: 'register' })
    const inputs = wrapper.findAll('input')
    if (inputs[0]) await inputs[0].setValue('alice')
    if (inputs[1]) await inputs[1].setValue('alice@example.com')
    if (inputs[2]) await inputs[2].setValue('supersecret')
    await wrapper.find('form').trigger('submit')
    const registerEvents = wrapper.emitted('register')
    expect(registerEvents).toBeTruthy()
    expect(registerEvents?.[0]?.[0]).toEqual({
      username: 'alice',
      email: 'alice@example.com',
      password: 'supersecret',
    })
  })

  it('emits "dismiss" when the close button is clicked (dismissible=true)', async () => {
    const wrapper = mountPanel({ dismissible: true })
    const closeBtn = wrapper.find('.auth-panel__close')
    expect(closeBtn.exists()).toBe(true)
    await closeBtn.trigger('click')
    expect(wrapper.emitted('dismiss')).toBeTruthy()
  })

  it('does not render the close button when dismissible=false (default)', () => {
    const wrapper = mountPanel()
    expect(wrapper.find('.auth-panel__close').exists()).toBe(false)
  })

  it('emits "forgot-password" when the link is clicked', async () => {
    const wrapper = mountPanel()
    const link = wrapper.find('.auth-panel__link')
    await link.trigger('click')
    expect(wrapper.emitted('forgot-password')).toBeTruthy()
  })

  it('emits "oauth" with the provider when a social button is clicked', async () => {
    const wrapper = mountPanel()
    const socialButtons = wrapper.findAll('.imago-btn-auth-social')
    expect(socialButtons.length).toBe(2)
    if (socialButtons[0]) await socialButtons[0].trigger('click')
    expect(wrapper.emitted('oauth')).toBeTruthy()
    expect(wrapper.emitted('oauth')?.[0]?.[0]).toBe('github')
    if (socialButtons[1]) await socialButtons[1].trigger('click')
    expect(wrapper.emitted('oauth')?.[1]?.[0]).toBe('google')
  })

  it('renders the error banner when the error prop is set', () => {
    const wrapper = mountPanel({ error: '登录失败' })
    expect(wrapper.text()).toContain('登录失败')
  })

  it('hides the remember row when showRememberMe=false', () => {
    const wrapper = mountPanel({ showRememberMe: false })
    expect(wrapper.find('.auth-panel__row-options').exists()).toBe(false)
  })

  it('hides the security note when showSecurityNote=false', () => {
    const wrapper = mountPanel({ showSecurityNote: false })
    expect(wrapper.find('.auth-panel__security-note').exists()).toBe(false)
  })
})
